package com.seaquake6324.civitas.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.*;import java.util.*;import net.minecraft.nbt.*;import net.minecraft.world.entity.EquipmentSlot;import org.junit.jupiter.api.Test;

class CitizenEquipmentSavedDataTest {
 @Test void schema1RoundTripsOpaqueStacksAndQuarantinesBrokenNeighbors(){CitizenEquipmentSavedData data=new CitizenEquipmentSavedData();UUID citizen=UUID.randomUUID();CompoundTag stack=new CompoundTag();stack.putString("id","minecraft:iron_sword");data.putRawSnapshot(new CitizenEquipmentSavedData.Snapshot(citizen,Map.of(EquipmentSlot.MAINHAND,stack),1,3));CompoundTag root=data.saveTag();assertEquals(1,root.getIntOr("SchemaVersion",0));CompoundTag broken=new CompoundTag();broken.putString("CitizenId","bad");root.getListOrEmpty("Snapshots").add(broken);CitizenEquipmentSavedData loaded=CitizenEquipmentSavedData.load(root);assertEquals(stack,loaded.snapshot(citizen).orElseThrow().items().get(EquipmentSlot.MAINHAND));assertEquals(1,loaded.quarantinedSnapshots());}
 @Test void malformedStackIsIsolatedWithoutDiscardingValidSlots(){CitizenEquipmentSavedData data=new CitizenEquipmentSavedData();UUID citizen=UUID.randomUUID();data.putRawSnapshot(new CitizenEquipmentSavedData.Snapshot(citizen,Map.of(EquipmentSlot.HEAD,new CompoundTag()),1,0));CompoundTag root=data.saveTag();CompoundTag item=(CompoundTag)((CompoundTag)root.getListOrEmpty("Snapshots").getFirst()).getListOrEmpty("Items").getFirst();item.putString("Slot","bad");CitizenEquipmentSavedData loaded=CitizenEquipmentSavedData.load(root);assertEquals(1,loaded.size());assertTrue(loaded.snapshot(citizen).orElseThrow().items().isEmpty());assertEquals(1,loaded.quarantinedStacks());}
 @Test void futureSchemaIsPreservedReadOnly(){CompoundTag root=new CompoundTag();root.putInt("SchemaVersion",99);root.putString("Future","keep");CitizenEquipmentSavedData loaded=CitizenEquipmentSavedData.load(root);assertTrue(loaded.readOnly());assertEquals("keep",loaded.saveTag().getStringOr("Future",""));}
 @Test void snapshotBatchIsBoundedAndResumesFromStableCursor(){CitizenEquipmentSavedData data=new CitizenEquipmentSavedData();List<UUID>ids=new ArrayList<>();for(int i=0;i<5;i++){UUID id=UUID.randomUUID();ids.add(id);data.putRawSnapshot(new CitizenEquipmentSavedData.Snapshot(id,Map.of(EquipmentSlot.MAINHAND,new CompoundTag()),1,0));}ids.sort(UUID::compareTo);var first=data.snapshotBatch(null,2);assertEquals(ids.subList(0,2),first.records().stream().map(CitizenEquipmentSavedData.Snapshot::citizenId).toList());var second=data.snapshotBatch(first.nextCursor(),2);assertEquals(ids.subList(2,4),second.records().stream().map(CitizenEquipmentSavedData.Snapshot::citizenId).toList());var third=data.snapshotBatch(second.nextCursor(),2);assertEquals(List.of(ids.get(4)),third.records().stream().map(CitizenEquipmentSavedData.Snapshot::citizenId).toList());var wrapped=data.snapshotBatch(third.nextCursor(),2);assertTrue(wrapped.wrapped());assertEquals(ids.subList(0,2),wrapped.records().stream().map(CitizenEquipmentSavedData.Snapshot::citizenId).toList());}
}
