package com.seaquake6324.civitas.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.*;
import com.seaquake6324.civitas.application.CreateMigrationGroupService;
import com.seaquake6324.civitas.application.StartOutMigrationService;
import com.seaquake6324.civitas.domain.population.*;
import java.util.*;
import net.minecraft.nbt.CompoundTag;
import org.junit.jupiter.api.Test;

class MigrationPersistenceTest {
    @Test void sourceBackedHouseholdRoundTripsAndSettlesAtomically(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID(),groupId=UUID.randomUUID(),residence=UUID.randomUUID();var created=create(data,groupId,city,4,1,1,1);assertTrue(created.success());assertEquals(4,created.group().members().size());assertEquals(2,created.group().children().size());PopulationSavedData loaded=PopulationSavedData.load(data.saveTag());MigrationGroupRecord group=loaded.migration(groupId).orElseThrow();for(UUID member:group.members()){assertNull(loaded.citizen(member).orElseThrow().cityId());assertEquals(groupId,loaded.migrationForMember(member).orElseThrow().id());}MigrationGroupRecord applied=group.applied(500);assertTrue(loaded.updateMigration(applied,group.revision()));assertTrue(loaded.settleMigration(applied,applied.revision(),residence,300));assertTrue(loaded.migration(groupId).isEmpty());Household household=loaded.household(groupId).orElseThrow();assertEquals(2,household.partners().size());assertEquals(2,household.children().size());for(UUID member:group.members()){CitizenRecord citizen=loaded.citizen(member).orElseThrow();assertEquals(city,citizen.cityId());assertEquals(groupId,citizen.householdId());assertEquals(residence,citizen.residenceId());assertEquals(groupId,loaded.migrationOrigin(member).orElseThrow().groupId());assertEquals(group.memberPositions().get(member).longValue(),loaded.location(member).orElseThrow().position());}for(UUID child:group.children()){ParentageRecord parentage=loaded.parentage(child).orElseThrow();assertEquals(ParentageRecord.Source.MIGRATION_WITH_SOURCE,parentage.source());assertEquals(2,parentage.parents().size());}PopulationSavedData restored=PopulationSavedData.load(loaded.saveTag());assertEquals(4,restored.migrationOriginCount());assertEquals(4,restored.locationCount());assertEquals(household,restored.household(groupId).orElseThrow());}
    @Test void rejectedHouseholdEntersRegionalPoolAndCanBeReactivatedWithoutRecreatingPeople(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID(),nextCity=UUID.randomUUID(),groupId=UUID.randomUUID();MigrationGroupRecord group=create(data,groupId,city,1,0,0,0).group();MigrationGroupRecord applied=group.applied(500);assertTrue(data.updateMigration(applied,group.revision()));MigrationGroupRecord leaving=applied.departing();assertTrue(data.updateMigration(leaving,applied.revision()));assertTrue(data.poolDepartedMigration(leaving,leaving.revision()));MigrationGroupRecord pooled=data.migration(groupId).orElseThrow();assertEquals(MigrationGroupRecord.State.REGIONAL_POOL,pooled.state());assertEquals(1,data.regionalPoolCount());assertTrue(group.members().stream().allMatch(id->data.citizen(id).isPresent()));MigrationGroupRecord active=pooled.reactivate(nextCity,99,100,600,75);assertTrue(data.updateMigration(active,pooled.revision()));assertEquals(nextCity,data.migration(groupId).orElseThrow().targetCityId());assertEquals(MigrationGroupRecord.State.APPROACHING,data.migration(groupId).orElseThrow().state());assertEquals(0,data.regionalPoolCount());assertEquals(0,data.migrationOriginCount());}
    @Test void duplicateMigrationIsQuarantinedWithoutDroppingValidNeighbor(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID(),groupId=UUID.randomUUID();create(data,groupId,city,1,0,0,0);CompoundTag root=data.saveTag();root.getListOrEmpty("Migrations").add(root.getListOrEmpty("Migrations").getFirst().copy());PopulationSavedData loaded=PopulationSavedData.load(root);assertEquals(1,loaded.activeMigrationCount());assertEquals(1,loaded.quarantinedMigrations());assertEquals(1,loaded.citizenCount());}
    @Test void futureSchemaPreservesMigrationRootReadOnly(){PopulationSavedData data=new PopulationSavedData();create(data,UUID.randomUUID(),UUID.randomUUID(),1,0,0,0);CompoundTag root=data.saveTag();root.putInt("SchemaVersion",99);PopulationSavedData loaded=PopulationSavedData.load(root);assertTrue(loaded.readOnly());assertEquals(99,loaded.saveTag().getIntOr("SchemaVersion",0));assertEquals(0,loaded.activeMigrationCount());}
    @Test void v6MigratesToEmptyV8MigrationAndLocationIndexesWithoutInventingCitizens(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID();CitizenRecord settled=new CitizenRecord(UUID.randomUUID(),"Mira","North",CitizenRace.HUMAN,"human_0",Gender.FEMALE,100,100,city,null,null,null,"",100,CitizenNeeds.neutral(),Map.of(),Set.of(),50,0,CitizenRuntimeState.VIRTUAL,0,70,0,1);data.putCitizen(settled);CompoundTag root=data.saveTag();root.putInt("SchemaVersion",6);root.remove("Migrations");root.remove("MigrationOrigins");root.remove("MigrationCursor");root.remove("CitizenLocations");PopulationSavedData loaded=PopulationSavedData.load(root);assertEquals("v6_to_v13",loaded.migrationResult());assertEquals(0,loaded.activeMigrationCount());assertEquals(0,loaded.migrationOriginCount());assertEquals(0,loaded.locationCount());assertTrue(loaded.citizen(settled.id()).isPresent());assertEquals(13,loaded.saveTag().getIntOr("SchemaVersion",0));}
    @Test void settledNpcHouseholdBeginsDepartureAtomically(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID();CitizenRecord a=settled(UUID.randomUUID(),city,"Ana"),b=settled(UUID.randomUUID(),city,"Borin");data.putCitizen(a);data.putCitizen(b);Household household=new Household(UUID.randomUUID(),city,Set.of(FamilyMemberRef.citizen(a.id()),FamilyMemberRef.citizen(b.id())),Set.of(),null,30,20,1);assertTrue(data.createHousehold(household,Map.of(a.id(),a.revision(),b.id(),b.revision())));a=data.citizen(a.id()).orElseThrow();b=data.citizen(b.id()).orElseThrow();assertTrue(data.updateLocation(new CitizenLocationRecord(a.id(),city,"minecraft:overworld",1,100,1),a.revision(),0));assertTrue(data.updateLocation(new CitizenLocationRecord(b.id(),city,"minecraft:overworld",2,100,1),b.revision(),0));Set<UUID> members=Set.of(a.id(),b.id());MigrationGroupRecord group=new MigrationGroupRecord(UUID.randomUUID(),city,"minecraft:overworld",9,8,members,members,Set.of(),Set.of(),Map.of(a.id(),1L,b.id(),2L),MigrationGroupRecord.State.DEPARTING,75,100,100,1);var result=new StartOutMigrationService().start(data,group,household,Map.of(a.id(),a.revision(),b.id(),b.revision()),16);assertTrue(result.success());assertTrue(data.household(household.id()).isEmpty());assertNull(data.citizen(a.id()).orElseThrow().cityId());assertNull(data.citizen(b.id()).orElseThrow().cityId());assertTrue(data.location(a.id()).isEmpty());assertEquals(group,data.migration(group.id()).orElseThrow());PopulationSavedData restored=PopulationSavedData.load(data.saveTag());assertEquals(group,restored.migration(group.id()).orElseThrow());}
    @Test void schema11MigrationDerivesSourceGuardiansAndInitializesDepartureCursors(){PopulationSavedData data=new PopulationSavedData();MigrationGroupRecord group=create(data,UUID.randomUUID(),UUID.randomUUID(),3,1,1,0).group();CompoundTag root=data.saveTag();root.putInt("SchemaVersion",11);root.remove("OutMigrationHouseholdCursor");root.remove("OutMigrationCitizenCursor");((CompoundTag)root.getListOrEmpty("Migrations").getFirst()).remove("Guardians");PopulationSavedData loaded=PopulationSavedData.load(root);assertEquals("v11_to_v13",loaded.migrationResult());assertEquals(group.partners(),loaded.migration(group.id()).orElseThrow().guardians());assertNull(loaded.outMigrationHouseholdCursor());assertNull(loaded.outMigrationCitizenCursor());assertEquals(13,loaded.saveTag().getIntOr("SchemaVersion",0));}
    private static CitizenRecord settled(UUID id,UUID city,String name){return new CitizenRecord(id,name,"Vale",CitizenRace.HUMAN,"human_0",Gender.FEMALE,500,500,city,null,null,null,"",100,CitizenNeeds.neutral(),Map.of(),Set.of(),50,50,CitizenRuntimeState.VIRTUAL,0,75,0,1);}
    private static CreateMigrationGroupService.Result create(PopulationSavedData data,UUID group,UUID city,int max,double couple,double child,double second){return new CreateMigrationGroupService().create(data,new CreateMigrationGroupService.Request(group,city,"minecraft:overworld",new net.minecraft.core.BlockPos(0,64,0).asLong(),new net.minecraft.core.BlockPos(20,64,20).asLong(),100,70,16,max,couple,child,second,24000,12,18,60,new LifespanRules(60,90)));}
}
