package com.seaquake6324.civitas.domain.population;

import java.util.Map;import java.util.Set;import java.util.UUID;

/** Unique persistent authority. A world entity may only reference this record. */
public record CitizenRecord(UUID id,String givenName,String familyName,CitizenRace race,String appearanceKey,
        Gender gender,long ageTicks,long lastAgeUpdateTick,UUID cityId,UUID householdId,UUID residenceId,
        UUID workBuildingId,String profession,int health,CitizenNeeds needs,Map<String,Integer> skills,
        Set<UUID> relationships,double settlementWillingness,double migrationWillingness,
        CitizenRuntimeState runtimeState,long runtimeLockUntilTick,int lifespanYears,long diedAtTick,
        CitizenDeathCause deathCause,long revision){
    public CitizenRecord{
        givenName=required(givenName);familyName=required(familyName);appearanceKey=required(appearanceKey);profession=profession==null?"":profession;health=clamp(health);ageTicks=Math.max(0,ageTicks);lastAgeUpdateTick=Math.max(0,lastAgeUpdateTick);skills=Map.copyOf(skills);relationships=Set.copyOf(relationships);settlementWillingness=clamp(settlementWillingness);migrationWillingness=clamp(migrationWillingness);revision=Math.max(0,revision);runtimeLockUntilTick=Math.max(0,runtimeLockUntilTick);lifespanYears=Math.max(1,lifespanYears);diedAtTick=Math.max(0,diedAtTick);deathCause=deathCause==null?(diedAtTick>0?CitizenDeathCause.OLD_AGE:CitizenDeathCause.NONE):deathCause;if((diedAtTick==0)!=(deathCause==CitizenDeathCause.NONE))throw new IllegalArgumentException("death cause does not match death time");
    }
    /** Compatibility constructor for schema 9 and older call sites; all old permanent deaths were old age. */
    public CitizenRecord(UUID id,String givenName,String familyName,CitizenRace race,String appearanceKey,Gender gender,long ageTicks,long lastAgeUpdateTick,UUID cityId,UUID householdId,UUID residenceId,UUID workBuildingId,String profession,int health,CitizenNeeds needs,Map<String,Integer>skills,Set<UUID>relationships,double settlementWillingness,double migrationWillingness,CitizenRuntimeState runtimeState,long runtimeLockUntilTick,int lifespanYears,long diedAtTick,long revision){this(id,givenName,familyName,race,appearanceKey,gender,ageTicks,lastAgeUpdateTick,cityId,householdId,residenceId,workBuildingId,profession,health,needs,skills,relationships,settlementWillingness,migrationWillingness,runtimeState,runtimeLockUntilTick,lifespanYears,diedAtTick,diedAtTick>0?CitizenDeathCause.OLD_AGE:CitizenDeathCause.NONE,revision);}
    public CitizenRecord(UUID id,String givenName,String familyName,CitizenRace race,String appearanceKey,Gender gender,long ageTicks,long lastAgeUpdateTick,UUID cityId,UUID householdId,UUID residenceId,UUID workBuildingId,String profession,int health,CitizenNeeds needs,Map<String,Integer>skills,Set<UUID>relationships,double settlementWillingness,double migrationWillingness,CitizenRuntimeState runtimeState,long runtimeLockUntilTick,long revision){this(id,givenName,familyName,race,appearanceKey,gender,ageTicks,lastAgeUpdateTick,cityId,householdId,residenceId,workBuildingId,profession,health,needs,skills,relationships,settlementWillingness,migrationWillingness,runtimeState,runtimeLockUntilTick,new LifespanRules(60,90).years(id),0,CitizenDeathCause.NONE,revision);}
    public String displayName(){return givenName+" "+familyName;}public boolean alive(){return deathCause==CitizenDeathCause.NONE;}
    public CitizenRecord withGender(Gender value){return copy(value,ageTicks,lastAgeUpdateTick,runtimeState,revision+1);}
    public CitizenRecord withRuntimeState(CitizenRuntimeState value){return copy(gender,ageTicks,lastAgeUpdateTick,value,revision+1);}
    public CitizenRecord withResidence(UUID value){return full(gender,ageTicks,lastAgeUpdateTick,cityId,householdId,value,workBuildingId,profession,health,needs,skills,relationships,settlementWillingness,migrationWillingness,runtimeState,runtimeLockUntilTick,lifespanYears,diedAtTick,deathCause,revision+1);}
    public CitizenRecord withHousehold(UUID value){return full(gender,ageTicks,lastAgeUpdateTick,cityId,value,residenceId,workBuildingId,profession,health,needs,skills,relationships,settlementWillingness,migrationWillingness,runtimeState,runtimeLockUntilTick,lifespanYears,diedAtTick,deathCause,revision+1);}
    public CitizenRecord settle(UUID city,UUID household,UUID residence){if(city==null)throw new IllegalArgumentException("missing settlement city");return full(gender,ageTicks,lastAgeUpdateTick,city,household,residence,workBuildingId,profession,health,needs,skills,relationships,settlementWillingness,migrationWillingness,runtimeState,runtimeLockUntilTick,lifespanYears,diedAtTick,deathCause,revision+1);}
    public CitizenRecord leaveCity(){if(cityId==null)return this;return full(gender,ageTicks,lastAgeUpdateTick,null,null,null,null,"",health,needs,skills,relationships,settlementWillingness,migrationWillingness,runtimeState,runtimeLockUntilTick,lifespanYears,diedAtTick,deathCause,revision+1);}
    public CitizenRecord withHealth(int value){return full(gender,ageTicks,lastAgeUpdateTick,cityId,householdId,residenceId,workBuildingId,profession,value,needs,skills,relationships,settlementWillingness,migrationWillingness,runtimeState,runtimeLockUntilTick,lifespanYears,diedAtTick,deathCause,revision+1);}
    public CitizenRecord withRuntimeLock(long until){return full(gender,ageTicks,lastAgeUpdateTick,cityId,householdId,residenceId,workBuildingId,profession,health,needs,skills,relationships,settlementWillingness,migrationWillingness,CitizenRuntimeState.LOCKED,until,lifespanYears,diedAtTick,deathCause,revision+1);}
    public CitizenRecord advanceAge(long now){long next=Math.max(0,ageTicks+Math.max(0,now-lastAgeUpdateTick));return copy(gender,next,Math.max(now,lastAgeUpdateTick),runtimeState,revision+1);}
    public CitizenRecord dieOfOldAge(long now){return die(now,CitizenDeathCause.OLD_AGE);}public CitizenRecord dieFromInvasion(long now){return die(now,CitizenDeathCause.INVASION);}
    public CitizenRecord die(long now,CitizenDeathCause cause){if(cause==null||cause==CitizenDeathCause.NONE)throw new IllegalArgumentException("permanent death requires an explicit cause");if(!alive())return this;return full(gender,ageTicks,Math.max(now,lastAgeUpdateTick),cityId,householdId,residenceId,workBuildingId,profession,0,needs,skills,relationships,settlementWillingness,migrationWillingness,CitizenRuntimeState.VIRTUAL,0,lifespanYears,Math.max(1,now),cause,revision+1);}
    private CitizenRecord copy(Gender nextGender,long nextAge,long nextUpdate,CitizenRuntimeState nextState,long nextRevision){return full(nextGender,nextAge,nextUpdate,cityId,householdId,residenceId,workBuildingId,profession,health,needs,skills,relationships,settlementWillingness,migrationWillingness,nextState,nextState==CitizenRuntimeState.LOCKED?runtimeLockUntilTick:0,lifespanYears,diedAtTick,deathCause,nextRevision);}
    private CitizenRecord full(Gender g,long age,long update,UUID city,UUID household,UUID residence,UUID work,String job,int hp,CitizenNeeds n,Map<String,Integer>s,Set<UUID>rels,double settle,double migrate,CitizenRuntimeState state,long lock,int lifespan,long died,CitizenDeathCause cause,long rev){return new CitizenRecord(id,givenName,familyName,race,appearanceKey,g,age,update,city,household,residence,work,job,hp,n,s,rels,settle,migrate,state,lock,lifespan,died,cause,rev);}
    private static String required(String value){if(value==null||value.isBlank())throw new IllegalArgumentException("blank citizen field");return value.trim();}private static int clamp(int value){return Math.max(0,Math.min(100,value));}private static double clamp(double value){return Math.max(0,Math.min(100,value));}
}
