package com.seaquake6324.civitas.domain.population;
import com.seaquake6324.civitas.domain.building.*;import java.util.*;
/** Explainable city population snapshot. Only current limitations are reported. */
public record PopulationDashboard(PopulationSummary composition,int housingCapacity,int housedCitizens,int unassignedCitizens,
        int invalidResidenceReferences,int employedCitizens,int householdCount,int partneredHouseholds,int householdsWithChildren,
        int permanentDeaths,long latestDeathAtTick,
        double averageFoodCoverage,double averageHousingCoverage,double averageSettlementWillingness,double averageMigrationWillingness,
        Set<Limitation>limitations,boolean truncated){public PopulationDashboard{limitations=Set.copyOf(limitations);}
 public enum Limitation{NO_POPULATION,HOUSING_CAPACITY_SHORTFALL,UNASSIGNED_RESIDENCE,INVALID_RESIDENCE_REFERENCE,NO_HOUSEHOLD_DATA,BIRTH_TREND_NOT_AVAILABLE,DEATH_HISTORY_NOT_ACTIVE,MIGRATION_TREND_NOT_AVAILABLE,OUT_MIGRATION_NOT_ACTIVE}
 public static PopulationDashboard from(UUID cityId,Collection<CitizenRecord>citizens,Collection<Household>households,Collection<BuildingRecord>buildings,AgeRules ageRules,boolean truncated){Map<UUID,BuildingRecord>validResidences=new HashMap<>();int capacity=0;for(BuildingRecord b:buildings)if(cityId.equals(b.cityId())&&b.purpose()==BuildingPurpose.RESIDENCE&&b.status()==BuildingStatus.VALID){validResidences.put(b.id(),b);capacity+=b.capacity();}List<CitizenRecord>cityRecords=citizens.stream().filter(c->cityId.equals(c.cityId())).toList();List<CitizenRecord>cityCitizens=cityRecords.stream().filter(CitizenRecord::alive).toList();int deaths=(int)cityRecords.stream().filter(c->!c.alive()).count();long latestDeath=cityRecords.stream().mapToLong(CitizenRecord::diedAtTick).max().orElse(0);int housed=0,unassigned=0,invalid=0,employed=0;double settlement=0,migration=0;for(CitizenRecord c:cityCitizens){if(c.residenceId()==null)unassigned++;else if(validResidences.containsKey(c.residenceId()))housed++;else invalid++;if(c.workBuildingId()!=null||!c.profession().isBlank())employed++;settlement+=c.settlementWillingness();migration+=c.migrationWillingness();}List<Household>cityHouseholds=households.stream().filter(h->cityId.equals(h.cityId())).toList();int partnered=0,withChildren=0;double food=0,housing=0;for(Household h:cityHouseholds){if(h.partners().size()>=2)partnered++;if(!h.children().isEmpty())withChildren++;food+=h.foodCoverage();housing+=h.housingCoverage();}EnumSet<Limitation>limits=EnumSet.of(Limitation.BIRTH_TREND_NOT_AVAILABLE,Limitation.MIGRATION_TREND_NOT_AVAILABLE,Limitation.OUT_MIGRATION_NOT_ACTIVE);int total=cityCitizens.size();if(total==0)limits.add(Limitation.NO_POPULATION);if(capacity<total)limits.add(Limitation.HOUSING_CAPACITY_SHORTFALL);if(unassigned>0)limits.add(Limitation.UNASSIGNED_RESIDENCE);if(invalid>0)limits.add(Limitation.INVALID_RESIDENCE_REFERENCE);if(cityHouseholds.isEmpty())limits.add(Limitation.NO_HOUSEHOLD_DATA);return new PopulationDashboard(PopulationSummary.from(cityId,cityCitizens,ageRules),capacity,housed,unassigned,invalid,employed,cityHouseholds.size(),partnered,withChildren,deaths,latestDeath,average(food,cityHouseholds.size()),average(housing,cityHouseholds.size()),average(settlement,total),average(migration,total),limits,truncated);}
 private static double average(double sum,int count){return count==0?0:sum/count;}
}
