package com.seaquake6324.civitas.domain.security;
import com.seaquake6324.civitas.domain.territory.NeglectStage;import com.seaquake6324.civitas.domain.territory.TerritoryChunkState;import java.util.*;
/** Centralized first-pass balance hypothesis used by diagnostics and invasion-site selection. */
public final class SecurityRiskRules{
 public SecurityCell evaluate(UUID cityId,long chunk,SecurityCellEvidence e,Weights w,long revision){EnumMap<SecurityFactor,SecurityContribution>parts=new EnumMap<>(SecurityFactor.class);put(parts,SecurityFactor.CIVILITY,100-e.civility(),w.civility());put(parts,SecurityFactor.ACTIVITY,100-e.activity(),w.activity());put(parts,SecurityFactor.BUILT_SAFETY,100-e.builtSafety(),w.builtSafety());put(parts,SecurityFactor.PATROL_COVERAGE,100-e.patrolCoverage(),w.patrolCoverage());put(parts,SecurityFactor.GUARD_RESPONSE,100-e.guardResponse(),w.guardResponse());put(parts,SecurityFactor.INFILTRATION_ACCESS,e.infiltrationAccess(),w.infiltrationAccess());put(parts,SecurityFactor.UNDERGROUND_DARKNESS,e.undergroundDarkness(),w.undergroundDarkness());put(parts,SecurityFactor.BORDER_EXPOSURE,100.0/(e.borderDistance()+1),w.borderExposure());put(parts,SecurityFactor.NEGLECT,neglect(e.neglectStage()),w.neglect());double recent=e.lastDefenseResult()==TerritoryChunkState.DefenseResult.FAILURE?Math.max(0,100.0*(1.0-Math.max(0,e.assessedAt()-e.lastDefenseAt())/(double)w.failureMemoryTicks())):0;put(parts,SecurityFactor.RECENT_DEFENSE_FAILURE,recent,w.recentFailure());put(parts,SecurityFactor.CITY_SCALE,Math.min(100,100.0*e.territorySize()/w.fullScaleChunks()),w.cityScale());double totalWeight=parts.values().stream().mapToDouble(SecurityContribution::weight).sum();double total=parts.values().stream().mapToDouble(SecurityContribution::weightedRisk).sum();SecurityFactor primary=parts.entrySet().stream().max(Comparator.comparingDouble(x->x.getValue().weightedRisk())).map(Map.Entry::getKey).orElse(SecurityFactor.CIVILITY);EnumSet<SecurityCell.MissingEvidence>missing=EnumSet.noneOf(SecurityCell.MissingEvidence.class);if(!e.infiltrationEvidenceLinked())missing.add(SecurityCell.MissingEvidence.INFILTRATION_SOURCE);if(!e.undergroundEvidenceLinked())missing.add(SecurityCell.MissingEvidence.UNDERGROUND_DARKNESS);if(!e.patrolEvidenceLinked())missing.add(SecurityCell.MissingEvidence.PATROL_COVERAGE);if(!e.guardEvidenceLinked())missing.add(SecurityCell.MissingEvidence.GUARD_RESPONSE);if(!e.buildingEvidenceLinked())missing.add(SecurityCell.MissingEvidence.BUILDING_RECORD_LINK);if(e.borderTopologyLimited())missing.add(SecurityCell.MissingEvidence.BORDER_TOPOLOGY_LIMIT);return new SecurityCell(cityId,chunk,e,parts,totalWeight<=0?0:total/totalWeight,primary,missing,revision);}
 private static void put(Map<SecurityFactor,SecurityContribution>parts,SecurityFactor factor,double risk,double weight){parts.put(factor,new SecurityContribution(risk,weight,risk*weight));}
 private static double neglect(NeglectStage stage){return switch(stage){case HEALTHY->0;case WARNING->35;case ABANDONED->70;case RETRACTABLE->100;};}
 public record Weights(double civility,double activity,double builtSafety,double patrolCoverage,double guardResponse,double infiltrationAccess,double undergroundDarkness,double borderExposure,double neglect,double recentFailure,double cityScale,int failureMemoryTicks,int fullScaleChunks){public Weights{if(civility<0||activity<0||builtSafety<0||patrolCoverage<0||guardResponse<0||infiltrationAccess<0||undergroundDarkness<0||borderExposure<0||neglect<0||recentFailure<0||cityScale<0||failureMemoryTicks<1||fullScaleChunks<1)throw new IllegalArgumentException("invalid security weights");}public Weights(double civility,double activity,double builtSafety,double borderExposure,double neglect,double recentFailure,double cityScale,int failureMemoryTicks,int fullScaleChunks){this(civility,activity,builtSafety,0,0,0,0,borderExposure,neglect,recentFailure,cityScale,failureMemoryTicks,fullScaleChunks);}public Weights(double civility,double activity,double builtSafety,double patrolCoverage,double guardResponse,double borderExposure,double neglect,double recentFailure,double cityScale,int failureMemoryTicks,int fullScaleChunks){this(civility,activity,builtSafety,patrolCoverage,guardResponse,0,0,borderExposure,neglect,recentFailure,cityScale,failureMemoryTicks,fullScaleChunks);}}
}
