package com.seaquake6324.civitas.infrastructure.persistence;

import com.mojang.logging.LogUtils;import com.mojang.serialization.Codec;import com.seaquake6324.civitas.domain.security.GuardEquipment;import com.seaquake6324.civitas.infrastructure.entity.CitizenEntity;import java.util.*;import net.minecraft.core.RegistryAccess;import net.minecraft.nbt.*;import net.minecraft.resources.Identifier;import net.minecraft.server.MinecraftServer;import net.minecraft.tags.ItemTags;import net.minecraft.world.entity.EquipmentSlot;import net.minecraft.world.item.*;import net.minecraft.world.level.saveddata.*;import org.slf4j.Logger;

/** Infrastructure authority for real equipment while a citizen entity is virtualized. */
public final class CitizenEquipmentSavedData extends SavedData {
    public static final int SCHEMA_VERSION=1;private static final Logger LOGGER=LogUtils.getLogger();
    private static final Codec<CitizenEquipmentSavedData>CODEC=CompoundTag.CODEC.xmap(CitizenEquipmentSavedData::load,CitizenEquipmentSavedData::saveTag);
    private static final SavedDataType<CitizenEquipmentSavedData>TYPE=new SavedDataType<>(Identifier.fromNamespaceAndPath("civitas","citizen_equipment"),CitizenEquipmentSavedData::new,CODEC);
    private static final List<EquipmentSlot>SLOTS=List.of(EquipmentSlot.MAINHAND,EquipmentSlot.OFFHAND,EquipmentSlot.HEAD,EquipmentSlot.CHEST,EquipmentSlot.LEGS,EquipmentSlot.FEET);
    private final NavigableMap<UUID,Snapshot>snapshots=new TreeMap<>();private boolean readOnly;private CompoundTag protectedRoot;private int quarantinedSnapshots,quarantinedStacks;private String migrationResult="created_v1";private long captures,restores,decodeFailures;

    public static CitizenEquipmentSavedData get(MinecraftServer server){return server.overworld().getDataStorage().computeIfAbsent(TYPE);}
    public boolean capture(CitizenEntity entity,long expectedRevision){if(readOnly)return false;UUID citizen=entity.citizenId().orElse(null);if(citizen==null)return false;var ops=entity.registryAccess().createSerializationContext(NbtOps.INSTANCE);EnumMap<EquipmentSlot,Tag>items=new EnumMap<>(EquipmentSlot.class);try{for(EquipmentSlot slot:SLOTS){ItemStack stack=entity.getItemBySlot(slot);if(!stack.isEmpty())items.put(slot,ItemStack.OPTIONAL_CODEC.encodeStart(ops,stack).getOrThrow());}}catch(RuntimeException ex){LOGGER.warn("Could not encode Civitas citizen equipment {}",citizen,ex);return false;}Snapshot previous=snapshots.get(citizen);if(items.isEmpty()){if(previous!=null){snapshots.remove(citizen);setDirty();}return true;}if(previous!=null&&previous.items().equals(items))return true;long next=previous==null?1:previous.revision()+1;snapshots.put(citizen,new Snapshot(citizen,items,next,Math.max(0,expectedRevision)));captures++;setDirty();return true;}
    public boolean restore(CitizenEntity entity){UUID citizen=entity.citizenId().orElse(null);Snapshot snapshot=citizen==null?null:snapshots.get(citizen);if(snapshot==null)return false;var ops=entity.registryAccess().createSerializationContext(NbtOps.INSTANCE);boolean any=false;for(var entry:snapshot.items().entrySet())try{ItemStack stack=ItemStack.OPTIONAL_CODEC.parse(ops,entry.getValue()).getOrThrow();entity.setItemSlot(entry.getKey(),stack.copy());any|=!stack.isEmpty();}catch(RuntimeException ex){decodeFailures++;LOGGER.warn("Could not decode Civitas citizen equipment {} slot {}",citizen,entry.getKey(),ex);}restores++;return any;}
    public GuardEquipment guardEquipment(UUID citizenId,RegistryAccess registries){Snapshot snapshot=snapshots.get(citizenId);if(snapshot==null)return new GuardEquipment(false,0,false);var ops=registries.createSerializationContext(NbtOps.INSTANCE);boolean weapon=false,shield=false;int armor=0;for(var entry:snapshot.items().entrySet())try{ItemStack stack=ItemStack.OPTIONAL_CODEC.parse(ops,entry.getValue()).getOrThrow();if(entry.getKey()==EquipmentSlot.MAINHAND)weapon=stack.is(ItemTags.SWORDS)||stack.is(ItemTags.AXES)||stack.is(ItemTags.BOW_ENCHANTABLE)||stack.is(ItemTags.CROSSBOW_ENCHANTABLE)||stack.is(ItemTags.TRIDENT_ENCHANTABLE);else if(entry.getKey()==EquipmentSlot.OFFHAND)shield=stack.is(Items.SHIELD);else if(!stack.isEmpty())armor++;}catch(RuntimeException ex){decodeFailures++;}return new GuardEquipment(weapon,armor,shield);}
    public List<ItemStack> decodedItems(UUID citizenId,RegistryAccess registries){Snapshot snapshot=snapshots.get(citizenId);if(snapshot==null)return List.of();var ops=registries.createSerializationContext(NbtOps.INSTANCE);List<ItemStack>result=new ArrayList<>();for(Tag encoded:snapshot.items().values())try{ItemStack stack=ItemStack.OPTIONAL_CODEC.parse(ops,encoded).getOrThrow();if(!stack.isEmpty())result.add(stack.copy());}catch(RuntimeException ex){decodeFailures++;LOGGER.warn("Could not decode Civitas citizen equipment {} for death drop",citizenId,ex);}return List.copyOf(result);}
    public SnapshotBatch snapshotBatch(UUID after,int limit){if(limit<1)return new SnapshotBatch(List.of(),null,false);NavigableMap<UUID,Snapshot>tail=after==null?snapshots:snapshots.tailMap(after,false);List<Snapshot>records=new ArrayList<>(Math.min(limit,tail.size()));for(Snapshot snapshot:tail.values()){if(records.size()>=limit)break;records.add(snapshot);}boolean wrapped=records.isEmpty()&&after!=null&&!snapshots.isEmpty();if(wrapped)for(Snapshot snapshot:snapshots.values()){if(records.size()>=limit)break;records.add(snapshot);}UUID next=records.isEmpty()?null:records.getLast().citizenId();return new SnapshotBatch(List.copyOf(records),next,wrapped);}
    public void remove(UUID citizenId){if(!readOnly&&snapshots.remove(citizenId)!=null)setDirty();}
    public Optional<Snapshot>snapshot(UUID citizenId){return Optional.ofNullable(snapshots.get(citizenId));}public int size(){return snapshots.size();}public boolean readOnly(){return readOnly;}public int quarantinedSnapshots(){return quarantinedSnapshots;}public int quarantinedStacks(){return quarantinedStacks;}public String migrationResult(){return migrationResult;}public Metrics metrics(){return new Metrics(captures,restores,decodeFailures,snapshots.size());}public record Metrics(long captures,long restores,long decodeFailures,int snapshots){}
    public record SnapshotBatch(List<Snapshot>records,UUID nextCursor,boolean wrapped){}
    public record Snapshot(UUID citizenId,Map<EquipmentSlot,Tag>items,long revision,long citizenRevision){public Snapshot{Objects.requireNonNull(citizenId);if(revision<1||citizenRevision<0)throw new IllegalArgumentException("invalid equipment snapshot");EnumMap<EquipmentSlot,Tag>copy=new EnumMap<>(EquipmentSlot.class);for(var entry:items.entrySet()){if(!SLOTS.contains(entry.getKey())||entry.getValue()==null)throw new IllegalArgumentException("invalid equipment slot");copy.put(entry.getKey(),entry.getValue().copy());}items=Collections.unmodifiableMap(copy);}}
    void putRawSnapshot(Snapshot snapshot){snapshots.put(snapshot.citizenId(),snapshot);}
    CompoundTag saveTag(){if(readOnly&&protectedRoot!=null)return protectedRoot.copy();CompoundTag root=new CompoundTag();root.putInt("SchemaVersion",SCHEMA_VERSION);root.putString("MigrationResult",migrationResult);root.putInt("QuarantinedSnapshots",quarantinedSnapshots);root.putInt("QuarantinedStacks",quarantinedStacks);ListTag records=new ListTag();for(Snapshot snapshot:snapshots.values()){CompoundTag record=new CompoundTag();record.putString("CitizenId",snapshot.citizenId().toString());record.putLong("Revision",snapshot.revision());record.putLong("CitizenRevision",snapshot.citizenRevision());ListTag items=new ListTag();for(var entry:snapshot.items().entrySet()){CompoundTag item=new CompoundTag();item.putString("Slot",entry.getKey().name());item.put("Stack",entry.getValue().copy());items.add(item);}record.put("Items",items);records.add(record);}root.put("Snapshots",records);return root;}
    static CitizenEquipmentSavedData load(CompoundTag root){CitizenEquipmentSavedData data=new CitizenEquipmentSavedData();int schema=root.getIntOr("SchemaVersion",0);if(schema>SCHEMA_VERSION){data.readOnly=true;data.protectedRoot=root.copy();data.migrationResult="future_schema_read_only";return data;}data.migrationResult=schema<1?"v"+schema+"_to_v1":root.getStringOr("MigrationResult","v1");data.quarantinedSnapshots=Math.max(0,root.getIntOr("QuarantinedSnapshots",0));data.quarantinedStacks=Math.max(0,root.getIntOr("QuarantinedStacks",0));for(Tag raw:root.getListOrEmpty("Snapshots")){try{if(!(raw instanceof CompoundTag record))throw new IllegalArgumentException("snapshot not compound");UUID citizen=UUID.fromString(record.getStringOr("CitizenId",""));EnumMap<EquipmentSlot,Tag>items=new EnumMap<>(EquipmentSlot.class);for(Tag itemRaw:record.getListOrEmpty("Items")){try{if(!(itemRaw instanceof CompoundTag item))throw new IllegalArgumentException("item not compound");EquipmentSlot slot=EquipmentSlot.valueOf(item.getStringOr("Slot",""));Tag stack=item.get("Stack");if(stack==null||!SLOTS.contains(slot)||items.putIfAbsent(slot,stack.copy())!=null)throw new IllegalArgumentException("invalid equipment stack");}catch(RuntimeException ex){data.quarantinedStacks++;LOGGER.warn("Skipping malformed Civitas equipment stack",ex);}}Snapshot snapshot=new Snapshot(citizen,items,record.getLongOr("Revision",0),record.getLongOr("CitizenRevision",0));if(data.snapshots.putIfAbsent(citizen,snapshot)!=null)throw new IllegalArgumentException("duplicate equipment snapshot");}catch(RuntimeException ex){data.quarantinedSnapshots++;LOGGER.warn("Skipping malformed Civitas equipment snapshot",ex);}}return data;}
}
