package com.seaquake6324.civitas.infrastructure.persistence;

import com.mojang.logging.LogUtils;
import com.mojang.serialization.Codec;
import com.seaquake6324.civitas.application.port.PopulationRepository;
import com.seaquake6324.civitas.application.port.ReproductionRepository;
import com.seaquake6324.civitas.application.port.MigrationRepository;
import com.seaquake6324.civitas.domain.population.*;
import java.util.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.Identifier;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.level.saveddata.*;
import org.slf4j.Logger;

/** Independent population authority. Entity NBT must never duplicate these records. */
public final class PopulationSavedData extends SavedData implements ReproductionRepository,MigrationRepository {
    public static final int SCHEMA_VERSION=13;
    private static final Logger LOGGER=LogUtils.getLogger();
    private static final Codec<PopulationSavedData> CODEC=CompoundTag.CODEC.xmap(PopulationSavedData::load,PopulationSavedData::saveTag);
    private static final SavedDataType<PopulationSavedData> TYPE=new SavedDataType<>(Identifier.fromNamespaceAndPath("civitas","population"),PopulationSavedData::new,CODEC);
    private final Map<UUID,PlayerCivitasProfile> profiles=new HashMap<>();
    private final NavigableMap<UUID,CitizenRecord> citizens=new TreeMap<>();
    private final NavigableMap<UUID,Household> households=new TreeMap<>();
    private final NavigableMap<UUID,MarriageProposal>proposals=new TreeMap<>();
    private final NavigableMap<UUID,PregnancyRecord>pregnancies=new TreeMap<>();
    private final NavigableMap<UUID,ReproductionConsent>reproductionConsents=new TreeMap<>();
    private final Map<FamilyMemberRef,UUID>activeReproductionConsentIndex=new HashMap<>();
    private final Map<UUID,ParentageRecord>parentageByChild=new HashMap<>();
    private final NavigableMap<UUID,OrphanRecord>orphans=new TreeMap<>();
    private final NavigableMap<UUID,AdoptionConsent>adoptionConsents=new TreeMap<>();
    private final Map<UUID,UUID>adoptionConsentByChild=new HashMap<>();
    private final Map<UUID,LinkedHashSet<UUID>>adoptionConsentsByPlayer=new HashMap<>();
    private final NavigableMap<UUID,MigrationGroupRecord>migrations=new TreeMap<>();
    private final Map<UUID,MigrationOriginRecord>migrationOrigins=new HashMap<>();
    private final Map<UUID,CitizenLocationRecord>locations=new HashMap<>();
    private final Map<UUID,LinkedHashSet<UUID>>citizenCityIndex=new HashMap<>(),householdCityIndex=new HashMap<>(),orphanCityIndex=new HashMap<>();
    private final Map<String,LinkedHashSet<UUID>>citizenNameIndex=new HashMap<>();
    private final Map<FamilyMemberRef,UUID>partnerHouseholdIndex=new HashMap<>(),guardianHouseholdIndex=new HashMap<>();
    private final Map<FamilyMemberRef,UUID>activeProposalIndex=new HashMap<>();
    private final Map<FamilyMemberRef,Long>proposalCooldowns=new HashMap<>();
    private final Map<FamilyMemberRef,LinkedHashSet<UUID>>proposalParticipantIndex=new HashMap<>();
    private final Map<FamilyMemberRef,UUID>activePregnancyIndex=new HashMap<>();
    private final Map<FamilyMemberRef,LinkedHashSet<UUID>>childrenByParent=new HashMap<>();
    private final Map<FamilyMemberRef,Long>reproductionCooldowns=new HashMap<>();
    private final Map<UUID,UUID>migrationByMember=new HashMap<>();
    private final Map<UUID,LinkedHashSet<UUID>>migrationCityIndex=new HashMap<>();
    private boolean readOnly;private CompoundTag protectedRoot;private int quarantinedProfiles,quarantinedCitizens,quarantinedHouseholds,quarantinedProposals,quarantinedCooldowns,quarantinedPregnancies,quarantinedReproductionConsents,quarantinedParentage,quarantinedOrphans,quarantinedAdoptionConsents,quarantinedReproductionCooldowns,quarantinedMigrations,quarantinedMigrationOrigins,quarantinedLocations;
    private String migrationResult="created_v12";private UUID simulationCursor,proposalMaintenanceCursor,marriageMatchingCursor,reproductionCursor,pregnancyCursor,migrationCursor,adoptionConsentCursor,outMigrationHouseholdCursor,outMigrationCitizenCursor;

    public static PopulationSavedData get(MinecraftServer server){return server.overworld().getDataStorage().computeIfAbsent(TYPE);}
    @Override public Optional<PlayerCivitasProfile> profile(UUID id){return Optional.ofNullable(profiles.get(id));}
    @Override public void putProfile(PlayerCivitasProfile profile){if(!readOnly){profiles.put(profile.playerId(),profile);setDirty();}}
    @Override public Optional<CitizenRecord> citizen(UUID id){return Optional.ofNullable(citizens.get(id));}
    @Override public Collection<CitizenRecord> citizens(){return List.copyOf(citizens.values());}
    public List<CitizenRecord> citizens(UUID cityId,int limit){return citizenPage(cityId,limit).records();}
    public CitizenPage citizenPage(UUID cityId,int limit){int cap=Math.max(0,limit),examined=0;ArrayList<CitizenRecord>out=new ArrayList<>();boolean truncated=false;for(UUID id:citizenCityIndex.getOrDefault(cityId,new LinkedHashSet<>())){if(examined++>=cap){truncated=true;break;}CitizenRecord record=citizens.get(id);if(record!=null)out.add(record);}return new CitizenPage(List.copyOf(out),truncated,examined);}
    public record CitizenPage(List<CitizenRecord>records,boolean truncated,int examined){public CitizenPage{records=List.copyOf(records);}}
    public CitizenBatch citizenBatch(UUID after,int limit){int cap=Math.max(0,limit);if(cap==0||citizens.isEmpty())return new CitizenBatch(List.of(),after,false,0);ArrayList<CitizenRecord>out=new ArrayList<>(Math.min(cap,citizens.size()));UUID key=after==null?citizens.firstKey():citizens.higherKey(after);boolean wrapped=false;if(key==null){key=citizens.firstKey();wrapped=true;}int examined=0,maximum=Math.min(cap,citizens.size());while(out.size()<maximum){CitizenRecord record=citizens.get(key);if(record!=null)out.add(record);examined++;UUID next=citizens.higherKey(key);if(next==null){wrapped=true;if(out.size()<maximum)next=citizens.firstKey();}key=next;}return new CitizenBatch(List.copyOf(out),out.getLast().id(),wrapped,examined);}
    public record CitizenBatch(List<CitizenRecord>records,UUID nextCursor,boolean wrapped,int examined){public CitizenBatch{records=List.copyOf(records);}}
    public List<CitizenRecord> citizensByName(String displayName,int limit){ArrayList<CitizenRecord>out=new ArrayList<>();for(UUID id:citizenNameIndex.getOrDefault(normalizeName(displayName),new LinkedHashSet<>())){if(out.size()>=Math.max(0,limit))break;CitizenRecord record=citizens.get(id);if(record!=null)out.add(record);}return List.copyOf(out);}
    @Override public void putCitizen(CitizenRecord citizen){if(!readOnly){CitizenRecord previous=citizens.get(citizen.id());if(previous!=null&&citizen.revision()<=previous.revision())throw new IllegalArgumentException("citizen revision must increase");citizens.put(citizen.id(),citizen);if(previous!=null)unindex(previous);index(citizen);setDirty();}}
    @Override public Optional<CitizenLocationRecord>location(UUID id){return Optional.ofNullable(locations.get(id));}
    @Override public boolean updateLocation(CitizenLocationRecord location,long expectedCitizenRevision,long expectedLocationRevision){if(readOnly)return false;CitizenRecord citizen=citizens.get(location.citizenId());CitizenLocationRecord previous=locations.get(location.citizenId());long revision=previous==null?0:previous.revision();if(citizen==null||!citizen.alive()||citizen.revision()!=expectedCitizenRevision||citizen.cityId()==null||!citizen.cityId().equals(location.cityId())||revision!=expectedLocationRevision||location.revision()!=expectedLocationRevision+1)return false;locations.put(location.citizenId(),location);setDirty();return true;}
    @Override public Optional<Household> household(UUID id){return Optional.ofNullable(households.get(id));}
    @Override public Collection<Household> households(){return List.copyOf(households.values());}
    public List<Household> households(UUID cityId,int limit){return householdPage(cityId,limit).records();}
    public HouseholdPage householdPage(UUID cityId,int limit){int cap=Math.max(0,limit),examined=0;ArrayList<Household>out=new ArrayList<>();boolean truncated=false;for(UUID id:householdCityIndex.getOrDefault(cityId,new LinkedHashSet<>())){if(examined++>=cap){truncated=true;break;}Household record=households.get(id);if(record!=null)out.add(record);}return new HouseholdPage(List.copyOf(out),truncated,examined);}
    public record HouseholdPage(List<Household>records,boolean truncated,int examined){public HouseholdPage{records=List.copyOf(records);}}
    public HouseholdBatch householdBatch(UUID after,int limit){int cap=Math.max(0,limit);if(cap==0||households.isEmpty())return new HouseholdBatch(List.of(),after,false,0);ArrayList<Household>out=new ArrayList<>();UUID key=after==null?households.firstKey():households.higherKey(after);boolean wrapped=false;if(key==null){key=households.firstKey();wrapped=true;}int maximum=Math.min(cap,households.size()),examined=0;while(out.size()<maximum){out.add(households.get(key));examined++;UUID next=households.higherKey(key);if(next==null){wrapped=true;if(out.size()<maximum)next=households.firstKey();}key=next;}return new HouseholdBatch(out,out.getLast().id(),wrapped,examined);}
    public record HouseholdBatch(List<Household>records,UUID nextCursor,boolean wrapped,int examined){public HouseholdBatch{records=List.copyOf(records);}}
    @Override public void putHousehold(Household household){if(!readOnly){Household previous=households.get(household.id());if(previous!=null&&(!previous.cityId().equals(household.cityId())||!previous.partners().equals(household.partners())||!previous.historicalPartners().equals(household.historicalPartners())||household.revision()<=previous.revision()))throw new IllegalArgumentException("invalid household replacement");for(FamilyMemberRef partner:household.partners()){UUID existing=partnerHouseholdIndex.get(partner);if(existing!=null&&!existing.equals(household.id()))throw new IllegalArgumentException("partner already belongs to another household");}for(FamilyMemberRef guardian:household.guardians()){UUID existing=guardianHouseholdIndex.get(guardian);if(existing!=null&&!existing.equals(household.id()))throw new IllegalArgumentException("guardian already belongs to another household");validateFamilyReference(guardian,household.cityId(),household.id());}households.put(household.id(),household);if(previous!=null)unindex(previous);index(household);setDirty();}}
    @Override public boolean createHousehold(Household household,Map<UUID,Long> expected){if(readOnly||households.containsKey(household.id()))return false;Set<FamilyMemberRef>adults=new HashSet<>(household.partners());adults.addAll(household.guardians());for(FamilyMemberRef adult:adults){if(household.partners().contains(adult)&&partnerHouseholdIndex.containsKey(adult)||household.guardians().contains(adult)&&guardianHouseholdIndex.containsKey(adult))return false;if(adult.kind()==FamilyMemberRef.Kind.CITIZEN){CitizenRecord citizen=citizens.get(adult.id());Long revision=expected.get(adult.id());if(citizen==null||revision==null||citizen.revision()!=revision||!citizen.alive()||citizen.householdId()!=null||!household.cityId().equals(citizen.cityId()))return false;}}households.put(household.id(),household);index(household);for(FamilyMemberRef adult:adults)if(adult.kind()==FamilyMemberRef.Kind.CITIZEN){CitizenRecord citizen=citizens.get(adult.id());putCitizen(citizen.withHousehold(household.id()));}setDirty();return true;}
    @Override public boolean recordPartnerDeath(UUID householdId,FamilyMemberRef deceased,long expectedRevision){if(readOnly)return false;Household household=households.get(householdId);if(household==null||household.revision()!=expectedRevision||!household.partners().contains(deceased))return false;Household historical=household.recordPartnerDeath(deceased);unindex(household);households.put(householdId,historical);index(historical);for(FamilyMemberRef member:household.partners())if(!member.equals(deceased)&&member.kind()==FamilyMemberRef.Kind.CITIZEN&&!historical.guardians().contains(member)){CitizenRecord survivor=citizens.get(member.id());if(survivor!=null&&survivor.alive()&&householdId.equals(survivor.householdId()))putCitizen(survivor.withHousehold(null));}setDirty();return true;}
    @Override public Optional<Household>householdForPartner(FamilyMemberRef partner){UUID id=partnerHouseholdIndex.get(partner);return id==null?Optional.empty():Optional.ofNullable(households.get(id));}
    @Override public Optional<Household>householdForGuardian(FamilyMemberRef guardian){UUID id=guardianHouseholdIndex.get(guardian);return id==null?Optional.empty():Optional.ofNullable(households.get(id));}
    @Override public Optional<MarriageProposal>proposal(UUID proposalId){return Optional.ofNullable(proposals.get(proposalId));}
    @Override public Optional<MarriageProposal>activeProposalFor(FamilyMemberRef participant){UUID id=activeProposalIndex.get(participant);return id==null?Optional.empty():Optional.ofNullable(proposals.get(id)).filter(p->p.status()==MarriageProposal.Status.PENDING);}
    @Override public long nextProposalAt(FamilyMemberRef participant){return proposalCooldowns.getOrDefault(participant,0L);}
    @Override public void setNextProposalAt(FamilyMemberRef participant,long tick){if(!readOnly){if(tick<=0)proposalCooldowns.remove(participant);else proposalCooldowns.put(participant,tick);setDirty();}}
    @Override public void putProposal(MarriageProposal proposal){if(!readOnly){MarriageProposal previous=proposals.get(proposal.id());if(previous!=null&&!validProposalTransition(previous,proposal))throw new IllegalArgumentException("invalid proposal replacement");if(proposal.status()==MarriageProposal.Status.PENDING){UUID a=activeProposalIndex.get(proposal.proposer()),b=activeProposalIndex.get(proposal.target());if((a!=null&&!a.equals(proposal.id()))||(b!=null&&!b.equals(proposal.id())))throw new IllegalArgumentException("participant already has active proposal");}if(previous!=null)unindex(previous);proposals.put(proposal.id(),proposal);index(proposal);setDirty();}}
    public ProposalPage proposalPage(FamilyMemberRef participant,int limit){ArrayList<MarriageProposal>out=new ArrayList<>();int cap=Math.max(0,limit),examined=0;for(UUID id:proposalParticipantIndex.getOrDefault(participant,new LinkedHashSet<>())){examined++;if(out.size()>=cap)return new ProposalPage(out,true,examined);MarriageProposal proposal=proposals.get(id);if(proposal!=null)out.add(proposal);}return new ProposalPage(out,false,examined);}
    public record ProposalPage(List<MarriageProposal>records,boolean truncated,int examined){public ProposalPage{records=List.copyOf(records);}}
    public ProposalBatch proposalBatch(UUID after,int limit){int cap=Math.max(0,limit);if(cap==0||proposals.isEmpty())return new ProposalBatch(List.of(),after,false,0);ArrayList<MarriageProposal>out=new ArrayList<>();UUID key=after==null?proposals.firstKey():proposals.higherKey(after);boolean wrapped=false;if(key==null){key=proposals.firstKey();wrapped=true;}int maximum=Math.min(cap,proposals.size()),examined=0;while(out.size()<maximum){out.add(proposals.get(key));examined++;UUID next=proposals.higherKey(key);if(next==null){wrapped=true;if(out.size()<maximum)next=proposals.firstKey();}key=next;}return new ProposalBatch(out,out.getLast().id(),wrapped,examined);}
    public record ProposalBatch(List<MarriageProposal>records,UUID nextCursor,boolean wrapped,int examined){public ProposalBatch{records=List.copyOf(records);}}
    public ProposalDiagnostics proposalDiagnostics(int limit){int cap=Math.max(0,limit),examined=0;EnumMap<MarriageProposal.Status,Integer>counts=new EnumMap<>(MarriageProposal.Status.class);for(MarriageProposal.Status status:MarriageProposal.Status.values())counts.put(status,0);for(MarriageProposal proposal:proposals.values()){if(examined>=cap)break;counts.merge(proposal.status(),1,Integer::sum);examined++;}return new ProposalDiagnostics(counts,examined,proposals.size()>cap);}
    public record ProposalDiagnostics(Map<MarriageProposal.Status,Integer>statusCounts,int examined,boolean truncated){public ProposalDiagnostics{statusCounts=Map.copyOf(statusCounts);}}
    public void removeProposal(UUID id){if(readOnly)return;MarriageProposal removed=proposals.remove(id);if(removed!=null){unindex(removed);setDirty();}}
    public Collection<PlayerCivitasProfile> profiles(){return List.copyOf(profiles.values());}
    public Optional<PregnancyRecord>pregnancy(UUID id){return Optional.ofNullable(pregnancies.get(id));}
    public Optional<PregnancyRecord>activePregnancy(FamilyMemberRef carrier){UUID id=activePregnancyIndex.get(carrier);return id==null?Optional.empty():Optional.ofNullable(pregnancies.get(id));}
    public Collection<PregnancyRecord>pregnancies(){return List.copyOf(pregnancies.values());}
    public Optional<ReproductionConsent> reproductionConsent(UUID id){return Optional.ofNullable(reproductionConsents.get(id));}
    public Collection<ReproductionConsent> reproductionConsents(){return List.copyOf(reproductionConsents.values());}
    public Optional<ReproductionConsent> activeReproductionConsent(FamilyMemberRef member){UUID id=activeReproductionConsentIndex.get(member);return id==null?Optional.empty():Optional.ofNullable(reproductionConsents.get(id));}
    public boolean createReproductionConsent(ReproductionConsent consent,int cap){if(readOnly||reproductionConsents.size()>=Math.max(0,cap)||reproductionConsents.containsKey(consent.id())||activeReproductionConsentIndex.containsKey(consent.proposer())||activeReproductionConsentIndex.containsKey(consent.target()))return false;reproductionConsents.put(consent.id(),consent);activeReproductionConsentIndex.put(consent.proposer(),consent.id());activeReproductionConsentIndex.put(consent.target(),consent.id());setDirty();return true;}
    public boolean removeReproductionConsent(UUID id,long expectedRevision){if(readOnly)return false;ReproductionConsent consent=reproductionConsents.get(id);if(consent==null||consent.revision()!=expectedRevision)return false;reproductionConsents.remove(id);activeReproductionConsentIndex.remove(consent.proposer(),id);activeReproductionConsentIndex.remove(consent.target(),id);setDirty();return true;}
    public int reproductionConsentCount(){return reproductionConsents.size();}
    public PregnancyBatch pregnancyBatch(UUID after,int limit){int cap=Math.max(0,limit);if(cap==0||pregnancies.isEmpty())return new PregnancyBatch(List.of(),after,false,0);ArrayList<PregnancyRecord>out=new ArrayList<>();UUID key=after==null?pregnancies.firstKey():pregnancies.higherKey(after);boolean wrapped=false;if(key==null){key=pregnancies.firstKey();wrapped=true;}int maximum=Math.min(cap,pregnancies.size()),examined=0;while(out.size()<maximum){out.add(pregnancies.get(key));examined++;UUID next=pregnancies.higherKey(key);if(next==null){wrapped=true;if(out.size()<maximum)next=pregnancies.firstKey();}key=next;}return new PregnancyBatch(out,out.getLast().id(),wrapped,examined);}
    public record PregnancyBatch(List<PregnancyRecord>records,UUID nextCursor,boolean wrapped,int examined){public PregnancyBatch{records=List.copyOf(records);}}
    public void putPregnancy(PregnancyRecord record){if(readOnly)return;for(FamilyMemberRef parent:record.parents())validateFamilyReference(parent,record.cityId(),null);if(gender(record.gestationalParent())!=Gender.FEMALE||genders(record.parents()).size()!=2)throw new IllegalArgumentException("invalid pregnancy genders");PregnancyRecord previous=pregnancies.get(record.id());if(previous!=null&&(!samePregnancyIdentity(previous,record)||record.revision()!=previous.revision()+1))throw new IllegalArgumentException("invalid pregnancy replacement");UUID active=activePregnancyIndex.get(record.gestationalParent());if(active!=null&&!active.equals(record.id()))throw new IllegalArgumentException("gestational parent already pregnant");pregnancies.put(record.id(),record);activePregnancyIndex.put(record.gestationalParent(),record.id());setDirty();}
    @Override public boolean createPregnancy(PregnancyRecord record,Map<FamilyMemberRef,Long>expectedRevisions,int pregnancyCapacity,long now){if(readOnly||pregnancies.size()>=Math.max(0,pregnancyCapacity)||pregnancies.containsKey(record.id())||activePregnancyIndex.containsKey(record.gestationalParent()))return false;try{for(FamilyMemberRef parent:record.parents()){validateFamilyReference(parent,record.cityId(),null);Long expected=expectedRevisions.get(parent);if(expected==null||memberRevision(parent)!=expected||nextReproductionAt(parent)>now)return false;if(parent.kind()==FamilyMemberRef.Kind.CITIZEN&&!citizens.get(parent.id()).alive())return false;}if(gender(record.gestationalParent())!=Gender.FEMALE||genders(record.parents()).size()!=2)return false;}catch(RuntimeException exception){return false;}pregnancies.put(record.id(),record);activePregnancyIndex.put(record.gestationalParent(),record.id());setDirty();return true;}
    public void removePregnancy(UUID id,long expectedRevision){if(readOnly)return;PregnancyRecord record=pregnancies.get(id);if(record==null||record.revision()!=expectedRevision)throw new IllegalArgumentException("stale pregnancy removal");pregnancies.remove(id);activePregnancyIndex.remove(record.gestationalParent(),id);setDirty();}
    @Override public Optional<ParentageRecord>parentage(UUID childId){return Optional.ofNullable(parentageByChild.get(childId));}
    @Override public Collection<ParentageRecord>parentageForParent(FamilyMemberRef parent,int limit){ArrayList<ParentageRecord>out=new ArrayList<>();for(UUID childId:childrenByParent.getOrDefault(parent,new LinkedHashSet<>())){if(out.size()>=Math.max(0,limit))break;ParentageRecord record=parentageByChild.get(childId);if(record!=null)out.add(record);}return List.copyOf(out);}
    public void putParentage(ParentageRecord record){if(readOnly)return;CitizenRecord child=citizens.get(record.childId());if(child==null||!record.cityId().equals(child.cityId()))throw new IllegalArgumentException("missing parentage child");for(FamilyMemberRef parent:record.parents())validateFamilyReference(parent,record.cityId(),null);ParentageRecord previous=parentageByChild.get(record.childId());if(previous!=null&&(!sameParentageIdentity(previous,record)||record.revision()!=previous.revision()+1))throw new IllegalArgumentException("invalid parentage replacement");if(previous!=null)unindex(previous);parentageByChild.put(record.childId(),record);index(record);setDirty();}
    @Override public Optional<OrphanRecord>orphan(UUID childId){return Optional.ofNullable(orphans.get(childId));}
    public Collection<OrphanRecord>orphans(){return List.copyOf(orphans.values());}
    public OrphanPage orphanPage(UUID cityId,int limit){int cap=Math.max(0,limit),examined=0;ArrayList<OrphanRecord>out=new ArrayList<>();boolean truncated=false;for(UUID id:orphanCityIndex.getOrDefault(cityId,new LinkedHashSet<>())){if(examined++>=cap){truncated=true;break;}OrphanRecord record=orphans.get(id);if(record!=null)out.add(record);}return new OrphanPage(out,truncated,examined);}
    public record OrphanPage(List<OrphanRecord>records,boolean truncated,int examined){public OrphanPage{records=List.copyOf(records);}}
    public OrphanBatch orphanBatch(UUID after,int limit){int cap=Math.max(0,limit);if(cap==0||orphans.isEmpty())return new OrphanBatch(List.of(),after,false,0);ArrayList<OrphanRecord>out=new ArrayList<>();UUID key=after==null?orphans.firstKey():orphans.higherKey(after);boolean wrapped=false;if(key==null){key=orphans.firstKey();wrapped=true;}int maximum=Math.min(cap,orphans.size()),examined=0;while(out.size()<maximum){out.add(orphans.get(key));examined++;UUID next=orphans.higherKey(key);if(next==null){wrapped=true;if(out.size()<maximum)next=orphans.firstKey();}key=next;}return new OrphanBatch(out,out.getLast().childId(),wrapped,examined);}
    public record OrphanBatch(List<OrphanRecord>records,UUID nextCursor,boolean wrapped,int examined){public OrphanBatch{records=List.copyOf(records);}}
    @Override public void putOrphan(OrphanRecord record){if(readOnly)return;CitizenRecord child=citizens.get(record.childId());if(child==null||!child.alive()||!record.cityId().equals(child.cityId())||!parentageByChild.containsKey(record.childId()))throw new IllegalArgumentException("invalid orphan child");OrphanRecord previous=orphans.get(record.childId());if(previous!=null&&(!sameOrphanIdentity(previous,record)||record.revision()!=previous.revision()+1))throw new IllegalArgumentException("invalid orphan replacement");orphans.put(record.childId(),record);if(previous!=null)removeIndex(orphanCityIndex,previous.cityId(),previous.childId());orphanCityIndex.computeIfAbsent(record.cityId(),ignored->new LinkedHashSet<>()).add(record.childId());setDirty();}
    public Optional<AdoptionConsent>adoptionConsent(UUID id){return Optional.ofNullable(adoptionConsents.get(id));}
    public Optional<AdoptionConsent>adoptionConsentForChild(UUID childId){UUID id=adoptionConsentByChild.get(childId);return id==null?Optional.empty():Optional.ofNullable(adoptionConsents.get(id));}
    public List<AdoptionConsent>adoptionConsentsForPlayer(UUID player,int limit){ArrayList<AdoptionConsent>out=new ArrayList<>();for(UUID id:adoptionConsentsByPlayer.getOrDefault(player,new LinkedHashSet<>())){if(out.size()>=Math.max(0,limit))break;AdoptionConsent consent=adoptionConsents.get(id);if(consent!=null)out.add(consent);}return List.copyOf(out);}
    public List<AdoptionConsent>adoptionConsentsForCity(UUID city,int limit){ArrayList<AdoptionConsent>out=new ArrayList<>();for(AdoptionConsent consent:adoptionConsents.values()){if(out.size()>=Math.max(0,limit))break;if(consent.cityId().equals(city))out.add(consent);}return List.copyOf(out);}
    public boolean createAdoptionConsent(AdoptionConsent consent,int cap){if(readOnly||adoptionConsents.size()>=Math.max(0,cap)||adoptionConsents.containsKey(consent.id())||adoptionConsentByChild.containsKey(consent.childId())||!orphans.containsKey(consent.childId()))return false;for(UUID player:consent.requiredPlayers())if(!profiles.containsKey(player))return false;adoptionConsents.put(consent.id(),consent);index(consent);setDirty();return true;}
    public boolean updateAdoptionConsent(AdoptionConsent consent,long expectedRevision){AdoptionConsent current=adoptionConsents.get(consent.id());if(readOnly||current==null||current.revision()!=expectedRevision||consent.revision()!=expectedRevision+1||!sameAdoptionConsentIdentity(current,consent)||!consent.confirmedPlayers().containsAll(current.confirmedPlayers()))return false;adoptionConsents.put(consent.id(),consent);setDirty();return true;}
    public boolean removeAdoptionConsent(UUID id,long expectedRevision){AdoptionConsent current=adoptionConsents.get(id);if(readOnly||current==null||current.revision()!=expectedRevision)return false;adoptionConsents.remove(id);unindex(current);setDirty();return true;}
    public AdoptionConsentBatch adoptionConsentBatch(UUID after,int limit){int cap=Math.max(0,limit);if(cap==0||adoptionConsents.isEmpty())return new AdoptionConsentBatch(List.of(),after,false);ArrayList<AdoptionConsent>out=new ArrayList<>();UUID key=after==null?adoptionConsents.firstKey():adoptionConsents.higherKey(after);boolean wrapped=false;if(key==null){key=adoptionConsents.firstKey();wrapped=true;}int maximum=Math.min(cap,adoptionConsents.size());while(out.size()<maximum){out.add(adoptionConsents.get(key));UUID next=adoptionConsents.higherKey(key);if(next==null){wrapped=true;if(out.size()<maximum)next=adoptionConsents.firstKey();}key=next;}return new AdoptionConsentBatch(out,out.getLast().id(),wrapped);}
    public record AdoptionConsentBatch(List<AdoptionConsent>records,UUID nextCursor,boolean wrapped){public AdoptionConsentBatch{records=List.copyOf(records);}}
    @Override public boolean commitAdoption(OrphanRecord expectedOrphan,long expectedChildRevision,Household adoptive,long expectedAdoptiveRevision,Household origin,Household originAfter,CitizenRecord childAfter,Map<UUID,Long>guardianRevisions,Set<UUID>confirmedPlayers,int childCapacity){
        if(readOnly||expectedOrphan==null||adoptive==null||childAfter==null||adoptive.children().size()>Math.max(1,childCapacity)||!adoptive.children().contains(childAfter.id())||!adoptive.id().equals(childAfter.householdId())||!adoptive.cityId().equals(childAfter.cityId())||adoptive.guardians().isEmpty())return false;
        OrphanRecord currentOrphan=orphans.get(expectedOrphan.childId());CitizenRecord child=citizens.get(expectedOrphan.childId());if(!expectedOrphan.equals(currentOrphan)||child==null||!child.alive()||child.revision()!=expectedChildRevision||!child.cityId().equals(adoptive.cityId())||childAfter.revision()<=child.revision())return false;
        Household currentAdoptive=households.get(adoptive.id());if(currentAdoptive==null){if(expectedAdoptiveRevision!=0||adoptive.revision()!=1)return false;}else if(currentAdoptive.revision()!=expectedAdoptiveRevision||adoptive.revision()!=expectedAdoptiveRevision+1||!currentAdoptive.cityId().equals(adoptive.cityId()))return false;
        Household currentOrigin=origin==null?null:households.get(origin.id());if(origin!=null&&(currentOrigin==null||!currentOrigin.equals(origin)||originAfter==null||originAfter.revision()!=origin.revision()+1||originAfter.children().contains(child.id())))return false;
        Map<UUID,CitizenRecord>guardianUpdates=new HashMap<>();try{for(FamilyMemberRef guardian:adoptive.guardians()){UUID indexed=guardianHouseholdIndex.get(guardian);if(indexed!=null&&!indexed.equals(adoptive.id()))return false;if(guardian.kind()==FamilyMemberRef.Kind.PLAYER){if(!profiles.containsKey(guardian.id())||!confirmedPlayers.contains(guardian.id()))return false;continue;}CitizenRecord adult=citizens.get(guardian.id());Long revision=guardianRevisions.get(guardian.id());if(adult==null||revision==null||adult.revision()!=revision||!adult.alive()||!adult.cityId().equals(adoptive.cityId()))return false;if(adult.householdId()==null)guardianUpdates.put(adult.id(),adult.withHousehold(adoptive.id()));else if(!adult.householdId().equals(adoptive.id()))return false;}}catch(RuntimeException exception){return false;}
        if(currentOrigin!=null){unindex(currentOrigin);households.put(originAfter.id(),originAfter);index(originAfter);}if(currentAdoptive!=null)unindex(currentAdoptive);households.put(adoptive.id(),adoptive);index(adoptive);for(CitizenRecord update:guardianUpdates.values()){CitizenRecord old=citizens.put(update.id(),update);unindex(old);index(update);}unindex(child);citizens.put(child.id(),childAfter);index(childAfter);OrphanRecord removed=orphans.remove(child.id());if(removed!=null)removeIndex(orphanCityIndex,removed.cityId(),removed.childId());setDirty();return true;
    }
    public void removeOrphan(UUID childId,long expectedRevision){if(readOnly)return;OrphanRecord record=orphans.get(childId);if(record==null||record.revision()!=expectedRevision)throw new IllegalArgumentException("stale orphan removal");orphans.remove(childId);removeIndex(orphanCityIndex,record.cityId(),record.childId());setDirty();}
    public long nextReproductionAt(FamilyMemberRef member){return reproductionCooldowns.getOrDefault(member,0L);}
    public void setNextReproductionAt(FamilyMemberRef member,long tick){if(readOnly)return;if(tick<=0)reproductionCooldowns.remove(member);else reproductionCooldowns.put(member,tick);setDirty();}
    @Override public boolean commitBirth(PregnancyRecord expectedPregnancy,CitizenRecord child,ParentageRecord parentage,Household household,Map<FamilyMemberRef,Long>expectedParentRevisions,long cooldownUntil,int householdChildCapacity){
        if(readOnly||expectedPregnancy==null||child==null||parentage==null||household==null)return false;
        PregnancyRecord currentPregnancy=pregnancies.get(expectedPregnancy.id());
        if(!expectedPregnancy.equals(currentPregnancy)||citizens.containsKey(child.id())||parentageByChild.containsKey(child.id())||orphans.containsKey(child.id())
                ||!child.id().equals(parentage.childId())||!child.cityId().equals(expectedPregnancy.cityId())||!child.cityId().equals(parentage.cityId())
                ||!parentage.parents().equals(expectedPregnancy.parents())||!household.cityId().equals(child.cityId())||!household.children().contains(child.id())
                ||!household.id().equals(child.householdId())||household.children().size()>Math.max(0,householdChildCapacity)||household.guardians().isEmpty())return false;
        for(FamilyMemberRef parent:expectedPregnancy.parents()){Long revision=expectedParentRevisions.get(parent);if(revision==null||memberRevision(parent)!=revision)return false;}
        if(expectedPregnancy.gestationalParent().kind()==FamilyMemberRef.Kind.CITIZEN&&!citizens.get(expectedPregnancy.gestationalParent().id()).alive())return false;
        Household previous=households.get(household.id());
        if(previous==null){if(household.revision()!=1)return false;}
        else if(!previous.cityId().equals(household.cityId())||!previous.partners().equals(household.partners())||!previous.historicalPartners().equals(household.historicalPartners())||household.revision()!=previous.revision()+1)return false;
        Map<UUID,CitizenRecord>adultUpdates=new HashMap<>();
        try{
            for(FamilyMemberRef guardian:household.guardians()){
                validateFamilyReference(guardian,household.cityId(),previous==null?null:household.id());
                UUID indexed=guardianHouseholdIndex.get(guardian);if(indexed!=null&&!indexed.equals(household.id()))return false;
                if(guardian.kind()==FamilyMemberRef.Kind.CITIZEN){CitizenRecord adult=citizens.get(guardian.id());if(adult.householdId()==null){Long expected=expectedParentRevisions.get(guardian);if(expected==null||adult.revision()!=expected)return false;adultUpdates.put(adult.id(),adult.withHousehold(household.id()));}else if(!household.id().equals(adult.householdId()))return false;}
            }
        }catch(RuntimeException exception){return false;}
        if(previous!=null)unindex(previous);households.put(household.id(),household);index(household);
        for(CitizenRecord update:adultUpdates.values()){CitizenRecord old=citizens.put(update.id(),update);if(old!=null)unindex(old);index(update);}
        citizens.put(child.id(),child);index(child);parentageByChild.put(child.id(),parentage);index(parentage);
        pregnancies.remove(currentPregnancy.id());activePregnancyIndex.remove(currentPregnancy.gestationalParent(),currentPregnancy.id());
        for(FamilyMemberRef parent:currentPregnancy.parents())reproductionCooldowns.put(parent,Math.max(0,cooldownUntil));
        setDirty();return true;
    }
    @Override public Optional<MigrationGroupRecord>migration(UUID id){return Optional.ofNullable(migrations.get(id));}
    @Override public Optional<MigrationGroupRecord>migrationForMember(UUID memberId){UUID id=migrationByMember.get(memberId);return id==null?Optional.empty():Optional.ofNullable(migrations.get(id));}
    @Override public List<MigrationGroupRecord>migrationsForCity(UUID cityId,int limit){ArrayList<MigrationGroupRecord>out=new ArrayList<>();for(UUID id:migrationCityIndex.getOrDefault(cityId,new LinkedHashSet<>())){if(out.size()>=Math.max(0,limit))break;MigrationGroupRecord group=migrations.get(id);if(group!=null)out.add(group);}return List.copyOf(out);}
    @Override public Collection<MigrationGroupRecord>migrations(){return List.copyOf(migrations.values());}
    public MigrationBatch migrationBatch(UUID after,int limit){int cap=Math.max(0,limit);if(cap==0||migrations.isEmpty())return new MigrationBatch(List.of(),after,false,0);ArrayList<MigrationGroupRecord>out=new ArrayList<>();UUID key=after==null?migrations.firstKey():migrations.higherKey(after);boolean wrapped=false;if(key==null){key=migrations.firstKey();wrapped=true;}int maximum=Math.min(cap,migrations.size()),examined=0;UUID last=after;while(examined++<maximum){MigrationGroupRecord record=migrations.get(key);last=key;if(record.state()!=MigrationGroupRecord.State.REGIONAL_POOL)out.add(record);UUID next=migrations.higherKey(key);if(next==null){wrapped=true;if(examined<maximum)next=migrations.firstKey();}key=next;}return new MigrationBatch(List.copyOf(out),last,wrapped,examined-1);}
    public record MigrationBatch(List<MigrationGroupRecord>records,UUID nextCursor,boolean wrapped,int examined){public MigrationBatch{records=List.copyOf(records);}}
    @Override public int activeMigrationCount(){return migrations.size();}
    @Override public boolean createMigration(MigrationGroupRecord group,Collection<CitizenRecord>members,int activeCap){
        if(readOnly||migrations.size()>=Math.max(0,activeCap)||migrations.containsKey(group.id())||members.size()!=group.members().size())return false;
        Map<UUID,CitizenRecord>created=new HashMap<>();for(CitizenRecord citizen:members){if(!group.members().contains(citizen.id())||citizen.cityId()!=null||citizen.householdId()!=null||citizens.containsKey(citizen.id())||migrationByMember.containsKey(citizen.id())||created.put(citizen.id(),citizen)!=null)return false;}
        if(!created.keySet().equals(group.members()))return false;migrations.put(group.id(),group);index(group);for(CitizenRecord citizen:created.values()){citizens.put(citizen.id(),citizen);index(citizen);}setDirty();return true;
    }
    @Override public boolean beginOutMigration(MigrationGroupRecord group,Household household,Map<UUID,Long>expectedCitizenRevisions,int activeCap){
        if(readOnly||group==null||group.state()!=MigrationGroupRecord.State.DEPARTING||migrations.size()>=Math.max(0,activeCap)||migrations.containsKey(group.id())||!expectedCitizenRevisions.keySet().equals(group.members()))return false;
        Household currentHousehold=household==null?null:households.get(household.id());if(household!=null&&!household.equals(currentHousehold))return false;Set<UUID>expectedMembers=new HashSet<>();if(currentHousehold!=null){for(FamilyMemberRef adult:currentHousehold.partners())if(adult.kind()==FamilyMemberRef.Kind.CITIZEN)expectedMembers.add(adult.id());for(FamilyMemberRef adult:currentHousehold.guardians())if(adult.kind()==FamilyMemberRef.Kind.CITIZEN)expectedMembers.add(adult.id());expectedMembers.addAll(currentHousehold.children());if(!expectedMembers.equals(group.members())||!currentHousehold.children().equals(group.children()))return false;}else if(group.members().size()!=1)return false;
        for(UUID id:group.members()){CitizenRecord citizen=citizens.get(id);Long revision=expectedCitizenRevisions.get(id);FamilyMemberRef ref=FamilyMemberRef.citizen(id);if(citizen==null||revision==null||citizen.revision()!=revision||!citizen.alive()||!group.targetCityId().equals(citizen.cityId())||migrationByMember.containsKey(id)||citizen.runtimeState()==CitizenRuntimeState.LOCKED||activeProposalIndex.containsKey(ref)||activeReproductionConsentIndex.containsKey(ref)||activePregnancyIndex.containsKey(ref)||orphans.containsKey(id))return false;for(PregnancyRecord pregnancy:pregnancies.values())if(pregnancy.parents().contains(ref))return false;for(AdoptionConsent consent:adoptionConsents.values())if(consent.guardians().contains(ref)||consent.childId().equals(id))return false;}
        if(currentHousehold!=null){unindex(currentHousehold);households.remove(currentHousehold.id());}migrations.put(group.id(),group);index(group);for(UUID id:group.members()){CitizenRecord old=citizens.get(id),departing=old.leaveCity();unindex(old);citizens.put(id,departing);index(departing);locations.remove(id);}setDirty();return true;
    }
    @Override public boolean updateMigration(MigrationGroupRecord group,long expectedRevision){MigrationGroupRecord current=migrations.get(group.id());boolean reactivation=current!=null&&current.state()==MigrationGroupRecord.State.REGIONAL_POOL&&group.state()==MigrationGroupRecord.State.APPROACHING&&sameMigrationFamily(current,group);if(readOnly||current==null||current.revision()!=expectedRevision||group.revision()!=expectedRevision+1||!reactivation&&!sameMigrationIdentity(current,group))return false;unindex(current);migrations.put(group.id(),group);index(group);setDirty();return true;}
    @Override public boolean settleMigration(MigrationGroupRecord group,long expectedRevision,UUID residenceId,long settledAt){
        MigrationGroupRecord current=migrations.get(group.id());if(readOnly||current==null||current.revision()!=expectedRevision||current.state()!=MigrationGroupRecord.State.APPLIED||settledAt<0)return false;
        Map<UUID,CitizenRecord>source=new HashMap<>();for(UUID id:current.members()){CitizenRecord citizen=citizens.get(id);if(citizen==null||citizen.cityId()!=null||citizen.householdId()!=null||!citizen.alive())return false;source.put(id,citizen);}
        UUID householdId=current.partners().isEmpty()&&current.children().isEmpty()?null:current.id();if(householdId!=null&&households.containsKey(householdId))return false;
        Set<FamilyMemberRef>partners=current.partners().stream().map(FamilyMemberRef::citizen).collect(java.util.stream.Collectors.toSet());Set<FamilyMemberRef>guardians=current.guardians().stream().map(FamilyMemberRef::citizen).collect(java.util.stream.Collectors.toSet());
        Household household=householdId==null?null:new Household(householdId,current.targetCityId(),partners,Set.of(),guardians,current.children(),residenceId,50,residenceId==null?0:100,1);
        if(household!=null){households.put(household.id(),household);index(household);}
        for(CitizenRecord citizen:source.values()){CitizenRecord settled=citizen.settle(current.targetCityId(),householdId,residenceId);citizens.put(citizen.id(),settled);unindex(citizen);index(settled);migrationOrigins.put(citizen.id(),new MigrationOriginRecord(citizen.id(),current.id(),current.targetCityId(),current.dimension(),current.originPos(),settledAt,1));locations.put(citizen.id(),new CitizenLocationRecord(citizen.id(),current.targetCityId(),current.dimension(),current.memberPositions().get(citizen.id()),settledAt,1));}
        for(UUID childId:current.children())if(!parentageByChild.containsKey(childId)){Set<FamilyMemberRef>parents=partners.isEmpty()?guardians:partners;ParentageRecord parentage=new ParentageRecord(childId,current.targetCityId(),parents,Math.max(0,settledAt-source.get(childId).ageTicks()),false,ParentageRecord.Source.MIGRATION_WITH_SOURCE,1);parentageByChild.put(childId,parentage);index(parentage);}
        unindex(current);migrations.remove(current.id());setDirty();return true;
    }
    @Override public boolean poolDepartedMigration(MigrationGroupRecord group,long expectedRevision){MigrationGroupRecord current=migrations.get(group.id());if(readOnly||current==null||current.revision()!=expectedRevision||current.state()!=MigrationGroupRecord.State.DEPARTING)return false;for(UUID id:current.members()){CitizenRecord citizen=citizens.get(id);if(citizen==null||citizen.cityId()!=null)return false;}MigrationGroupRecord pooled=current.pooled();unindex(current);migrations.put(current.id(),pooled);index(pooled);setDirty();return true;}
    public List<MigrationGroupRecord>regionalPool(String dimension,int limit){ArrayList<MigrationGroupRecord>out=new ArrayList<>();int examined=0,cap=Math.max(0,limit);for(MigrationGroupRecord group:migrations.values()){if(examined++>=cap)break;if(group.state()==MigrationGroupRecord.State.REGIONAL_POOL&&group.dimension().equals(dimension))out.add(group);}return List.copyOf(out);}
    public int regionalPoolCount(){int count=0;for(MigrationGroupRecord group:migrations.values())if(group.state()==MigrationGroupRecord.State.REGIONAL_POOL)count++;return count;}
    @Override public Optional<MigrationOriginRecord>migrationOrigin(UUID citizenId){return Optional.ofNullable(migrationOrigins.get(citizenId));}
    public int citizenCount(){return citizens.size();}public int householdCount(){return households.size();}public int proposalCount(){return proposals.size();}public int cooldownCount(){return proposalCooldowns.size();}public int profileCount(){return profiles.size();}public int pregnancyCount(){return pregnancies.size();}public int parentageCount(){return parentageByChild.size();}public int orphanCount(){return orphans.size();}public int adoptionConsentCount(){return adoptionConsents.size();}public int reproductionCooldownCount(){return reproductionCooldowns.size();}public int migrationOriginCount(){return migrationOrigins.size();}
    public DeathDiagnostics deathDiagnostics(int limit){EnumMap<CitizenDeathCause,Integer>counts=new EnumMap<>(CitizenDeathCause.class);for(CitizenDeathCause cause:CitizenDeathCause.values())counts.put(cause,0);int examined=0,cap=Math.max(0,limit);for(CitizenRecord citizen:citizens.values()){if(examined>=cap)break;examined++;counts.merge(citizen.deathCause(),1,Integer::sum);}return new DeathDiagnostics(counts,examined,citizens.size()>cap);}
    public record DeathDiagnostics(Map<CitizenDeathCause,Integer>counts,int examined,boolean truncated){public DeathDiagnostics{counts=Map.copyOf(counts);}}
    public boolean readOnly(){return readOnly;}public int quarantinedProfiles(){return quarantinedProfiles;}public int quarantinedCitizens(){return quarantinedCitizens;}public int quarantinedHouseholds(){return quarantinedHouseholds;}public int quarantinedProposals(){return quarantinedProposals;}public int quarantinedCooldowns(){return quarantinedCooldowns;}public int quarantinedPregnancies(){return quarantinedPregnancies;}public int quarantinedReproductionConsents(){return quarantinedReproductionConsents;}public int quarantinedParentage(){return quarantinedParentage;}public int quarantinedOrphans(){return quarantinedOrphans;}public int quarantinedAdoptionConsents(){return quarantinedAdoptionConsents;}public int quarantinedReproductionCooldowns(){return quarantinedReproductionCooldowns;}public int quarantinedMigrations(){return quarantinedMigrations;}public int quarantinedMigrationOrigins(){return quarantinedMigrationOrigins;}public int quarantinedLocations(){return quarantinedLocations;}public int locationCount(){return locations.size();}public String migrationResult(){return migrationResult;}
    public UUID simulationCursor(){return simulationCursor;}public void simulationCursor(UUID value){if(!readOnly){simulationCursor=value;setDirty();}}public UUID proposalMaintenanceCursor(){return proposalMaintenanceCursor;}public void proposalMaintenanceCursor(UUID value){if(!readOnly){proposalMaintenanceCursor=value;setDirty();}}public UUID marriageMatchingCursor(){return marriageMatchingCursor;}public void marriageMatchingCursor(UUID value){if(!readOnly){marriageMatchingCursor=value;setDirty();}}public UUID reproductionCursor(){return reproductionCursor;}public void reproductionCursor(UUID value){if(!readOnly){reproductionCursor=value;setDirty();}}public UUID pregnancyCursor(){return pregnancyCursor;}public void pregnancyCursor(UUID value){if(!readOnly){pregnancyCursor=value;setDirty();}}public UUID migrationCursor(){return migrationCursor;}public void migrationCursor(UUID value){if(!readOnly){migrationCursor=value;setDirty();}}public UUID adoptionConsentCursor(){return adoptionConsentCursor;}public void adoptionConsentCursor(UUID value){if(!readOnly){adoptionConsentCursor=value;setDirty();}}
    public UUID outMigrationHouseholdCursor(){return outMigrationHouseholdCursor;}public void outMigrationHouseholdCursor(UUID value){if(!readOnly){outMigrationHouseholdCursor=value;setDirty();}}public UUID outMigrationCitizenCursor(){return outMigrationCitizenCursor;}public void outMigrationCitizenCursor(UUID value){if(!readOnly){outMigrationCitizenCursor=value;setDirty();}}

    CompoundTag saveTag(){
        if(readOnly&&protectedRoot!=null)return protectedRoot.copy();CompoundTag root=new CompoundTag();root.putInt("SchemaVersion",SCHEMA_VERSION);root.putString("MigrationResult",migrationResult);
        if(simulationCursor!=null)root.putString("SimulationCursor",simulationCursor.toString());
        if(proposalMaintenanceCursor!=null)root.putString("ProposalMaintenanceCursor",proposalMaintenanceCursor.toString());
        if(marriageMatchingCursor!=null)root.putString("MarriageMatchingCursor",marriageMatchingCursor.toString());
        if(reproductionCursor!=null)root.putString("ReproductionCursor",reproductionCursor.toString());
        if(pregnancyCursor!=null)root.putString("PregnancyCursor",pregnancyCursor.toString());
        if(migrationCursor!=null)root.putString("MigrationCursor",migrationCursor.toString());
        if(adoptionConsentCursor!=null)root.putString("AdoptionConsentCursor",adoptionConsentCursor.toString());
        if(outMigrationHouseholdCursor!=null)root.putString("OutMigrationHouseholdCursor",outMigrationHouseholdCursor.toString());
        if(outMigrationCitizenCursor!=null)root.putString("OutMigrationCitizenCursor",outMigrationCitizenCursor.toString());
        CompoundTag quarantine=new CompoundTag();quarantine.putInt("Profiles",quarantinedProfiles);quarantine.putInt("Citizens",quarantinedCitizens);quarantine.putInt("Households",quarantinedHouseholds);quarantine.putInt("Proposals",quarantinedProposals);quarantine.putInt("Cooldowns",quarantinedCooldowns);quarantine.putInt("Pregnancies",quarantinedPregnancies);quarantine.putInt("ReproductionConsents",quarantinedReproductionConsents);quarantine.putInt("Parentage",quarantinedParentage);quarantine.putInt("Orphans",quarantinedOrphans);quarantine.putInt("AdoptionConsents",quarantinedAdoptionConsents);quarantine.putInt("ReproductionCooldowns",quarantinedReproductionCooldowns);quarantine.putInt("Migrations",quarantinedMigrations);quarantine.putInt("MigrationOrigins",quarantinedMigrationOrigins);quarantine.putInt("Locations",quarantinedLocations);root.put("Quarantine",quarantine);
        ListTag profileList=new ListTag();for(PlayerCivitasProfile profile:profiles.values()){CompoundTag t=new CompoundTag();t.putString("PlayerId",profile.playerId().toString());t.putString("Gender",profile.gender().name());t.putLong("Revision",profile.revision());profileList.add(t);}root.put("Profiles",profileList);
        ListTag citizenList=new ListTag();for(CitizenRecord citizen:citizens.values())citizenList.add(saveCitizen(citizen));root.put("Citizens",citizenList);
        ListTag householdList=new ListTag();for(Household household:households.values())householdList.add(saveHousehold(household));root.put("Households",householdList);
        ListTag proposalList=new ListTag();for(MarriageProposal proposal:proposals.values())proposalList.add(saveProposal(proposal));root.put("MarriageProposals",proposalList);
        ListTag cooldownList=new ListTag();for(var entry:proposalCooldowns.entrySet()){CompoundTag t=new CompoundTag();putFamily(t,"Participant",entry.getKey());t.putLong("NextAt",entry.getValue());cooldownList.add(t);}root.put("MarriageCooldowns",cooldownList);
        ListTag pregnancyList=new ListTag();for(PregnancyRecord record:pregnancies.values())pregnancyList.add(savePregnancy(record));root.put("Pregnancies",pregnancyList);
        ListTag consentList=new ListTag();for(ReproductionConsent record:reproductionConsents.values())consentList.add(saveReproductionConsent(record));root.put("ReproductionConsents",consentList);
        ListTag parentageList=new ListTag();for(ParentageRecord record:parentageByChild.values())parentageList.add(saveParentage(record));root.put("Parentage",parentageList);
        ListTag orphanList=new ListTag();for(OrphanRecord record:orphans.values())orphanList.add(saveOrphan(record));root.put("Orphans",orphanList);
        ListTag adoptionConsentList=new ListTag();for(AdoptionConsent record:adoptionConsents.values())adoptionConsentList.add(saveAdoptionConsent(record));root.put("AdoptionConsents",adoptionConsentList);
        ListTag reproductionCooldownList=new ListTag();for(var entry:reproductionCooldowns.entrySet()){CompoundTag t=new CompoundTag();putFamily(t,"Participant",entry.getKey());t.putLong("NextAt",entry.getValue());reproductionCooldownList.add(t);}root.put("ReproductionCooldowns",reproductionCooldownList);
        ListTag migrationList=new ListTag();for(MigrationGroupRecord record:migrations.values())migrationList.add(saveMigration(record));root.put("Migrations",migrationList);
        ListTag originList=new ListTag();for(MigrationOriginRecord record:migrationOrigins.values())originList.add(saveMigrationOrigin(record));root.put("MigrationOrigins",originList);
        ListTag locationList=new ListTag();for(CitizenLocationRecord record:locations.values())locationList.add(saveLocation(record));root.put("CitizenLocations",locationList);
        return root;
    }

    static PopulationSavedData load(CompoundTag root){
        PopulationSavedData data=new PopulationSavedData();int schema=root.getIntOr("SchemaVersion",0);
        if(schema>SCHEMA_VERSION){data.readOnly=true;data.protectedRoot=root.copy();data.migrationResult="future_schema_read_only";LOGGER.warn("Civitas population schema {} is newer than {}; loading read-only",schema,SCHEMA_VERSION);return data;}
        else if(schema<0){data.readOnly=true;data.protectedRoot=root.copy();data.migrationResult="invalid_schema_read_only";LOGGER.warn("Civitas population schema {} is invalid; preserving root read-only",schema);return data;}else if(schema<SCHEMA_VERSION)data.migrationResult="v"+schema+"_to_v"+SCHEMA_VERSION;else data.migrationResult=root.getStringOr("MigrationResult","v13");
        CompoundTag savedQuarantine=root.getCompoundOrEmpty("Quarantine");data.quarantinedProfiles=Math.max(0,savedQuarantine.getIntOr("Profiles",0));data.quarantinedCitizens=Math.max(0,savedQuarantine.getIntOr("Citizens",0));data.quarantinedHouseholds=Math.max(0,savedQuarantine.getIntOr("Households",0));data.quarantinedProposals=Math.max(0,savedQuarantine.getIntOr("Proposals",0));data.quarantinedCooldowns=Math.max(0,savedQuarantine.getIntOr("Cooldowns",0));data.quarantinedPregnancies=Math.max(0,savedQuarantine.getIntOr("Pregnancies",0));data.quarantinedReproductionConsents=Math.max(0,savedQuarantine.getIntOr("ReproductionConsents",0));data.quarantinedParentage=Math.max(0,savedQuarantine.getIntOr("Parentage",0));data.quarantinedOrphans=Math.max(0,savedQuarantine.getIntOr("Orphans",0));data.quarantinedAdoptionConsents=Math.max(0,savedQuarantine.getIntOr("AdoptionConsents",0));data.quarantinedReproductionCooldowns=Math.max(0,savedQuarantine.getIntOr("ReproductionCooldowns",0));data.quarantinedMigrations=Math.max(0,savedQuarantine.getIntOr("Migrations",0));data.quarantinedMigrationOrigins=Math.max(0,savedQuarantine.getIntOr("MigrationOrigins",0));data.quarantinedLocations=Math.max(0,savedQuarantine.getIntOr("Locations",0));
        String cursor=root.getStringOr("SimulationCursor","");if(!cursor.isBlank())try{data.simulationCursor=UUID.fromString(cursor);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed population cursor",exception);}
        String proposalCursor=root.getStringOr("ProposalMaintenanceCursor","");if(!proposalCursor.isBlank())try{data.proposalMaintenanceCursor=UUID.fromString(proposalCursor);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed proposal maintenance cursor",exception);}
        String matchingCursor=root.getStringOr("MarriageMatchingCursor","");if(!matchingCursor.isBlank())try{data.marriageMatchingCursor=UUID.fromString(matchingCursor);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed marriage matching cursor",exception);}
        if(schema>=6){String reproductionCursorValue=root.getStringOr("ReproductionCursor","");if(!reproductionCursorValue.isBlank())try{data.reproductionCursor=UUID.fromString(reproductionCursorValue);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed reproduction cursor",exception);}
        String pregnancyCursorValue=root.getStringOr("PregnancyCursor","");if(!pregnancyCursorValue.isBlank())try{data.pregnancyCursor=UUID.fromString(pregnancyCursorValue);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed pregnancy cursor",exception);}}
        if(schema>=7){String migrationCursorValue=root.getStringOr("MigrationCursor","");if(!migrationCursorValue.isBlank())try{data.migrationCursor=UUID.fromString(migrationCursorValue);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed migration cursor",exception);}}
        if(schema>=11){String adoptionCursorValue=root.getStringOr("AdoptionConsentCursor","");if(!adoptionCursorValue.isBlank())try{data.adoptionConsentCursor=UUID.fromString(adoptionCursorValue);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed adoption consent cursor",exception);}}
        if(schema>=12){String value=root.getStringOr("OutMigrationHouseholdCursor","");if(!value.isBlank())try{data.outMigrationHouseholdCursor=UUID.fromString(value);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed out-migration household cursor",exception);}value=root.getStringOr("OutMigrationCitizenCursor","");if(!value.isBlank())try{data.outMigrationCitizenCursor=UUID.fromString(value);}catch(IllegalArgumentException exception){LOGGER.warn("Ignoring malformed out-migration citizen cursor",exception);}}
        for(Tag raw:root.getListOrEmpty("Profiles")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");UUID id=UUID.fromString(t.getStringOr("PlayerId",""));Gender gender=Gender.valueOf(t.getStringOr("Gender",""));if(data.profiles.putIfAbsent(id,new PlayerCivitasProfile(id,gender,t.getLongOr("Revision",0)))!=null)throw new IllegalArgumentException("duplicate profile id");}catch(RuntimeException exception){data.quarantinedProfiles++;LOGGER.warn("Skipping malformed Civitas player profile",exception);}}
        for(Tag raw:root.getListOrEmpty("Citizens")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");CitizenRecord citizen=loadCitizen(t,schema);if(data.citizens.putIfAbsent(citizen.id(),citizen)!=null)throw new IllegalArgumentException("duplicate citizen id");data.index(citizen);}catch(RuntimeException exception){data.quarantinedCitizens++;LOGGER.warn("Skipping malformed Civitas citizen",exception);}}
        for(Tag raw:root.getListOrEmpty("Households")){try{
            if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");
            Household household=loadHousehold(t,schema);
            if(data.households.containsKey(household.id()))throw new IllegalArgumentException("duplicate household id");
            for(FamilyMemberRef partner:household.partners()){
                if(data.partnerHouseholdIndex.containsKey(partner))throw new IllegalArgumentException("duplicate partner household");
                data.validateFamilyReference(partner,household.cityId(),household.id());
                if(partner.kind()==FamilyMemberRef.Kind.CITIZEN){CitizenRecord citizen=data.citizens.get(partner.id());if(citizen.householdId()==null&&schema<5)data.putCitizen(citizen.withHousehold(household.id()));else if(!household.id().equals(citizen.householdId()))throw new IllegalArgumentException("missing active household backlink");}
            }
            for(FamilyMemberRef guardian:household.guardians()){
                if(data.guardianHouseholdIndex.containsKey(guardian))throw new IllegalArgumentException("duplicate guardian household");
                data.validateFamilyReference(guardian,household.cityId(),household.id());
                if(guardian.kind()==FamilyMemberRef.Kind.CITIZEN&&!household.id().equals(data.citizens.get(guardian.id()).householdId()))throw new IllegalArgumentException("missing guardian household backlink");
            }
            for(FamilyMemberRef historical:household.historicalPartners())data.validateFamilyReference(historical,household.cityId(),null);
            data.households.put(household.id(),household);data.index(household);
        }catch(RuntimeException exception){data.quarantinedHouseholds++;LOGGER.warn("Skipping malformed Civitas household",exception);}}
        for(CitizenRecord citizen:List.copyOf(data.citizens.values())){if(citizen.householdId()==null)continue;Household household=data.households.get(citizen.householdId());FamilyMemberRef reference=FamilyMemberRef.citizen(citizen.id());if(household==null||(!household.partners().contains(reference)&&!household.historicalPartners().contains(reference)&&!household.guardians().contains(reference)&&!household.children().contains(citizen.id()))){data.putCitizen(citizen.withHousehold(null));data.quarantinedCitizens++;LOGGER.warn("Cleared invalid Civitas household backlink for citizen {}",citizen.id());}}
        for(Tag raw:root.getListOrEmpty("MarriageProposals")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");MarriageProposal proposal=loadProposal(t);data.validateFamilyReference(proposal.proposer(),proposal.cityId(),null);data.validateFamilyReference(proposal.target(),proposal.cityId(),null);if(proposal.status()==MarriageProposal.Status.PENDING&&(data.partnerHouseholdIndex.containsKey(proposal.proposer())||data.partnerHouseholdIndex.containsKey(proposal.target())||data.activeProposalIndex.containsKey(proposal.proposer())||data.activeProposalIndex.containsKey(proposal.target())))throw new IllegalArgumentException("conflicting active proposal");if(data.proposals.putIfAbsent(proposal.id(),proposal)!=null)throw new IllegalArgumentException("duplicate proposal id");data.index(proposal);}catch(RuntimeException exception){data.quarantinedProposals++;LOGGER.warn("Skipping malformed Civitas marriage proposal",exception);}}
        for(Tag raw:root.getListOrEmpty("MarriageCooldowns")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");FamilyMemberRef participant=readFamily(t.getCompoundOrEmpty("Participant"));data.validateFamilyReference(participant,null,null);long next=t.getLongOr("NextAt",0);if(next<0||data.proposalCooldowns.putIfAbsent(participant,next)!=null)throw new IllegalArgumentException("invalid marriage cooldown");}catch(RuntimeException exception){data.quarantinedCooldowns++;LOGGER.warn("Skipping malformed Civitas marriage cooldown",exception);}}
        if(schema>=6){for(Tag raw:root.getListOrEmpty("Pregnancies")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");PregnancyRecord record=loadPregnancy(t,schema);for(FamilyMemberRef parent:record.parents())data.validateFamilyReference(parent,record.cityId(),null);if(data.gender(record.gestationalParent())!=Gender.FEMALE||data.genders(record.parents()).size()!=2)throw new IllegalArgumentException("invalid pregnancy genders");if(data.pregnancies.containsKey(record.id())||data.activePregnancyIndex.containsKey(record.gestationalParent()))throw new IllegalArgumentException("duplicate pregnancy");data.pregnancies.put(record.id(),record);data.activePregnancyIndex.put(record.gestationalParent(),record.id());}catch(RuntimeException exception){data.quarantinedPregnancies++;LOGGER.warn("Skipping malformed Civitas pregnancy",exception);}}
        if(schema>=9)for(Tag raw:root.getListOrEmpty("ReproductionConsents")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");ReproductionConsent record=loadReproductionConsent(t);data.validateFamilyReference(record.proposer(),record.cityId(),null);data.validateFamilyReference(record.target(),record.cityId(),null);if(data.reproductionConsents.containsKey(record.id())||data.activeReproductionConsentIndex.containsKey(record.proposer())||data.activeReproductionConsentIndex.containsKey(record.target()))throw new IllegalArgumentException("conflicting reproduction consent");data.reproductionConsents.put(record.id(),record);data.activeReproductionConsentIndex.put(record.proposer(),record.id());data.activeReproductionConsentIndex.put(record.target(),record.id());}catch(RuntimeException exception){data.quarantinedReproductionConsents++;LOGGER.warn("Skipping malformed Civitas reproduction consent",exception);}}
        for(Tag raw:root.getListOrEmpty("Parentage")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");ParentageRecord record=loadParentage(t);CitizenRecord child=data.citizens.get(record.childId());if(child==null||child.cityId()!=null&&!record.cityId().equals(child.cityId()))throw new IllegalArgumentException("missing parentage child");for(FamilyMemberRef parent:record.parents()){if(parent.kind()==FamilyMemberRef.Kind.PLAYER){if(!data.profiles.containsKey(parent.id()))throw new IllegalArgumentException("missing player parent");}else{CitizenRecord adult=data.citizens.get(parent.id());if(adult==null||child.cityId()!=null&&!record.cityId().equals(adult.cityId())||child.cityId()==null&&adult.cityId()!=null)throw new IllegalArgumentException("invalid citizen parent");}}if(data.parentageByChild.putIfAbsent(record.childId(),record)!=null)throw new IllegalArgumentException("duplicate parentage");data.index(record);}catch(RuntimeException exception){data.quarantinedParentage++;LOGGER.warn("Skipping malformed Civitas parentage",exception);}}
        for(Tag raw:root.getListOrEmpty("Orphans")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");OrphanRecord record=loadOrphan(t);CitizenRecord child=data.citizens.get(record.childId());if(child==null||!child.alive()||!record.cityId().equals(child.cityId())||!data.parentageByChild.containsKey(record.childId()))throw new IllegalArgumentException("invalid orphan child");if(record.originHouseholdId()!=null){Household household=data.households.get(record.originHouseholdId());if(household==null||!record.cityId().equals(household.cityId()))throw new IllegalArgumentException("invalid orphan household");}if(data.orphans.putIfAbsent(record.childId(),record)!=null)throw new IllegalArgumentException("duplicate orphan");data.orphanCityIndex.computeIfAbsent(record.cityId(),ignored->new LinkedHashSet<>()).add(record.childId());}catch(RuntimeException exception){data.quarantinedOrphans++;LOGGER.warn("Skipping malformed Civitas orphan",exception);}}
        if(schema>=11)for(Tag raw:root.getListOrEmpty("AdoptionConsents")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");AdoptionConsent record=loadAdoptionConsent(t);if(!data.orphans.containsKey(record.childId())||data.adoptionConsents.containsKey(record.id())||data.adoptionConsentByChild.containsKey(record.childId()))throw new IllegalArgumentException("invalid adoption consent child");for(FamilyMemberRef guardian:record.guardians())data.validateFamilyReference(guardian,record.cityId(),null);data.adoptionConsents.put(record.id(),record);data.index(record);}catch(RuntimeException exception){data.quarantinedAdoptionConsents++;LOGGER.warn("Skipping malformed Civitas adoption consent",exception);}}
        for(Tag raw:root.getListOrEmpty("ReproductionCooldowns")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");FamilyMemberRef participant=readFamily(t.getCompoundOrEmpty("Participant"));data.validateFamilyReference(participant,null,null);long next=t.getLongOr("NextAt",0);if(next<0||data.reproductionCooldowns.putIfAbsent(participant,next)!=null)throw new IllegalArgumentException("invalid reproduction cooldown");}catch(RuntimeException exception){data.quarantinedReproductionCooldowns++;LOGGER.warn("Skipping malformed Civitas reproduction cooldown",exception);}}}
        if(schema>=7){for(Tag raw:root.getListOrEmpty("Migrations")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");MigrationGroupRecord record=loadMigration(t,schema);if(data.migrations.containsKey(record.id()))throw new IllegalArgumentException("duplicate migration");for(UUID member:record.members()){CitizenRecord citizen=data.citizens.get(member);if(citizen==null||citizen.cityId()!=null||data.migrationByMember.containsKey(member))throw new IllegalArgumentException("invalid migrant member");}data.migrations.put(record.id(),record);data.index(record);}catch(RuntimeException exception){data.quarantinedMigrations++;LOGGER.warn("Skipping malformed Civitas migration",exception);}}
        for(Tag raw:root.getListOrEmpty("MigrationOrigins")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");MigrationOriginRecord record=loadMigrationOrigin(t);CitizenRecord citizen=data.citizens.get(record.citizenId());if(citizen==null||!record.cityId().equals(citizen.cityId())||data.migrationOrigins.putIfAbsent(record.citizenId(),record)!=null)throw new IllegalArgumentException("invalid migration origin");}catch(RuntimeException exception){data.quarantinedMigrationOrigins++;LOGGER.warn("Skipping malformed Civitas migration origin",exception);}}
        for(CitizenRecord citizen:List.copyOf(data.citizens.values()))if(citizen.cityId()==null&&!data.migrationByMember.containsKey(citizen.id())){data.citizens.remove(citizen.id());data.unindex(citizen);data.quarantinedCitizens++;LOGGER.warn("Removed unlinked migrant candidate {}",citizen.id());}}
        if(schema>=8)for(Tag raw:root.getListOrEmpty("CitizenLocations")){try{if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("not compound");CitizenLocationRecord record=loadLocation(t);CitizenRecord citizen=data.citizens.get(record.citizenId());if(citizen==null||citizen.cityId()==null||!citizen.cityId().equals(record.cityId())||data.locations.putIfAbsent(record.citizenId(),record)!=null)throw new IllegalArgumentException("invalid citizen location");}catch(RuntimeException exception){data.quarantinedLocations++;LOGGER.warn("Skipping malformed Civitas citizen location",exception);}}
        return data;
    }

    private static CompoundTag saveCitizen(CitizenRecord c){CompoundTag t=new CompoundTag();t.putString("Id",c.id().toString());t.putString("GivenName",c.givenName());t.putString("FamilyName",c.familyName());t.putString("Race",c.race().name());t.putString("Appearance",c.appearanceKey());t.putString("Gender",c.gender().name());t.putLong("AgeTicks",c.ageTicks());t.putLong("LastAgeUpdateTick",c.lastAgeUpdateTick());t.putInt("LifespanYears",c.lifespanYears());t.putLong("DiedAtTick",c.diedAtTick());t.putString("DeathCause",c.deathCause().name());putUuid(t,"CityId",c.cityId());putUuid(t,"HouseholdId",c.householdId());putUuid(t,"ResidenceId",c.residenceId());putUuid(t,"WorkBuildingId",c.workBuildingId());t.putString("Profession",c.profession());t.putInt("Health",c.health());CompoundTag needs=new CompoundTag();needs.putInt("Food",c.needs().food());needs.putInt("Safety",c.needs().safety());needs.putInt("Rest",c.needs().rest());needs.putInt("Social",c.needs().social());t.put("Needs",needs);ListTag skills=new ListTag();c.skills().forEach((key,value)->{CompoundTag skill=new CompoundTag();skill.putString("Key",key);skill.putInt("Value",value);skills.add(skill);});t.put("Skills",skills);t.put("Relationships",uuidList(c.relationships()));t.putDouble("SettlementWillingness",c.settlementWillingness());t.putDouble("MigrationWillingness",c.migrationWillingness());t.putString("RuntimeState",c.runtimeState().name());t.putLong("RuntimeLockUntilTick",c.runtimeLockUntilTick());t.putLong("Revision",c.revision());return t;}
    private static CitizenRecord loadCitizen(CompoundTag t,int schema){UUID id=UUID.fromString(t.getStringOr("Id",""));CompoundTag needs=t.getCompoundOrEmpty("Needs");Map<String,Integer> skills=new HashMap<>();for(Tag raw:t.getListOrEmpty("Skills"))if(raw instanceof CompoundTag skill){String key=skill.getStringOr("Key","");if(!key.isBlank()&&skills.putIfAbsent(key,Math.max(0,skill.getIntOr("Value",0)))!=null)throw new IllegalArgumentException("duplicate skill key");}int lifespan=schema>=3?t.getIntOr("LifespanYears",0):new LifespanRules(60,90).years(id);long died=schema>=3?t.getLongOr("DiedAtTick",0):0;CitizenDeathCause cause=schema>=10?CitizenDeathCause.valueOf(t.getStringOr("DeathCause","")):(died>0?CitizenDeathCause.OLD_AGE:CitizenDeathCause.NONE);CitizenRuntimeState runtime=CitizenRuntimeState.valueOf(t.getStringOr("RuntimeState","VIRTUAL"));if(lifespan<1||died<0||(died>0&&runtime!=CitizenRuntimeState.VIRTUAL))throw new IllegalArgumentException("invalid citizen lifespan/death state");return new CitizenRecord(id,t.getStringOr("GivenName",""),t.getStringOr("FamilyName",""),CitizenRace.valueOf(t.getStringOr("Race","")),t.getStringOr("Appearance",""),Gender.valueOf(t.getStringOr("Gender","")),t.getLongOr("AgeTicks",0),t.getLongOr("LastAgeUpdateTick",0),uuid(t,"CityId"),uuid(t,"HouseholdId"),uuid(t,"ResidenceId"),uuid(t,"WorkBuildingId"),t.getStringOr("Profession",""),t.getIntOr("Health",100),new CitizenNeeds(needs.getIntOr("Food",50),needs.getIntOr("Safety",50),needs.getIntOr("Rest",50),needs.getIntOr("Social",50)),skills,readUuidList(t.getListOrEmpty("Relationships")),t.getDoubleOr("SettlementWillingness",50),t.getDoubleOr("MigrationWillingness",0),runtime,t.getLongOr("RuntimeLockUntilTick",0),lifespan,died,cause,t.getLongOr("Revision",0));}
    private static CompoundTag saveHousehold(Household h){CompoundTag t=new CompoundTag();t.putString("Id",h.id().toString());t.putString("CityId",h.cityId().toString());t.put("Partners",familyList(h.partners()));t.put("HistoricalPartners",familyList(h.historicalPartners()));t.put("Guardians",familyList(h.guardians()));t.put("Children",uuidList(h.children()));putUuid(t,"ResidenceId",h.residenceId());t.putInt("FoodCoverage",h.foodCoverage());t.putInt("HousingCoverage",h.housingCoverage());t.putLong("Revision",h.revision());return t;}
    private static Household loadHousehold(CompoundTag t,int schema){Set<FamilyMemberRef>partners=readFamilyList(t.getListOrEmpty("Partners"),schema),history=schema>=5?readFamilyList(t.getListOrEmpty("HistoricalPartners"),schema):Set.of();Set<UUID>children=readUuidList(t.getListOrEmpty("Children"));Set<FamilyMemberRef>guardians=schema>=6?readFamilyList(t.getListOrEmpty("Guardians"),schema):(children.isEmpty()?Set.of():partners);return new Household(UUID.fromString(t.getStringOr("Id","")),UUID.fromString(t.getStringOr("CityId","")),partners,history,guardians,children,uuid(t,"ResidenceId"),t.getIntOr("FoodCoverage",0),t.getIntOr("HousingCoverage",0),t.getLongOr("Revision",0));}
    private static CompoundTag saveProposal(MarriageProposal p){CompoundTag t=new CompoundTag();t.putString("Id",p.id().toString());t.putString("CityId",p.cityId().toString());putFamily(t,"Proposer",p.proposer());putFamily(t,"Target",p.target());t.putBoolean("ProposerConfirmed",p.proposerConfirmed());t.putBoolean("TargetConfirmed",p.targetConfirmed());t.putLong("CreatedAt",p.createdAt());t.putLong("ExpiresAt",p.expiresAt());t.putString("Status",p.status().name());t.putLong("Revision",p.revision());return t;}
    private static MarriageProposal loadProposal(CompoundTag t){return new MarriageProposal(UUID.fromString(t.getStringOr("Id","")),UUID.fromString(t.getStringOr("CityId","")),readFamily(t.getCompoundOrEmpty("Proposer")),readFamily(t.getCompoundOrEmpty("Target")),t.getBooleanOr("ProposerConfirmed",false),t.getBooleanOr("TargetConfirmed",false),t.getLongOr("CreatedAt",0),t.getLongOr("ExpiresAt",0),MarriageProposal.Status.valueOf(t.getStringOr("Status","")),t.getLongOr("Revision",0));}
    private static CompoundTag savePregnancy(PregnancyRecord p){CompoundTag t=new CompoundTag();t.putString("Id",p.id().toString());t.putString("CityId",p.cityId().toString());t.put("Parents",familyList(p.parents()));putFamily(t,"GestationalParent",p.gestationalParent());t.putLong("ConceivedAt",p.conceivedAt());t.putLong("DueAt",p.dueAt());t.putBoolean("Infidelity",p.infidelity());t.putDouble("ConceptionWillingness",p.conceptionWillingness());if(p.evaluation()!=null)t.put("Evaluation",saveReproductionEvaluation(p.evaluation()));t.putLong("Revision",p.revision());return t;}
    private static PregnancyRecord loadPregnancy(CompoundTag t,int schema){var evaluation=schema>=13&&t.get("Evaluation")!=null?loadReproductionEvaluation(t.getCompoundOrEmpty("Evaluation")):null;return new PregnancyRecord(UUID.fromString(t.getStringOr("Id","")),UUID.fromString(t.getStringOr("CityId","")),readFamilyList(t.getListOrEmpty("Parents"),6),readFamily(t.getCompoundOrEmpty("GestationalParent")),t.getLongOr("ConceivedAt",0),t.getLongOr("DueAt",0),t.getBooleanOr("Infidelity",false),t.getDoubleOr("ConceptionWillingness",0),evaluation,t.getLongOr("Revision",0));}
    private static CompoundTag saveReproductionEvaluation(ReproductionRules.Result r){CompoundTag t=new CompoundTag();t.putBoolean("Eligible",r.biologicallyEligible());t.putDouble("StageModifier",r.stageModifier());t.putDouble("ConditionScore",r.conditionScore());t.putDouble("ConsentModifier",r.consentModifier());t.putDouble("EffectiveWillingness",r.effectiveWillingness());t.putLong("AttemptIntervalTicks",r.attemptIntervalTicks());t.putString("Reason",r.reason());CompoundTag c=new CompoundTag();c.putDouble("Housing",r.conditions().housing());c.putDouble("Food",r.conditions().food());c.putDouble("Safety",r.conditions().safety());c.putDouble("Civility",r.conditions().civility());c.putDouble("Activity",r.conditions().activity());c.putDouble("FamilyStability",r.conditions().familyStability());c.putDouble("CasualtyRecovery",r.conditions().casualtyRecovery());c.putDouble("Uncrowded",r.conditions().uncrowded());t.put("Conditions",c);CompoundTag w=new CompoundTag();w.putDouble("Housing",r.weights().housing());w.putDouble("Food",r.weights().food());w.putDouble("Safety",r.weights().safety());w.putDouble("Civility",r.weights().civility());w.putDouble("Activity",r.weights().activity());w.putDouble("FamilyStability",r.weights().familyStability());w.putDouble("CasualtyRecovery",r.weights().casualtyRecovery());w.putDouble("Uncrowded",r.weights().uncrowded());t.put("Weights",w);CompoundTag parts=new CompoundTag();r.components().forEach(parts::putDouble);t.put("Components",parts);return t;}
    private static ReproductionRules.Result loadReproductionEvaluation(CompoundTag t){CompoundTag c=t.getCompoundOrEmpty("Conditions"),w=t.getCompoundOrEmpty("Weights"),parts=t.getCompoundOrEmpty("Components");var conditions=new ReproductionRules.Conditions(c.getDoubleOr("Housing",Double.NaN),c.getDoubleOr("Food",Double.NaN),c.getDoubleOr("Safety",Double.NaN),c.getDoubleOr("Civility",Double.NaN),c.getDoubleOr("Activity",Double.NaN),c.getDoubleOr("FamilyStability",Double.NaN),c.getDoubleOr("CasualtyRecovery",Double.NaN),c.getDoubleOr("Uncrowded",Double.NaN));var weights=new ReproductionRules.Weights(w.getDoubleOr("Housing",Double.NaN),w.getDoubleOr("Food",Double.NaN),w.getDoubleOr("Safety",Double.NaN),w.getDoubleOr("Civility",Double.NaN),w.getDoubleOr("Activity",Double.NaN),w.getDoubleOr("FamilyStability",Double.NaN),w.getDoubleOr("CasualtyRecovery",Double.NaN),w.getDoubleOr("Uncrowded",Double.NaN));Map<String,Double>components=new LinkedHashMap<>();for(String key:List.of("housing","food","safety","civility","activity","family_stability","casualty_recovery","uncrowded"))components.put(key,parts.getDoubleOr(key,Double.NaN));return new ReproductionRules.Result(t.getBooleanOr("Eligible",false),t.getDoubleOr("StageModifier",Double.NaN),t.getDoubleOr("ConditionScore",Double.NaN),t.getDoubleOr("ConsentModifier",Double.NaN),t.getDoubleOr("EffectiveWillingness",Double.NaN),t.getLongOr("AttemptIntervalTicks",0),conditions,weights,components,t.getStringOr("Reason",""));}
    private static CompoundTag saveReproductionConsent(ReproductionConsent p){CompoundTag t=new CompoundTag();t.putString("Id",p.id().toString());t.putString("CityId",p.cityId().toString());putFamily(t,"Proposer",p.proposer());putFamily(t,"Target",p.target());t.putLong("CreatedAt",p.createdAt());t.putLong("ExpiresAt",p.expiresAt());t.putLong("Revision",p.revision());return t;}
    private static ReproductionConsent loadReproductionConsent(CompoundTag t){return new ReproductionConsent(UUID.fromString(t.getStringOr("Id","")),UUID.fromString(t.getStringOr("CityId","")),readFamily(t.getCompoundOrEmpty("Proposer")),readFamily(t.getCompoundOrEmpty("Target")),t.getLongOr("CreatedAt",0),t.getLongOr("ExpiresAt",0),t.getLongOr("Revision",0));}
    private static CompoundTag saveParentage(ParentageRecord p){CompoundTag t=new CompoundTag();t.putString("ChildId",p.childId().toString());t.putString("CityId",p.cityId().toString());t.put("Parents",familyList(p.parents()));t.putLong("BornAt",p.bornAt());t.putBoolean("Infidelity",p.infidelity());t.putString("Source",p.source().name());t.putLong("Revision",p.revision());return t;}
    private static ParentageRecord loadParentage(CompoundTag t){return new ParentageRecord(UUID.fromString(t.getStringOr("ChildId","")),UUID.fromString(t.getStringOr("CityId","")),readFamilyList(t.getListOrEmpty("Parents"),6),t.getLongOr("BornAt",0),t.getBooleanOr("Infidelity",false),ParentageRecord.Source.valueOf(t.getStringOr("Source","")),t.getLongOr("Revision",0));}
    private static CompoundTag saveOrphan(OrphanRecord o){CompoundTag t=new CompoundTag();t.putString("ChildId",o.childId().toString());t.putString("CityId",o.cityId().toString());t.putString("Reason",o.reason().name());putUuid(t,"OriginHouseholdId",o.originHouseholdId());putUuid(t,"LastResidenceId",o.lastResidenceId());t.putLong("AdmittedAt",o.admittedAt());t.putLong("Revision",o.revision());return t;}
    private static OrphanRecord loadOrphan(CompoundTag t){return new OrphanRecord(UUID.fromString(t.getStringOr("ChildId","")),UUID.fromString(t.getStringOr("CityId","")),OrphanRecord.Reason.valueOf(t.getStringOr("Reason","")),uuid(t,"OriginHouseholdId"),uuid(t,"LastResidenceId"),t.getLongOr("AdmittedAt",0),t.getLongOr("Revision",0));}
    private static CompoundTag saveAdoptionConsent(AdoptionConsent c){CompoundTag t=new CompoundTag();t.putString("Id",c.id().toString());t.putString("CityId",c.cityId().toString());t.putString("ChildId",c.childId().toString());t.putString("HouseholdId",c.householdId().toString());t.put("Guardians",familyList(c.guardians()));t.put("RequiredPlayers",uuidList(c.requiredPlayers()));t.put("ConfirmedPlayers",uuidList(c.confirmedPlayers()));putUuid(t,"ResidenceId",c.residenceId());t.putString("AnchorDimension",c.anchorDimension());t.putLong("AnchorPosition",c.anchorPosition());t.putLong("CreatedAt",c.createdAt());t.putLong("ExpiresAt",c.expiresAt());t.putLong("Revision",c.revision());return t;}
    private static AdoptionConsent loadAdoptionConsent(CompoundTag t){return new AdoptionConsent(UUID.fromString(t.getStringOr("Id","")),UUID.fromString(t.getStringOr("CityId","")),UUID.fromString(t.getStringOr("ChildId","")),UUID.fromString(t.getStringOr("HouseholdId","")),readFamilyList(t.getListOrEmpty("Guardians"),11),readUuidList(t.getListOrEmpty("RequiredPlayers")),readUuidList(t.getListOrEmpty("ConfirmedPlayers")),uuid(t,"ResidenceId"),t.getStringOr("AnchorDimension",""),t.getLongOr("AnchorPosition",0),t.getLongOr("CreatedAt",0),t.getLongOr("ExpiresAt",0),t.getLongOr("Revision",0));}
    private static CompoundTag saveMigration(MigrationGroupRecord m){CompoundTag t=new CompoundTag();t.putString("Id",m.id().toString());t.putString("TargetCityId",m.targetCityId().toString());t.putString("Dimension",m.dimension());t.putLong("OriginPos",m.originPos());t.putLong("TargetPos",m.targetPos());t.put("Members",uuidList(m.members()));t.put("Partners",uuidList(m.partners()));t.put("Guardians",uuidList(m.guardians()));t.put("Children",uuidList(m.children()));ListTag positions=new ListTag();for(var entry:m.memberPositions().entrySet()){CompoundTag p=new CompoundTag();p.putString("MemberId",entry.getKey().toString());p.putLong("Pos",entry.getValue());positions.add(p);}t.put("MemberPositions",positions);t.putString("State",m.state().name());t.putDouble("AttractionScore",m.attractionScore());t.putLong("CreatedAt",m.createdAt());t.putLong("DecisionDeadline",m.decisionDeadline());t.putLong("Revision",m.revision());return t;}
    private static MigrationGroupRecord loadMigration(CompoundTag t,int schema){Map<UUID,Long>positions=new HashMap<>();for(Tag raw:t.getListOrEmpty("MemberPositions")){if(!(raw instanceof CompoundTag p))throw new IllegalArgumentException("invalid migration position");if(positions.putIfAbsent(UUID.fromString(p.getStringOr("MemberId","")),p.getLongOr("Pos",0))!=null)throw new IllegalArgumentException("duplicate migration position");}Set<UUID>partners=readUuidList(t.getListOrEmpty("Partners")),children=readUuidList(t.getListOrEmpty("Children")),guardians=schema>=12?readUuidList(t.getListOrEmpty("Guardians")):(children.isEmpty()?Set.of():partners);return new MigrationGroupRecord(UUID.fromString(t.getStringOr("Id","")),UUID.fromString(t.getStringOr("TargetCityId","")),t.getStringOr("Dimension",""),t.getLongOr("OriginPos",0),t.getLongOr("TargetPos",0),readUuidList(t.getListOrEmpty("Members")),partners,guardians,children,positions,MigrationGroupRecord.State.valueOf(t.getStringOr("State","")),t.getDoubleOr("AttractionScore",0),t.getLongOr("CreatedAt",0),t.getLongOr("DecisionDeadline",0),t.getLongOr("Revision",0));}
    private static CompoundTag saveMigrationOrigin(MigrationOriginRecord o){CompoundTag t=new CompoundTag();t.putString("CitizenId",o.citizenId().toString());t.putString("GroupId",o.groupId().toString());t.putString("CityId",o.cityId().toString());t.putString("Dimension",o.dimension());t.putLong("OriginPos",o.originPos());t.putLong("SettledAt",o.settledAt());t.putLong("Revision",o.revision());return t;}
    private static MigrationOriginRecord loadMigrationOrigin(CompoundTag t){return new MigrationOriginRecord(UUID.fromString(t.getStringOr("CitizenId","")),UUID.fromString(t.getStringOr("GroupId","")),UUID.fromString(t.getStringOr("CityId","")),t.getStringOr("Dimension",""),t.getLongOr("OriginPos",0),t.getLongOr("SettledAt",0),t.getLongOr("Revision",0));}
    private static CompoundTag saveLocation(CitizenLocationRecord l){CompoundTag t=new CompoundTag();t.putString("CitizenId",l.citizenId().toString());t.putString("CityId",l.cityId().toString());t.putString("Dimension",l.dimension());t.putLong("Position",l.position());t.putLong("UpdatedAt",l.updatedAt());t.putLong("Revision",l.revision());return t;}
    private static CitizenLocationRecord loadLocation(CompoundTag t){return new CitizenLocationRecord(UUID.fromString(t.getStringOr("CitizenId","")),UUID.fromString(t.getStringOr("CityId","")),t.getStringOr("Dimension",""),t.getLongOr("Position",0),t.getLongOr("UpdatedAt",0),t.getLongOr("Revision",0));}
    private static void putUuid(CompoundTag t,String key,UUID value){if(value!=null)t.putString(key,value.toString());}
    private static UUID uuid(CompoundTag t,String key){String value=t.getStringOr(key,"");return value.isBlank()?null:UUID.fromString(value);}
    private static ListTag uuidList(Collection<UUID> values){ListTag list=new ListTag();for(UUID value:values){CompoundTag t=new CompoundTag();t.putString("Id",value.toString());list.add(t);}return list;}
    private static Set<UUID> readUuidList(ListTag list){Set<UUID> result=new HashSet<>();for(Tag raw:list){if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("invalid UUID list");if(!result.add(UUID.fromString(t.getStringOr("Id",""))))throw new IllegalArgumentException("duplicate UUID list entry");}return result;}
    private static ListTag familyList(Collection<FamilyMemberRef>values){ListTag list=new ListTag();for(FamilyMemberRef value:values){CompoundTag t=new CompoundTag();putFamily(t,"Value",value);list.add(t.getCompoundOrEmpty("Value"));}return list;}
    private static Set<FamilyMemberRef>readFamilyList(ListTag list,int schema){Set<FamilyMemberRef>result=new HashSet<>();for(Tag raw:list){if(!(raw instanceof CompoundTag t))throw new IllegalArgumentException("invalid family list");FamilyMemberRef value=schema<4?FamilyMemberRef.citizen(UUID.fromString(t.getStringOr("Id",""))):readFamily(t);if(!result.add(value))throw new IllegalArgumentException("duplicate family member");}return result;}
    private static void putFamily(CompoundTag owner,String key,FamilyMemberRef value){CompoundTag t=new CompoundTag();t.putString("Kind",value.kind().name());t.putString("Id",value.id().toString());owner.put(key,t);}
    private static FamilyMemberRef readFamily(CompoundTag t){return new FamilyMemberRef(FamilyMemberRef.Kind.valueOf(t.getStringOr("Kind","")),UUID.fromString(t.getStringOr("Id","")));}
    private static boolean validProposalTransition(MarriageProposal before,MarriageProposal after){if(!before.cityId().equals(after.cityId())||!before.proposer().equals(after.proposer())||!before.target().equals(after.target())||before.createdAt()!=after.createdAt()||before.expiresAt()!=after.expiresAt()||after.revision()!=before.revision()+1||before.status()!=MarriageProposal.Status.PENDING||before.proposerConfirmed()&&!after.proposerConfirmed()||before.targetConfirmed()&&!after.targetConfirmed())return false;return after.status()==MarriageProposal.Status.PENDING||after.status()==MarriageProposal.Status.ACCEPTED||after.status()==MarriageProposal.Status.DECLINED||after.status()==MarriageProposal.Status.EXPIRED||after.status()==MarriageProposal.Status.CANCELLED;}
    private static boolean samePregnancyIdentity(PregnancyRecord a,PregnancyRecord b){return a.id().equals(b.id())&&a.cityId().equals(b.cityId())&&a.parents().equals(b.parents())&&a.gestationalParent().equals(b.gestationalParent())&&a.conceivedAt()==b.conceivedAt()&&a.dueAt()==b.dueAt()&&a.infidelity()==b.infidelity()&&Double.compare(a.conceptionWillingness(),b.conceptionWillingness())==0&&Objects.equals(a.evaluation(),b.evaluation());}
    private static boolean sameParentageIdentity(ParentageRecord a,ParentageRecord b){return a.childId().equals(b.childId())&&a.cityId().equals(b.cityId())&&a.parents().equals(b.parents())&&a.bornAt()==b.bornAt()&&a.infidelity()==b.infidelity()&&a.source()==b.source();}
    private static boolean sameOrphanIdentity(OrphanRecord a,OrphanRecord b){return a.childId().equals(b.childId())&&a.cityId().equals(b.cityId())&&a.reason()==b.reason()&&Objects.equals(a.originHouseholdId(),b.originHouseholdId())&&Objects.equals(a.lastResidenceId(),b.lastResidenceId())&&a.admittedAt()==b.admittedAt();}
    private static boolean sameAdoptionConsentIdentity(AdoptionConsent a,AdoptionConsent b){return a.id().equals(b.id())&&a.cityId().equals(b.cityId())&&a.childId().equals(b.childId())&&a.householdId().equals(b.householdId())&&a.guardians().equals(b.guardians())&&a.requiredPlayers().equals(b.requiredPlayers())&&Objects.equals(a.residenceId(),b.residenceId())&&a.anchorDimension().equals(b.anchorDimension())&&a.anchorPosition()==b.anchorPosition()&&a.createdAt()==b.createdAt()&&a.expiresAt()==b.expiresAt();}
    private static boolean sameMigrationIdentity(MigrationGroupRecord a,MigrationGroupRecord b){return a.id().equals(b.id())&&a.targetCityId().equals(b.targetCityId())&&a.dimension().equals(b.dimension())&&a.originPos()==b.originPos()&&a.members().equals(b.members())&&a.partners().equals(b.partners())&&a.guardians().equals(b.guardians())&&a.children().equals(b.children())&&Double.compare(a.attractionScore(),b.attractionScore())==0&&a.createdAt()==b.createdAt();}
    private static boolean sameMigrationFamily(MigrationGroupRecord a,MigrationGroupRecord b){return a.id().equals(b.id())&&a.dimension().equals(b.dimension())&&a.members().equals(b.members())&&a.partners().equals(b.partners())&&a.guardians().equals(b.guardians())&&a.children().equals(b.children());}
    private Gender gender(FamilyMemberRef member){return member.kind()==FamilyMemberRef.Kind.PLAYER?Optional.ofNullable(profiles.get(member.id())).map(PlayerCivitasProfile::gender).orElseThrow():Optional.ofNullable(citizens.get(member.id())).map(CitizenRecord::gender).orElseThrow();}
    private long memberRevision(FamilyMemberRef member){return member.kind()==FamilyMemberRef.Kind.PLAYER?Optional.ofNullable(profiles.get(member.id())).map(PlayerCivitasProfile::revision).orElse(Long.MIN_VALUE):Optional.ofNullable(citizens.get(member.id())).map(CitizenRecord::revision).orElse(Long.MIN_VALUE);}
    private Set<Gender>genders(Collection<FamilyMemberRef>members){EnumSet<Gender>values=EnumSet.noneOf(Gender.class);for(FamilyMemberRef member:members)values.add(gender(member));return values;}
    private void validateFamilyReference(FamilyMemberRef member,UUID cityId,UUID householdId){if(member.kind()==FamilyMemberRef.Kind.PLAYER){if(!profiles.containsKey(member.id()))throw new IllegalArgumentException("missing player family profile");return;}CitizenRecord citizen=citizens.get(member.id());if(citizen==null||(cityId!=null&&!cityId.equals(citizen.cityId()))||(householdId!=null&&citizen.householdId()!=null&&!householdId.equals(citizen.householdId())))throw new IllegalArgumentException("invalid citizen family reference");}
    private void index(CitizenRecord citizen){if(citizen.cityId()!=null)citizenCityIndex.computeIfAbsent(citizen.cityId(),ignored->new LinkedHashSet<>()).add(citizen.id());citizenNameIndex.computeIfAbsent(normalizeName(citizen.displayName()),ignored->new LinkedHashSet<>()).add(citizen.id());}
    private void unindex(CitizenRecord citizen){removeIndex(citizenCityIndex,citizen.cityId(),citizen.id());removeIndex(citizenNameIndex,normalizeName(citizen.displayName()),citizen.id());}
    private void index(Household household){householdCityIndex.computeIfAbsent(household.cityId(),ignored->new LinkedHashSet<>()).add(household.id());for(FamilyMemberRef partner:household.partners())partnerHouseholdIndex.put(partner,household.id());for(FamilyMemberRef guardian:household.guardians())guardianHouseholdIndex.put(guardian,household.id());}
    private void unindex(Household household){removeIndex(householdCityIndex,household.cityId(),household.id());for(FamilyMemberRef partner:household.partners())partnerHouseholdIndex.remove(partner,household.id());for(FamilyMemberRef guardian:household.guardians())guardianHouseholdIndex.remove(guardian,household.id());}
    private void index(MarriageProposal proposal){proposalParticipantIndex.computeIfAbsent(proposal.proposer(),ignored->new LinkedHashSet<>()).add(proposal.id());proposalParticipantIndex.computeIfAbsent(proposal.target(),ignored->new LinkedHashSet<>()).add(proposal.id());if(proposal.status()==MarriageProposal.Status.PENDING){UUID a=activeProposalIndex.putIfAbsent(proposal.proposer(),proposal.id()),b=activeProposalIndex.putIfAbsent(proposal.target(),proposal.id());if((a!=null&&!a.equals(proposal.id()))||(b!=null&&!b.equals(proposal.id())))throw new IllegalArgumentException("participant already has active proposal");}}
    private void unindex(MarriageProposal proposal){removeIndex(proposalParticipantIndex,proposal.proposer(),proposal.id());removeIndex(proposalParticipantIndex,proposal.target(),proposal.id());if(proposal.status()==MarriageProposal.Status.PENDING){activeProposalIndex.remove(proposal.proposer(),proposal.id());activeProposalIndex.remove(proposal.target(),proposal.id());}}
    private void index(ParentageRecord parentage){for(FamilyMemberRef parent:parentage.parents())childrenByParent.computeIfAbsent(parent,ignored->new LinkedHashSet<>()).add(parentage.childId());}
    private void unindex(ParentageRecord parentage){for(FamilyMemberRef parent:parentage.parents())removeIndex(childrenByParent,parent,parentage.childId());}
    private void index(AdoptionConsent consent){adoptionConsentByChild.put(consent.childId(),consent.id());for(UUID player:consent.requiredPlayers())adoptionConsentsByPlayer.computeIfAbsent(player,ignored->new LinkedHashSet<>()).add(consent.id());}
    private void unindex(AdoptionConsent consent){adoptionConsentByChild.remove(consent.childId(),consent.id());for(UUID player:consent.requiredPlayers())removeIndex(adoptionConsentsByPlayer,player,consent.id());}
    private void index(MigrationGroupRecord group){migrationCityIndex.computeIfAbsent(group.targetCityId(),ignored->new LinkedHashSet<>()).add(group.id());for(UUID member:group.members()){UUID previous=migrationByMember.putIfAbsent(member,group.id());if(previous!=null&&!previous.equals(group.id()))throw new IllegalArgumentException("migrant belongs to multiple groups");}}
    private void unindex(MigrationGroupRecord group){removeIndex(migrationCityIndex,group.targetCityId(),group.id());for(UUID member:group.members())migrationByMember.remove(member,group.id());}
    private static<K>void removeIndex(Map<K,LinkedHashSet<UUID>>index,K key,UUID id){if(key==null)return;Set<UUID>ids=index.get(key);if(ids!=null&&ids.remove(id)&&ids.isEmpty())index.remove(key);}
    private static String normalizeName(String value){return value==null?"":value.trim().toLowerCase(Locale.ROOT);}
}
