package com.seaquake6324.civitas.presentation.screen;

import com.seaquake6324.civitas.infrastructure.network.OpenCitizenInfoPayload;
import com.seaquake6324.civitas.infrastructure.network.SubmitNpcMarriageProposalPayload;
import com.seaquake6324.civitas.infrastructure.network.SubmitNpcReproductionPayload;
import com.seaquake6324.civitas.infrastructure.network.SubmitGuardAssignmentPayload;
import com.seaquake6324.civitas.infrastructure.network.RequestCitizenInfoPayload;
import com.seaquake6324.civitas.domain.security.GuardShift;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.neoforged.neoforge.client.network.ClientPacketDistributor;

/** Close-range resident card with an explicit two-step, in-screen player consent flow. */
public final class CitizenInfoScreen extends Screen {
    private static final int WIDTH=350,HEIGHT=310,REFRESH_TICKS=20;private OpenCitizenInfoPayload data;private int left,top,noticeTicks,routeIndex,refreshTicks;private boolean waiting,confirming,resolved,guardMode;private GuardShift guardShift=GuardShift.DAY;private Component notice=Component.empty();private int noticeColor=0xFFFF7777;private Button propose,confirm,cancel,reproduce,guard,route,shift,voluntary,force,guardCancel;
    public CitizenInfoScreen(OpenCitizenInfoPayload data){super(Component.translatable("civitas.citizen.title"));this.data=data;}
    public java.util.UUID citizenId(){return data.citizenId();}
    public void updateData(OpenCitizenInfoPayload fresh){if(!data.citizenId().equals(fresh.citizenId()))return;data=fresh;routeIndex=Math.min(routeIndex,Math.max(0,data.guardRoutes().size()-1));if(data.guardRoutes().isEmpty())guardMode=false;resolved=false;refreshButtons();}
    @Override public boolean isPauseScreen(){return false;}
    @Override protected void init(){left=(width-WIDTH)/2;top=(height-HEIGHT)/2;propose=addRenderableWidget(Button.builder(Component.translatable("civitas.marriage.propose"),b->showConfirmation()).bounds(left+35,top+194,130,22).build());reproduce=addRenderableWidget(Button.builder(Component.translatable("civitas.reproduction.propose"),b->submitReproduction()).bounds(left+185,top+194,130,22).build());guard=addRenderableWidget(Button.builder(Component.translatable("civitas.guard.open"),b->openGuard()).bounds(left+110,top+224,130,22).build());confirm=addRenderableWidget(Button.builder(Component.translatable("civitas.marriage.confirm"),b->submit()).bounds(left+55,top+194,108,22).build());cancel=addRenderableWidget(Button.builder(Component.translatable("civitas.marriage.cancel"),b->hideConfirmation()).bounds(left+187,top+194,108,22).build());route=addRenderableWidget(Button.builder(Component.empty(),b->cycleRoute()).bounds(left+18,top+190,200,22).build());shift=addRenderableWidget(Button.builder(Component.empty(),b->toggleShift()).bounds(left+228,top+190,104,22).build());voluntary=addRenderableWidget(Button.builder(Component.translatable("civitas.guard.appoint"),b->submitGuard(false)).bounds(left+18,top+222,98,22).build());force=addRenderableWidget(Button.builder(Component.translatable("civitas.guard.force"),b->submitGuard(true)).bounds(left+126,top+222,98,22).build());guardCancel=addRenderableWidget(Button.builder(Component.translatable("civitas.guard.cancel"),b->{guardMode=false;refreshButtons();}).bounds(left+234,top+222,98,22).build());refreshButtons();}
    private void showConfirmation(){if(waiting||!"available".equals(data.marriageAction()))return;confirming=true;refreshButtons();}
    private void hideConfirmation(){confirming=false;refreshButtons();}
    private void submit(){if(waiting)return;waiting=true;confirm.active=false;cancel.active=false;notice=Component.translatable("civitas.marriage.sending");noticeColor=0xFFD8C7A1;noticeTicks=100;ClientPacketDistributor.sendToServer(new SubmitNpcMarriageProposalPayload(data.citizenId(),data.citizenRevision()));}
    private void submitReproduction(){if(waiting||!"available".equals(data.reproductionAction()))return;waiting=true;notice=Component.translatable("civitas.reproduction.sending");noticeColor=0xFFD8C7A1;noticeTicks=100;ClientPacketDistributor.sendToServer(new SubmitNpcReproductionPayload(data.citizenId(),data.citizenRevision()));refreshButtons();}
    private void openGuard(){if(waiting||!"available".equals(data.guardAction())||data.guardRoutes().isEmpty())return;guardMode=true;confirming=false;refreshButtons();}
    private void cycleRoute(){if(data.guardRoutes().isEmpty())return;routeIndex=(routeIndex+1)%data.guardRoutes().size();refreshButtons();}
    private void toggleShift(){guardShift=guardShift==GuardShift.DAY?GuardShift.NIGHT:GuardShift.DAY;refreshButtons();}
    private void submitGuard(boolean forced){if(waiting||data.guardRoutes().isEmpty())return;var selected=data.guardRoutes().get(Math.min(routeIndex,data.guardRoutes().size()-1));waiting=true;notice=Component.translatable("civitas.guard.sending");noticeColor=0xFFD8C7A1;noticeTicks=100;ClientPacketDistributor.sendToServer(new SubmitGuardAssignmentPayload(data.citizenId(),data.citizenRevision(),selected.id(),selected.revision(),guardShift,forced));refreshButtons();}
    private void refreshButtons(){boolean normal=!guardMode;boolean available="available".equals(data.marriageAction());propose.visible=normal&&!confirming;propose.active=available&&!waiting&&!resolved;reproduce.visible=normal&&!confirming;reproduce.active="available".equals(data.reproductionAction())&&!waiting&&!resolved;guard.visible=normal&&!confirming;guard.active="available".equals(data.guardAction())&&!waiting&&!resolved&&!data.guardRoutes().isEmpty();confirm.visible=normal&&confirming;cancel.visible=normal&&confirming;confirm.active=confirming&&!waiting&&!resolved;cancel.active=confirming&&!waiting&&!resolved;route.visible=shift.visible=voluntary.visible=force.visible=guardCancel.visible=guardMode;if(guardMode){var selected=data.guardRoutes().get(Math.min(routeIndex,data.guardRoutes().size()-1));route.setMessage(Component.translatable("civitas.guard.route",routeIndex+1,selected.nodes()));shift.setMessage(Component.translatable("civitas.guard.shift."+guardShift.name().toLowerCase(java.util.Locale.ROOT)));route.active=shift.active=voluntary.active=force.active=guardCancel.active=!waiting&&!resolved;}}
    public void handleMarriageResult(boolean success,String key){waiting=false;confirming=false;resolved=true;notice=Component.translatable(key);noticeColor=success?0xFF9ED6B0:0xFFFF7777;noticeTicks=120;refreshButtons();}
    public void handleReproductionResult(boolean success,String key){waiting=false;notice=Component.translatable(key);noticeColor=success?0xFF9ED6B0:0xFFFF7777;noticeTicks=120;refreshButtons();}
    public void handleGuardResult(boolean success,String key){waiting=false;notice=Component.translatable(key);noticeColor=success?0xFF9ED6B0:0xFFFF7777;noticeTicks=140;if(success){resolved=true;guardMode=false;}refreshButtons();}
    @Override public void tick(){super.tick();if(noticeTicks>0)noticeTicks--;if(++refreshTicks>=REFRESH_TICKS){refreshTicks=0;ClientPacketDistributor.sendToServer(new RequestCitizenInfoPayload(data.citizenId()));}}
    @Override public void extractRenderState(GuiGraphicsExtractor g,int mouseX,int mouseY,float partialTick){CivitasGuiTextures.stoneCityPanel(g,left,top,WIDTH,HEIGHT);g.fill(left,top,left+4,top+HEIGHT,0xFF9C8068);g.centeredText(font,Component.literal(data.displayName()),width/2,top+17,0xFFEADCC1);int x=left+24,y=top+43,line=15;row(g,x,y,Component.translatable("civitas.citizen.identity",tr("race",data.race()),tr("gender",data.gender())));y+=line;row(g,x,y,Component.translatable("civitas.citizen.age",tr("age",data.ageStage()),data.ageYears()));y+=line;row(g,x,y,Component.translatable("civitas.citizen.health",data.health()));y+=line;row(g,x,y,Component.translatable("civitas.citizen.physical",percent(data.bodyScale()),Math.round(data.maximumHealth()),percent(data.movementSpeed()/0.1F),percent(data.attackDamage())));y+=line;row(g,x,y,Component.translatable("civitas.citizen.profession",data.profession().isBlank()?Component.translatable("civitas.citizen.none"):Component.literal(data.profession())));y+=line;row(g,x,y,Component.translatable("civitas.citizen.residence",Component.translatable("civitas.citizen.residence."+data.residenceStatus())));y+=line;row(g,x,y,Component.translatable("civitas.citizen.needs",data.food(),data.safety(),data.rest(),data.social()));y+=line;row(g,x,y,Component.translatable("civitas.citizen.state",tr("state",data.runtimeState())));if(guardMode){g.centeredText(font,Component.translatable("civitas.guard.equipment",data.basicWeapon()?Component.translatable("civitas.guard.yes"):Component.translatable("civitas.guard.no"),data.armorPieces(),data.shield()?Component.translatable("civitas.guard.yes"):Component.translatable("civitas.guard.no")),width/2,top+160,0xFFD8C7A1);float score=guardShift==GuardShift.DAY?data.dayWillingness():data.nightWillingness();g.centeredText(font,Component.translatable("civitas.guard.willingness",Math.round(score)),width/2,top+174,0xFFD8C7A1);}else if(confirming)g.centeredText(font,Component.translatable("civitas.marriage.confirm_prompt",data.displayName()),width/2,top+174,0xFFEADCC1);else if(!"available".equals(data.guardAction()))g.centeredText(font,Component.translatable("civitas.guard.state."+data.guardAction()),width/2,top+254,0xFFC8B99E);if(noticeTicks>0)g.centeredText(font,notice,width/2,top+286,noticeColor);super.extractRenderState(g,mouseX,mouseY,partialTick);}
    private void row(GuiGraphicsExtractor g,int x,int y,Component text){g.text(font,text,x,y,0xFFD8C7A1,false);}private static int percent(float ratio){return Math.round(ratio*100F);}private static Component tr(String group,String value){return Component.translatable("civitas.citizen."+group+"."+value.toLowerCase(java.util.Locale.ROOT));}
}
