package com.seaquake6324.civitas.presentation.screen;
import com.seaquake6324.civitas.infrastructure.network.*;import com.seaquake6324.civitas.infrastructure.population.ReproductionInteractionManager;import net.minecraft.client.gui.GuiGraphicsExtractor;import net.minecraft.client.gui.components.Button;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;import net.neoforged.neoforge.client.network.ClientPacketDistributor;
/** Nearby-player family screen with independent marriage and reproduction consent. */
public final class PlayerMarriageScreen extends Screen{private static final int WIDTH=320,HEIGHT=210;private final OpenPlayerMarriagePayload data;private int left,top,noticeTicks;private Component notice=Component.empty();private int noticeColor=0xFFFF7777;private boolean waiting;
 @Override public boolean isPauseScreen(){return false;}
 public PlayerMarriageScreen(OpenPlayerMarriagePayload data){super(Component.translatable("civitas.marriage.player_title"));this.data=data;}
 @Override protected void init(){left=(width-WIDTH)/2;top=(height-HEIGHT)/2;String marriage=data.action();addRenderableWidget(Button.builder(Component.translatable("accept".equals(marriage)?"civitas.marriage.accept":"civitas.marriage.propose"),b->marriage("accept".equals(marriage)?SubmitPlayerMarriageActionPayload.Action.ACCEPT:SubmitPlayerMarriageActionPayload.Action.PROPOSE)).bounds(left+30,top+70,125,22).build()).active="accept".equals(marriage)||"propose".equals(marriage);if("accept".equals(marriage))addRenderableWidget(Button.builder(Component.translatable("civitas.marriage.decline"),b->marriage(SubmitPlayerMarriageActionPayload.Action.DECLINE)).bounds(left+165,top+70,125,22).build());String reproduction=data.reproductionAction();addRenderableWidget(Button.builder(Component.translatable("accept".equals(reproduction)?"civitas.reproduction.accept":"civitas.reproduction.propose"),b->reproduction("accept".equals(reproduction)?ReproductionInteractionManager.Action.ACCEPT:ReproductionInteractionManager.Action.PROPOSE)).bounds(left+30,top+132,125,22).build()).active="accept".equals(reproduction)||"propose".equals(reproduction);if("accept".equals(reproduction))addRenderableWidget(Button.builder(Component.translatable("civitas.reproduction.decline"),b->reproduction(ReproductionInteractionManager.Action.DECLINE)).bounds(left+165,top+132,125,22).build());}
 private void marriage(SubmitPlayerMarriageActionPayload.Action action){if(waiting)return;waiting=true;ClientPacketDistributor.sendToServer(new SubmitPlayerMarriageActionPayload(data.targetId(),action,data.proposalId(),data.proposalRevision()));}
 private void reproduction(ReproductionInteractionManager.Action action){if(waiting)return;waiting=true;ClientPacketDistributor.sendToServer(new SubmitPlayerReproductionPayload(data.targetId(),action,data.reproductionConsentId(),data.reproductionConsentRevision()));}
 public void handleResult(boolean success,String key){waiting=false;notice=Component.translatable(key);noticeColor=success?0xFF9ED6B0:0xFFFF7777;noticeTicks=120;}
 @Override public void tick(){super.tick();if(noticeTicks>0)noticeTicks--;}
 @Override public void extractRenderState(GuiGraphicsExtractor g,int mouseX,int mouseY,float partialTick){CivitasGuiTextures.stoneCityPanel(g,left,top,WIDTH,HEIGHT);g.centeredText(font,title,width/2,top+16,0xFFEADCC1);g.centeredText(font,Component.literal(data.targetName()),width/2,top+38,0xFFD8C7A1);g.text(font,Component.translatable("civitas.marriage.section"),left+30,top+56,0xFFEADCC1,false);g.text(font,Component.translatable("civitas.reproduction.section"),left+30,top+118,0xFFEADCC1,false);g.centeredText(font,Component.translatable("civitas.reproduction.state."+data.reproductionAction()),width/2,top+164,0xFFC8B99E);if(noticeTicks>0)g.centeredText(font,notice,width/2,top+187,noticeColor);super.extractRenderState(g,mouseX,mouseY,partialTick);}}
