package com.seaquake6324.civitas.infrastructure.territory;

import com.seaquake6324.civitas.domain.City;import com.seaquake6324.civitas.domain.ChunkCoordinate;import com.seaquake6324.civitas.domain.civilization.CivilizationLayer;import com.seaquake6324.civitas.domain.territory.*;import com.seaquake6324.civitas.infrastructure.civilization.CivilityDirtyQueue;import com.seaquake6324.civitas.infrastructure.civilization.CivilityScanScheduler;import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;import com.seaquake6324.civitas.infrastructure.network.CityMapNetworkSync;import com.seaquake6324.civitas.infrastructure.persistence.*;import java.util.*;import net.minecraft.network.chat.Component;import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerLevel;import net.minecraft.server.level.ServerPlayer;

/** Bounded online-tick lifecycle processing; wall time is consulted only for the offline grace. */
public final class TerritoryLifecycleManager{
 private static final int INTERVAL=200,WORK_BUDGET=16;private static int cursor;private static final Set<UUID> RETRACTED_THIS_CYCLE=new HashSet<>();
 public static void tick(MinecraftServer server){long gameTime=server.overworld().getGameTime();if(gameTime%INTERVAL!=0)return;RETRACTED_THIS_CYCLE.clear();CitySavedData cities=CitySavedData.get(server);long wall=System.currentTimeMillis();List<Work> work=new ArrayList<>();for(City original:List.copyOf(cities.cities())){City city=refreshPresence(server,original,wall,cities);boolean grace=offlineGrace(server,city,wall);for(long chunk:city.territory())work.add(new Work(city.id(),chunk,grace));}if(work.isEmpty())return;int count=Math.min(WORK_BUDGET,work.size());for(int i=0;i<count;i++)process(server,cities,work.get(Math.floorMod(cursor+i,work.size())),gameTime);cursor=Math.floorMod(cursor+count,work.size());}
 private static City refreshPresence(MinecraftServer server,City city,long wall,CitySavedData repo){City observed=city;boolean online=server.getPlayerList().getPlayers().stream().anyMatch(p->observed.isMember(p.getUUID()));if(online&&(wall-city.lastMemberOnlineEpochMillis()>60000)){city=city.withLastMemberOnline(wall);repo.add(city);}else if(!online&&city.lastMemberOnlineEpochMillis()==0){city=city.withLastMemberOnline(wall);repo.add(city);}return city;}
 private static boolean offlineGrace(MinecraftServer server,City city,long wall){boolean online=server.getPlayerList().getPlayers().stream().anyMatch(p->city.isMember(p.getUUID()));return !online&&wall-city.lastMemberOnlineEpochMillis()<CivitasConfig.OFFLINE_GRACE_SECONDS.get()*1000L;}
 private static void process(MinecraftServer server,CitySavedData repo,Work work,long now){City city=repo.byId(work.cityId).orElse(null);if(city==null||!city.territory().contains(work.chunk))return;TerritoryChunkState state=city.territoryStates().get(work.chunk);if(state==null)return;if(work.grace){repo.add(city.withTerritoryState(work.chunk,state.pauseTimers(INTERVAL)));return;}ServerLevel level=level(server,city.dimension());if(level==null)return;boolean border=!TerritoryTopology.borderEdges(city.territory(),work.chunk).isEmpty();CivilizationSavedData civilization=CivilizationSavedData.get(server);var surface=civilization.get(city.dimension(),work.chunk,CivilizationLayer.SURFACE);var underground=civilization.get(city.dimension(),work.chunk,CivilizationLayer.UNDERGROUND);double civility=Math.max(surface.civility(),underground.civility()),target=Math.max(surface.targetCivility(),underground.targetCivility()),activity=Math.max(surface.activity(),underground.activity());long lastActivity=Math.max(surface.activitySummary().lastActivityTime(),underground.activitySummary().lastActivityTime());boolean validActivity=lastActivity>0&&now-lastActivity<=CivitasConfig.ACTIVITY_WINDOW_TICKS.get();boolean eventPause=ThreatSavedData.get(server).edgesAt(city.id(),work.chunk).stream().anyMatch(e->e.getValue().phase()==ThreatSavedData.Phase.WARNING||e.getValue().phase()==ThreatSavedData.Phase.WAVE||e.getValue().phase()==ThreatSavedData.Phase.COOLDOWN);
  double factor=state.lastDefenseResult()==TerritoryChunkState.DefenseResult.FAILURE?CivitasConfig.FAILED_DEFENSE_NEGLECT_MULTIPLIER.get():1;var rules=new NeglectRules.Settings(CivitasConfig.NEGLECT_CIVILITY_MINIMUM.get(),CivitasConfig.NEGLECT_ACTIVITY_MINIMUM.get(),(long)(CivitasConfig.NEGLECT_WARNING_TICKS.get()*factor),(long)(CivitasConfig.NEGLECT_ABANDONED_TICKS.get()*factor),(long)(CivitasConfig.NEGLECT_RETRACTABLE_TICKS.get()*factor),CivitasConfig.NEGLECT_RECOVERY_TICKS.get());var input=new NeglectRules.Input(now,civility,target,activity,border,work.chunk==city.coreChunk(),city.heartland().contains(work.chunk),eventPause,validActivity);var result=NeglectRules.evaluate(state,input,rules);if(!result.state().equals(state)){city=city.withTerritoryState(work.chunk,result.state());repo.add(city);}if(result.state().neglectStage()==NeglectStage.RETRACTABLE&&RETRACTED_THIS_CYCLE.add(city.id()))retractOne(server,level,repo,city,civilization);
 }
private static void retractOne(MinecraftServer server,ServerLevel level,CitySavedData repo,City city,CivilizationSavedData civilization){Map<Long,TerritoryRetraction.Health> health=new HashMap<>();for(long chunk:city.territory()){var s=civilization.get(city.dimension(),chunk,CivilizationLayer.SURFACE);var u=civilization.get(city.dimension(),chunk,CivilizationLayer.UNDERGROUND);health.put(chunk,new TerritoryRetraction.Health(Math.max(s.civility(),u.civility()),Math.max(s.activity(),u.activity())));}var selected=TerritoryRetraction.select(city,health);if(selected.isEmpty())return;long chunk=selected.getAsLong();City updated=city.retract(chunk);repo.add(updated);civilization.removeChunk(city.dimension(),chunk);ThreatSavedData.get(server).markPatrolRoutesOutsideTerritoryStale(city.id(),updated.territory());CityMapNetworkSync.broadcastUpsert(server,updated);ChunkCoordinate c=ChunkCoordinate.unpack(chunk);CivilityScanScheduler.markDirty(level,c.x(),c.z(),CivilityDirtyQueue.Reason.BORDER_CHANGE);for(var d:TerritoryTopology.Direction.values()){ChunkCoordinate n=ChunkCoordinate.unpack(TerritoryTopology.adjacent(chunk,d));CivilityScanScheduler.markDirty(level,n.x(),n.z(),CivilityDirtyQueue.Reason.BORDER_CHANGE);}for(ServerPlayer player:server.getPlayerList().getPlayers())if(city.isMember(player.getUUID()))player.sendSystemMessage(Component.translatable("civitas.neglect.retracted",c.x(),c.z()),true);}
 private static ServerLevel level(MinecraftServer server,String dimension){for(ServerLevel level:server.getAllLevels())if(level.dimension().identifier().toString().equals(dimension))return level;return null;}
 public static Snapshot snapshot(MinecraftServer server,UUID cityId,long chunk){City city=CitySavedData.get(server).byId(cityId).orElse(null);if(city==null)return null;TerritoryChunkState state=city.territoryStates().get(chunk);if(state==null)return null;long now=server.overworld().getGameTime();long remaining=state.recoveryStartedAt()==0?0:Math.max(0,CivitasConfig.NEGLECT_RECOVERY_TICKS.get()-(now-state.recoveryStartedAt()));return new Snapshot(state,remaining,TerritoryTopology.borderEdges(city.territory(),chunk).size());}
 public record Snapshot(TerritoryChunkState state,long recoveryRemaining,int externalEdges){}
 private record Work(UUID cityId,long chunk,boolean grace){}
 private TerritoryLifecycleManager(){}
}
