package com.seaquake6324.civitas.application;

import static org.junit.jupiter.api.Assertions.*;
import com.seaquake6324.civitas.domain.population.*;
import com.seaquake6324.civitas.infrastructure.persistence.PopulationSavedData;
import java.util.*;
import org.junit.jupiter.api.Test;

class MarriageServiceTest {
    private static final MarriageEligibilityRules.Settings SETTINGS=new MarriageEligibilityRules.Settings(60);
    private final MarriageService service=new MarriageService();

    @Test void playerPairRequiresBothRealPlayerConfirmations(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID();FamilyMemberRef a=FamilyMemberRef.player(UUID.randomUUID()),b=FamilyMemberRef.player(UUID.randomUUID());var proposed=service.propose(data,UUID.randomUUID(),UUID.randomUUID(),participant(a,city,true,100,0),participant(b,city,true,100,0),SETTINGS,a,10,200,64);assertTrue(proposed.success());assertEquals(MarriageProposal.Status.PENDING,proposed.proposal().status());assertTrue(proposed.proposal().proposerConfirmed());assertFalse(proposed.proposal().targetConfirmed());UUID household=UUID.randomUUID();var confirmed=service.confirm(data,proposed.proposal().id(),b,proposed.proposal().revision(),household,20,participant(a,city,true,100,0),participant(b,city,true,100,0),SETTINGS);assertTrue(confirmed.success());assertEquals(MarriageProposal.Status.ACCEPTED,confirmed.proposal().status());assertEquals(Set.of(a,b),data.household(household).orElseThrow().partners());}

    @Test void playerNpcAndNpcPairUseNpcWillingnessAndAtomicallyLinkCitizens(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID();CitizenRecord npc=citizen(city,75);data.putCitizen(npc);FamilyMemberRef player=FamilyMemberRef.player(UUID.randomUUID()),npcRef=FamilyMemberRef.citizen(npc.id());UUID firstHousehold=UUID.randomUUID();var first=service.propose(data,UUID.randomUUID(),firstHousehold,participant(player,city,true,100,0),participant(npcRef,city,true,75,npc.revision()),SETTINGS,player,10,200,64);assertTrue(first.success());assertEquals(MarriageProposal.Status.ACCEPTED,first.proposal().status());assertEquals(firstHousehold,data.citizen(npc.id()).orElseThrow().householdId());PopulationSavedData secondData=new PopulationSavedData();CitizenRecord one=citizen(city,80),two=citizen(city,90);secondData.putCitizen(one);secondData.putCitizen(two);var autonomous=service.propose(secondData,UUID.randomUUID(),UUID.randomUUID(),participant(FamilyMemberRef.citizen(one.id()),city,true,80,one.revision()),participant(FamilyMemberRef.citizen(two.id()),city,true,90,two.revision()),SETTINGS,null,10,200,64);assertTrue(autonomous.success());assertNotNull(autonomous.household());}

    @Test void rejectsForgedAutonomyLowWillingnessAndStaleCitizenRevisionWithoutPartialWrites(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID();FamilyMemberRef a=FamilyMemberRef.player(UUID.randomUUID()),b=FamilyMemberRef.player(UUID.randomUUID());var forged=service.propose(data,UUID.randomUUID(),UUID.randomUUID(),participant(a,city,true,100,0),participant(b,city,true,100,0),SETTINGS,null,10,200,64);assertEquals(MarriageService.Failure.INVALID_ACTOR,forged.failure());CitizenRecord npc=citizen(city,30);data.putCitizen(npc);var low=service.propose(data,UUID.randomUUID(),UUID.randomUUID(),participant(a,city,true,100,0),participant(FamilyMemberRef.citizen(npc.id()),city,true,30,npc.revision()),SETTINGS,a,10,200,64);assertEquals(MarriageService.Failure.INELIGIBLE,low.failure());CitizenRecord willing=citizen(city,80);data.putCitizen(willing);var stale=service.propose(data,UUID.randomUUID(),UUID.randomUUID(),participant(a,city,true,100,0),participant(FamilyMemberRef.citizen(willing.id()),city,true,80,willing.revision()+1),SETTINGS,a,10,200,64);assertEquals(MarriageService.Failure.REVALIDATION_FAILED,stale.failure());assertEquals(0,data.householdCount());assertEquals(0,data.proposalCount());}

    @Test void enforcesActiveProposalCapacityExpiryAndTerminalReplay(){PopulationSavedData data=new PopulationSavedData();UUID city=UUID.randomUUID();FamilyMemberRef a=FamilyMemberRef.player(UUID.randomUUID()),b=FamilyMemberRef.player(UUID.randomUUID()),c=FamilyMemberRef.player(UUID.randomUUID());var pending=service.propose(data,UUID.randomUUID(),UUID.randomUUID(),participant(a,city,true,100,0),participant(b,city,true,100,0),SETTINGS,a,10,20,1);assertTrue(pending.success());assertEquals(MarriageService.Failure.ACTIVE_PROPOSAL,service.propose(data,UUID.randomUUID(),UUID.randomUUID(),participant(a,city,true,100,0),participant(c,city,true,100,0),SETTINGS,a,11,30,1).failure());var expired=service.confirm(data,pending.proposal().id(),b,pending.proposal().revision(),UUID.randomUUID(),20,participant(a,city,true,100,0),participant(b,city,true,100,0),SETTINGS);assertEquals(MarriageService.Failure.EXPIRED,expired.failure());assertEquals(MarriageService.Failure.TERMINAL_STATUS,service.decline(data,pending.proposal().id(),b,expired.proposal().revision(),21).failure());assertEquals(MarriageService.Failure.CAPACITY,service.propose(data,UUID.randomUUID(),UUID.randomUUID(),participant(b,city,true,100,0),participant(c,city,true,100,0),SETTINGS,b,21,40,1).failure());}

    private static MarriageEligibilityRules.Participant participant(FamilyMemberRef member,UUID city,boolean adult,double willingness,long revision){return new MarriageEligibilityRules.Participant(member,city,true,adult,false,willingness,revision);}
    private static CitizenRecord citizen(UUID city,double willingness){return new CitizenRecord(UUID.randomUUID(),"Mira","North",CitizenRace.HUMAN,"human_0",Gender.FEMALE,432000,0,city,null,null,null,"",100,CitizenNeeds.neutral(),Map.of(),Set.of(),willingness,0,CitizenRuntimeState.VIRTUAL,0,1);}
}
