package com.seaquake6324.civitas.application;
import static org.junit.jupiter.api.Assertions.*;import com.seaquake6324.civitas.application.port.PatrolRouteRepository;import com.seaquake6324.civitas.domain.*;import com.seaquake6324.civitas.domain.building.*;import com.seaquake6324.civitas.domain.civilization.FacilityCategory;import com.seaquake6324.civitas.domain.security.PatrolRoute;import java.util.*;import org.junit.jupiter.api.Test;
class RegisterPatrolRouteServiceTest{
 @Test void founderRegistersBoundedWorldValidatedRoute(){Fixture f=new Fixture();var result=new RegisterPatrolRouteService().register(f.repo,f.request(f.founder,new RegisterPatrolRouteService.Evidence(3,8,true,true,true,true,false,25)));assertTrue(result.success());assertEquals(PatrolRoute.Status.VALID,result.route().status());assertEquals(f.post.id(),result.route().guardPostId());assertEquals(1,f.repo.routes.size());}
 @Test void lordWithoutFoundingMilitaryGrantCannotRegister(){Fixture f=new Fixture();var result=new RegisterPatrolRouteService().register(f.repo,f.request(f.lord,new RegisterPatrolRouteService.Evidence(3,8,true,true,true,true,false,25)));assertEquals(RegisterPatrolRouteService.Failure.NOT_COMMANDER,result.failure());}
 @Test void incompleteOrUnsafeEvidenceNeverCreatesCoverageAuthority(){Fixture f=new Fixture();for(var evidence:List.of(new RegisterPatrolRouteService.Evidence(2,8,true,true,true,true,false,1),new RegisterPatrolRouteService.Evidence(3,8,true,true,true,true,true,1),new RegisterPatrolRouteService.Evidence(3,8,false,true,true,true,false,1),new RegisterPatrolRouteService.Evidence(3,8,true,true,false,true,false,1),new RegisterPatrolRouteService.Evidence(3,8,true,true,true,false,false,1))){assertFalse(new RegisterPatrolRouteService().register(f.repo,f.request(f.founder,evidence)).success());assertTrue(f.repo.routes.isEmpty());}}
 private static final class Fixture{final UUID founder=UUID.randomUUID(),lord=UUID.randomUUID();final City city=new City(UUID.randomUUID(),"Test",0,"minecraft:overworld",0,ChunkCoordinate.pack(0,0),1,founder,lord,Set.of(founder,lord),Set.of(ChunkCoordinate.pack(0,0)));final BuildingRecord post=new BuildingRecord(UUID.randomUUID(),city.id(),city.dimension(),BuildingPurpose.GUARD_POST,10,11,Set.of(11L,12L),Map.of(FacilityCategory.PUBLIC,1),1,BuildingStatus.VALID,2,20,"");final Memory repo=new Memory();RegisterPatrolRouteService.Request request(UUID actor,RegisterPatrolRouteService.Evidence e){return new RegisterPatrolRouteService.Request(UUID.randomUUID(),city,actor,post,city.revision(),post.revision(),List.of(11L,12L,13L),30,8,e);}}
 private static final class Memory implements PatrolRouteRepository{final Map<UUID,PatrolRoute>routes=new HashMap<>();public Optional<PatrolRoute>patrolRoute(UUID id){return Optional.ofNullable(routes.get(id));}public boolean createPatrolRoute(PatrolRoute route,int cap){if(routes.size()>=cap||routes.containsKey(route.id()))return false;routes.put(route.id(),route);return true;}}
}
