package com.seaquake6324.civitas.application;
import static org.junit.jupiter.api.Assertions.*;import com.seaquake6324.civitas.application.port.PopulationRepository;import com.seaquake6324.civitas.domain.population.*;import java.util.*;import org.junit.jupiter.api.Test;
class TransitionCitizenRuntimeServiceTest{
 @Test void appliesOnlyLegalRevisionMatchedTransitions(){Repo repo=new Repo();CitizenRecord citizen=citizen();repo.putCitizen(citizen);var service=new TransitionCitizenRuntimeService();var prepared=service.transition(repo,citizen.id(),citizen.revision(),CitizenRuntimeState.PREWARMING);assertTrue(prepared.success());assertEquals(CitizenRuntimeState.PREWARMING,prepared.citizen().runtimeState());var stale=service.transition(repo,citizen.id(),citizen.revision(),CitizenRuntimeState.MATERIALIZED);assertEquals(TransitionCitizenRuntimeService.Failure.STALE_REVISION,stale.failure());var visible=service.transition(repo,citizen.id(),prepared.citizen().revision(),CitizenRuntimeState.MATERIALIZED);assertTrue(visible.success());}
 @Test void rejectsSkippingPrewarm(){Repo repo=new Repo();CitizenRecord citizen=citizen();repo.putCitizen(citizen);var result=new TransitionCitizenRuntimeService().transition(repo,citizen.id(),citizen.revision(),CitizenRuntimeState.MATERIALIZED);assertEquals(TransitionCitizenRuntimeService.Failure.INVALID_TRANSITION,result.failure());assertEquals(CitizenRuntimeState.VIRTUAL,repo.citizen(citizen.id()).orElseThrow().runtimeState());}
 @Test void lockCarriesExpiryAndRequiresCurrentRevision(){Repo repo=new Repo();CitizenRecord citizen=citizen();repo.putCitizen(citizen);var service=new TransitionCitizenRuntimeService();var pre=service.transition(repo,citizen.id(),1,CitizenRuntimeState.PREWARMING).citizen();var visible=service.transition(repo,citizen.id(),pre.revision(),CitizenRuntimeState.MATERIALIZED).citizen();var locked=service.lock(repo,citizen.id(),visible.revision(),500);assertTrue(locked.success());assertEquals(CitizenRuntimeState.LOCKED,locked.citizen().runtimeState());assertEquals(500,locked.citizen().runtimeLockUntilTick());assertEquals(TransitionCitizenRuntimeService.Failure.STALE_REVISION,service.lock(repo,citizen.id(),visible.revision(),600).failure());}
 @Test void repeatedEquivalentInteractionLockDoesNotInvalidateAnOpenScreen(){Repo repo=new Repo();CitizenRecord citizen=citizen();repo.putCitizen(citizen);var service=new TransitionCitizenRuntimeService();var pre=service.transition(repo,citizen.id(),1,CitizenRuntimeState.PREWARMING).citizen();var visible=service.transition(repo,citizen.id(),pre.revision(),CitizenRuntimeState.MATERIALIZED).citizen();var first=service.lock(repo,citizen.id(),visible.revision(),500).citizen();var repeated=service.lock(repo,citizen.id(),first.revision(),500).citizen();assertEquals(first.revision(),repeated.revision());assertSame(first,repeated);}
 private static CitizenRecord citizen(){return new CitizenRecord(UUID.randomUUID(),"Erik","Berg",CitizenRace.HUMAN,"human_0",Gender.MALE,0,0,UUID.randomUUID(),null,null,null,"",100,CitizenNeeds.neutral(),Map.of(),Set.of(),50,0,CitizenRuntimeState.VIRTUAL,0,1);}
 private static final class Repo implements PopulationRepository{private final Map<UUID,CitizenRecord>citizens=new HashMap<>();public Optional<PlayerCivitasProfile>profile(UUID id){return Optional.empty();}public void putProfile(PlayerCivitasProfile p){}public Optional<CitizenRecord>citizen(UUID id){return Optional.ofNullable(citizens.get(id));}public Collection<CitizenRecord>citizens(){return citizens.values();}public void putCitizen(CitizenRecord c){citizens.put(c.id(),c);}public Optional<Household>household(UUID id){return Optional.empty();}public Collection<Household>households(){return List.of();}public void putHousehold(Household h){}public boolean createHousehold(Household h,Map<UUID,Long>e){return false;}public Optional<Household>householdForPartner(FamilyMemberRef v){return Optional.empty();}public Optional<MarriageProposal>proposal(UUID id){return Optional.empty();}public Optional<MarriageProposal>activeProposalFor(FamilyMemberRef v){return Optional.empty();}public int proposalCount(){return 0;}public void putProposal(MarriageProposal v){}}
}
