package com.seaquake6324.civitas.application;
import com.seaquake6324.civitas.application.port.PatrolRouteRepository;import com.seaquake6324.civitas.domain.City;import com.seaquake6324.civitas.domain.building.*;import com.seaquake6324.civitas.domain.security.PatrolRoute;import java.util.*;
/** Revision-checked route registration. World traversal evidence is produced by the main-thread adapter. */
public final class RegisterPatrolRouteService{
 public Result register(PatrolRouteRepository repository,Request request){if(repository==null||request==null)return new Result(false,Failure.INVALID,null);City city=request.city();BuildingRecord post=request.guardPost();if(city.revision()!=request.expectedCityRevision())return new Result(false,Failure.STALE_CITY,null);if(!city.mayCommandMilitary(request.actor()))return new Result(false,Failure.NOT_COMMANDER,null);if(post==null||post.revision()!=request.expectedPostRevision())return new Result(false,Failure.STALE_POST,null);if(post.purpose()!=BuildingPurpose.GUARD_POST||post.status()!=BuildingStatus.VALID||!city.id().equals(post.cityId())||!city.dimension().equals(post.dimension()))return new Result(false,Failure.INVALID_POST,null);Evidence e=request.evidence();if(e==null||e.truncated()||e.nodesExamined()!=request.nodes().size())return new Result(false,Failure.INCOMPLETE_EVIDENCE,null);if(!e.allInsideTerritory())return new Result(false,Failure.OUTSIDE_TERRITORY,null);if(!e.startsAtPost())return new Result(false,Failure.NOT_AT_POST,null);if(!e.allStandable())return new Result(false,Failure.NOT_STANDABLE,null);if(!e.segmentsWithinLimit())return new Result(false,Failure.SEGMENT_TOO_LONG,null);PatrolRoute route;try{route=new PatrolRoute(request.routeId(),city.id(),city.dimension(),post.id(),request.nodes(),request.actor(),PatrolRoute.Status.VALID,request.now(),1,"");}catch(IllegalArgumentException ex){return new Result(false,Failure.INVALID,null);}return repository.createPatrolRoute(route,request.cityRouteCap())?new Result(true,null,route):new Result(false,Failure.CAP_OR_DUPLICATE,null);}
 public record Request(UUID routeId,City city,UUID actor,BuildingRecord guardPost,long expectedCityRevision,long expectedPostRevision,List<Long>nodes,long now,int cityRouteCap,Evidence evidence){public Request{nodes=nodes==null?List.of():List.copyOf(nodes);if(routeId==null||city==null||actor==null||now<0||cityRouteCap<1)throw new IllegalArgumentException("invalid patrol request");}}
 public record Evidence(int nodesExamined,int pathSamples,boolean allInsideTerritory,boolean startsAtPost,boolean allStandable,boolean segmentsWithinLimit,boolean truncated,long elapsedMicros){public Evidence{if(nodesExamined<0||pathSamples<0||elapsedMicros<0)throw new IllegalArgumentException("invalid patrol evidence");}}
 public enum Failure{INVALID,STALE_CITY,NOT_COMMANDER,STALE_POST,INVALID_POST,INCOMPLETE_EVIDENCE,OUTSIDE_TERRITORY,NOT_AT_POST,NOT_STANDABLE,SEGMENT_TOO_LONG,CAP_OR_DUPLICATE}
 public record Result(boolean success,Failure failure,PatrolRoute route){}
}
