package com.seaquake6324.civitas.application;
import com.seaquake6324.civitas.application.port.PopulationRepository;import com.seaquake6324.civitas.domain.population.CitizenRecord;import com.seaquake6324.civitas.domain.population.CitizenRuntimeState;import java.util.UUID;
/** Main-thread application boundary for revision-checked entity/virtual state changes. */
public final class TransitionCitizenRuntimeService{
 public Result transition(PopulationRepository repository,UUID citizenId,long expectedRevision,CitizenRuntimeState target){CitizenRecord current=repository.citizen(citizenId).orElse(null);if(current==null)return new Result(false,Failure.MISSING,null);if(current.revision()!=expectedRevision)return new Result(false,Failure.STALE_REVISION,current);if(!current.alive())return new Result(false,Failure.PERMANENTLY_DEAD,current);if(current.runtimeState()==target)return new Result(true,null,current);if(!allowed(current.runtimeState(),target))return new Result(false,Failure.INVALID_TRANSITION,current);CitizenRecord updated=current.withRuntimeState(target);repository.putCitizen(updated);return new Result(true,null,updated);}
 public Result lock(PopulationRepository repository,UUID citizenId,long expectedRevision,long until){CitizenRecord current=repository.citizen(citizenId).orElse(null);if(current==null)return new Result(false,Failure.MISSING,null);if(current.revision()!=expectedRevision)return new Result(false,Failure.STALE_REVISION,current);if(!current.alive())return new Result(false,Failure.PERMANENTLY_DEAD,current);if(current.runtimeState()!=CitizenRuntimeState.MATERIALIZED&&current.runtimeState()!=CitizenRuntimeState.LOCKED)return new Result(false,Failure.INVALID_TRANSITION,current);long target=Math.max(current.runtimeLockUntilTick(),until);if(current.runtimeState()==CitizenRuntimeState.LOCKED&&current.runtimeLockUntilTick()>=target)return new Result(true,null,current);CitizenRecord updated=current.withRuntimeLock(target);repository.putCitizen(updated);return new Result(true,null,updated);}
 private static boolean allowed(CitizenRuntimeState from,CitizenRuntimeState to){return switch(from){case VIRTUAL->to==CitizenRuntimeState.PREWARMING;case PREWARMING->to==CitizenRuntimeState.VIRTUAL||to==CitizenRuntimeState.MATERIALIZED;case MATERIALIZED->to==CitizenRuntimeState.VIRTUAL||to==CitizenRuntimeState.LOCKED;case LOCKED->to==CitizenRuntimeState.MATERIALIZED||to==CitizenRuntimeState.VIRTUAL;};}
 public enum Failure{MISSING,STALE_REVISION,INVALID_TRANSITION,PERMANENTLY_DEAD}
 public record Result(boolean success,Failure failure,CitizenRecord citizen){}
}
