package com.seaquake6324.civitas.infrastructure.network;
import com.seaquake6324.civitas.CivitasMod;import java.util.*;import net.minecraft.network.RegistryFriendlyByteBuf;import net.minecraft.network.codec.StreamCodec;import net.minecraft.network.protocol.common.custom.CustomPacketPayload;import net.minecraft.resources.Identifier;
/** Read-only, server-derived resident details for close-range interaction. */
public record OpenCitizenInfoPayload(UUID citizenId,String displayName,String race,String gender,String ageStage,int ageYears,int health,float bodyScale,float maximumHealth,float movementSpeed,float attackDamage,String profession,String runtimeState,int food,int safety,int rest,int social,String residenceStatus,String marriageAction,String reproductionAction,String guardAction,boolean basicWeapon,int armorPieces,boolean shield,float dayWillingness,float nightWillingness,List<GuardRouteOption>guardRoutes,long citizenRevision)implements CustomPacketPayload{
 public OpenCitizenInfoPayload{guardRoutes=List.copyOf(guardRoutes);}
 public record GuardRouteOption(UUID id,long revision,int nodes){}
 public static final Type<OpenCitizenInfoPayload>TYPE=new Type<>(Identifier.fromNamespaceAndPath(CivitasMod.MOD_ID,"open_citizen_info"));
 public static final StreamCodec<RegistryFriendlyByteBuf,OpenCitizenInfoPayload>STREAM_CODEC=CustomPacketPayload.codec(OpenCitizenInfoPayload::write,OpenCitizenInfoPayload::read);
 private static void write(OpenCitizenInfoPayload p,RegistryFriendlyByteBuf b){b.writeUUID(p.citizenId);b.writeUtf(p.displayName);b.writeUtf(p.race);b.writeUtf(p.gender);b.writeUtf(p.ageStage);b.writeVarInt(p.ageYears);b.writeVarInt(p.health);b.writeFloat(p.bodyScale);b.writeFloat(p.maximumHealth);b.writeFloat(p.movementSpeed);b.writeFloat(p.attackDamage);b.writeUtf(p.profession);b.writeUtf(p.runtimeState);b.writeVarInt(p.food);b.writeVarInt(p.safety);b.writeVarInt(p.rest);b.writeVarInt(p.social);b.writeUtf(p.residenceStatus);b.writeUtf(p.marriageAction);b.writeUtf(p.reproductionAction);b.writeUtf(p.guardAction);b.writeBoolean(p.basicWeapon);b.writeVarInt(p.armorPieces);b.writeBoolean(p.shield);b.writeFloat(p.dayWillingness);b.writeFloat(p.nightWillingness);b.writeVarInt(p.guardRoutes.size());for(GuardRouteOption route:p.guardRoutes){b.writeUUID(route.id);b.writeVarLong(route.revision);b.writeVarInt(route.nodes);}b.writeVarLong(p.citizenRevision);}
 private static OpenCitizenInfoPayload read(RegistryFriendlyByteBuf b){UUID id=b.readUUID();String name=b.readUtf(),race=b.readUtf(),gender=b.readUtf(),stage=b.readUtf();int years=b.readVarInt(),health=b.readVarInt();float scale=b.readFloat(),maxHealth=b.readFloat(),speed=b.readFloat(),damage=b.readFloat();String profession=b.readUtf(),state=b.readUtf();int food=b.readVarInt(),safety=b.readVarInt(),rest=b.readVarInt(),social=b.readVarInt();String residence=b.readUtf(),marriage=b.readUtf(),reproduction=b.readUtf(),guard=b.readUtf();boolean weapon=b.readBoolean();int armor=b.readVarInt();boolean shield=b.readBoolean();float day=b.readFloat(),night=b.readFloat();int count=b.readVarInt();if(count<0||count>256)throw new IllegalArgumentException("invalid guard route count");ArrayList<GuardRouteOption>routes=new ArrayList<>(count);for(int i=0;i<count;i++)routes.add(new GuardRouteOption(b.readUUID(),b.readVarLong(),b.readVarInt()));return new OpenCitizenInfoPayload(id,name,race,gender,stage,years,health,scale,maxHealth,speed,damage,profession,state,food,safety,rest,social,residence,marriage,reproduction,guard,weapon,armor,shield,day,night,routes,b.readVarLong());}
 @Override public Type<? extends CustomPacketPayload>type(){return TYPE;}
}
