package com.seaquake6324.civitas.infrastructure.population;

import com.seaquake6324.civitas.application.AdoptOrphanService;
import com.seaquake6324.civitas.domain.building.*;
import com.seaquake6324.civitas.domain.population.*;
import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;
import com.seaquake6324.civitas.infrastructure.persistence.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.server.MinecraftServer;

/** Main-thread, spatially evidenced and bounded autonomous NPC adoption matching. */
public final class AdoptionManager {
    private static final AdoptionRules RULES=new AdoptionRules();private static final AdoptOrphanService SERVICE=new AdoptOrphanService();
    private static MinecraftServer owner;private static long nextRun;private static UUID orphanCursor;
    private static long runs,orphansExamined,candidatesExamined,eligibleCandidates,adoptions,failedRolls,commitFailures,missingPosition,playerConsentDeferred;private static String lastReason="not_run";private static AdoptionRules.Result lastEvaluation;
    public static void tick(MinecraftServer server){if(owner!=server)reset(server);long now=server.overworld().getGameTime();if(now<nextRun)return;nextRun=now+CivitasConfig.ADOPTION_INTERVAL_TICKS.get();PopulationSavedData population=PopulationSavedData.get(server);BuildingSavedData buildings=BuildingSavedData.get(server);if(population.readOnly()||buildings.readOnly()){lastReason="dependency_read_only";return;}List<OrphanRecord>batch=batch(population,orphanCursor,CivitasConfig.ADOPTION_ORPHANS_PER_RUN.get());if(batch.isEmpty()){lastReason="no_orphans";return;}for(OrphanRecord orphan:batch){orphanCursor=orphan.childId();orphansExamined++;process(population,buildings,orphan,now);}runs++;}
    private static void process(PopulationSavedData population,BuildingSavedData buildings,OrphanRecord orphan,long now){CitizenRecord child=population.citizen(orphan.childId()).orElse(null);if(child==null||!child.alive()){lastReason="missing_or_dead_child";return;}if(PopulationAgingManager.rules().evaluate(child.ageTicks()).stage()!=AgeStage.CHILD){lastReason="not_child_stage";return;}Anchor childAnchor=anchor(orphan,child,population,buildings);if(childAnchor==null){missingPosition++;lastReason="child_position_missing";return;}List<Candidate>candidates=candidates(population,buildings,child,CivitasConfig.ADOPTION_CANDIDATES_PER_ORPHAN.get());Candidate best=null;AdoptionRules.Result bestResult=null;for(Candidate candidate:candidates){candidatesExamined++;if(!candidate.anchor.dimension.equals(childAnchor.dimension))continue;double distance=Math.sqrt(BlockPos.of(candidate.anchor.position).distSqr(BlockPos.of(childAnchor.position)));AdoptionRules.Result result=RULES.evaluate(candidate.rules,distance,CivitasConfig.ADOPTION_MAX_DISTANCE_BLOCKS.get());if(candidate.rules.includesPlayer()){playerConsentDeferred++;continue;}if(result.eligible()){eligibleCandidates++;if(bestResult==null||result.score()>bestResult.score()||result.score()==bestResult.score()&&candidate.household.id().compareTo(best.household.id())<0){best=candidate;bestResult=result;}}}lastEvaluation=bestResult;if(best==null){lastReason="no_local_candidate";return;}if(roll(orphan.childId(),best.household.id(),now)>=bestResult.score()/100.0){failedRolls++;lastReason="willingness_roll_failed";return;}Household origin=child.householdId()==null?null:population.household(child.householdId()).orElse(null);if(origin!=null&&origin.id().equals(best.household.id())){lastReason="same_origin_household";return;}long adoptiveExpected=population.household(best.household.id()).map(Household::revision).orElse(0L);Map<UUID,Long>revisions=new HashMap<>();for(FamilyMemberRef guardian:best.guardians)population.citizen(guardian.id()).ifPresent(c->revisions.put(c.id(),c.revision()));var result=SERVICE.adopt(population,new AdoptOrphanService.Request(child.id(),orphan.revision(),child.revision(),best.household,adoptiveExpected,origin==null?0:origin.revision(),revisions,CivitasConfig.HOUSEHOLD_CHILD_CAPACITY.get()));if(result.success()){adoptions++;lastReason="adopted";}else{commitFailures++;lastReason="commit_"+result.failure().name().toLowerCase(Locale.ROOT);}}
    private static List<Candidate> candidates(PopulationSavedData population,BuildingSavedData buildings,CitizenRecord child,int limit){ArrayList<Candidate>out=new ArrayList<>();Set<UUID>represented=new HashSet<>();int scanLimit=CivitasConfig.POPULATION_DASHBOARD_SCAN_LIMIT.get();for(Household h:population.householdPage(child.cityId(),scanLimit).records()){if(out.size()>=limit)break;Set<FamilyMemberRef>guardians=new HashSet<>(h.guardians().isEmpty()?h.partners():h.guardians());guardians.removeIf(g->g.kind()==FamilyMemberRef.Kind.CITIZEN&&(g.id().equals(child.id())||population.citizen(g.id()).filter(CitizenRecord::alive).isEmpty()));guardians.forEach(g->represented.add(g.id()));Candidate candidate=candidate(h,guardians,child.id(),population,buildings,true);if(candidate!=null)out.add(candidate);}if(out.size()<limit)for(CitizenRecord adult:population.citizenPage(child.cityId(),scanLimit).records()){if(out.size()>=limit)break;if(!adult.alive()||adult.householdId()!=null||adult.id().equals(child.id())||represented.contains(adult.id())||PopulationAgingManager.rules().evaluate(adult.ageTicks()).stage()==AgeStage.CHILD)continue;FamilyMemberRef guardian=FamilyMemberRef.citizen(adult.id());UUID id=UUID.nameUUIDFromBytes(("adoption-household:"+adult.id()).getBytes(StandardCharsets.UTF_8));Household h=new Household(id,child.cityId(),Set.of(),Set.of(),Set.of(guardian),Set.of(child.id()),adult.residenceId(),adult.needs().food(),adult.residenceId()==null?0:100,1);Candidate candidate=candidate(h,Set.of(guardian),child.id(),population,buildings,false);if(candidate!=null)out.add(candidate);}return out;}
    private static Candidate candidate(Household source,Set<FamilyMemberRef>guardians,UUID childId,PopulationSavedData population,BuildingSavedData buildings,boolean persisted){if(guardians.isEmpty())return null;boolean player=guardians.stream().anyMatch(g->g.kind()==FamilyMemberRef.Kind.PLAYER);UUID residence=source.residenceId();if(residence==null)for(FamilyMemberRef g:guardians)if(g.kind()==FamilyMemberRef.Kind.CITIZEN){residence=population.citizen(g.id()).map(CitizenRecord::residenceId).orElse(null);if(residence!=null)break;}BuildingRecord building=residence==null?null:buildings.byId(residence).filter(b->b.status()==BuildingStatus.VALID&&b.purpose()==BuildingPurpose.RESIDENCE).orElse(null);if(building==null)return null;double food=0,safety=0,willingness=0;int npc=0;for(FamilyMemberRef g:guardians)if(g.kind()==FamilyMemberRef.Kind.CITIZEN){CitizenRecord c=population.citizen(g.id()).orElse(null);if(c!=null){food+=c.needs().food();safety+=c.needs().safety();willingness+=c.settlementWillingness();npc++;}}if(npc>0){food/=npc;safety/=npc;willingness/=npc;}int maximum=CivitasConfig.HOUSEHOLD_CHILD_CAPACITY.get(),currentChildren=persisted?source.children().size():Math.max(0,source.children().size()-1),occupants=guardians.size()+currentChildren,remaining=Math.max(0,Math.min(maximum-currentChildren,building.capacity()-occupants));int physicalHousing=Math.max(0,Math.min(100,100*(building.capacity()-occupants)/Math.max(1,building.capacity()))),housing=persisted?Math.min(source.housingCoverage(),physicalHousing):physicalHousing;double scoredFood=persisted?(food+source.foodCoverage())/2:food;Household adoptive=persisted?source.addChild(childId,guardians):source;AdoptionRules.Candidate rules=new AdoptionRules.Candidate(guardians.size(),player,remaining,Math.max(1,maximum),housing,scoredFood,safety,willingness);return new Candidate(adoptive,Set.copyOf(guardians),new Anchor(building.dimension(),building.interior()),rules);}
    private static Anchor anchor(OrphanRecord orphan,CitizenRecord child,PopulationSavedData population,BuildingSavedData buildings){UUID residence=orphan.lastResidenceId()!=null?orphan.lastResidenceId():child.residenceId();if(residence!=null){BuildingRecord b=buildings.byId(residence).filter(x->x.status()==BuildingStatus.VALID).orElse(null);if(b!=null)return new Anchor(b.dimension(),b.interior());}return population.location(child.id()).map(l->new Anchor(l.dimension(),l.position())).orElse(null);}
    private static List<OrphanRecord>batch(PopulationSavedData data,UUID after,int limit){return data.orphanBatch(after,limit).records();}
    private static double roll(UUID child,UUID household,long now){return new SplittableRandom(child.getMostSignificantBits()^household.getLeastSignificantBits()^Long.rotateLeft(now,11)).nextDouble();}
    private static void reset(MinecraftServer server){owner=server;nextRun=0;orphanCursor=null;runs=orphansExamined=candidatesExamined=eligibleCandidates=adoptions=failedRolls=commitFailures=missingPosition=playerConsentDeferred=0;lastReason="server_reset";lastEvaluation=null;}
    public static Metrics metrics(){return new Metrics(runs,orphansExamined,candidatesExamined,eligibleCandidates,adoptions,failedRolls,commitFailures,missingPosition,playerConsentDeferred,lastReason,lastEvaluation);}
    public record Metrics(long runs,long orphansExamined,long candidatesExamined,long eligibleCandidates,long adoptions,long failedRolls,long commitFailures,long missingPosition,long playerConsentDeferred,String lastReason,AdoptionRules.Result lastEvaluation){}
    private record Anchor(String dimension,long position){}private record Candidate(Household household,Set<FamilyMemberRef>guardians,Anchor anchor,AdoptionRules.Candidate rules){}
    private AdoptionManager(){}
}
