package com.seaquake6324.civitas.infrastructure.population;
import com.seaquake6324.civitas.application.*;import com.seaquake6324.civitas.domain.population.*;import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;import com.seaquake6324.civitas.infrastructure.entity.CitizenEntity;import com.seaquake6324.civitas.infrastructure.entity.MaterializationLeaseManager;import com.seaquake6324.civitas.infrastructure.persistence.PopulationSavedData;import java.util.UUID;import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerLevel;
/** Main-thread adapter that commits death only for a currently marked formal invasion attacker. */
public final class CitizenCombatDeathManager{private static final KillCitizenService KILL=new KillCitizenService();private static final RecordPartnerDeathService PARTNER=new RecordPartnerDeathService();private static final ReconcileOrphansAfterParentDeathService ORPHANS=new ReconcileOrphansAfterParentDeathService();private static long attempts,deaths,rejected,partnerFailures,orphansCreated,orphanFailures,orphanTruncations;private static String lastReason="not_run";
 public static boolean kill(CitizenEntity entity,ServerLevel level,UUID invasionId){UUID id=entity.citizenId().orElse(null);if(id==null)return reject("missing_citizen");boolean killed=killRecord(level.getServer(),id,invasionId,level.getGameTime());if(killed){CitizenEquipmentDeathDropManager.retireSnapshot(level.getServer(),id);MaterializationLeaseManager.revoke(id);}return killed;}
 public static boolean killVirtual(MinecraftServer server,UUID citizenId,UUID invasionId,long now){boolean killed=killRecord(server,citizenId,invasionId,now);if(killed)CitizenMaterializationManager.discardPermanentDeath(server,citizenId);return killed;}
 private static boolean killRecord(MinecraftServer server,UUID id,UUID invasionId,long now){attempts++;if(invasionId==null)return reject("missing_invasion");PopulationSavedData data=PopulationSavedData.get(server);if(data.readOnly())return reject("read_only");CitizenRecord current=id==null?null:data.citizen(id).orElse(null);if(current==null||!current.alive())return reject("missing_citizen");var result=KILL.killFromInvasion(data,id,current.revision(),now);if(!result.success())return reject("kill_"+result.failure().name().toLowerCase(java.util.Locale.ROOT));deaths++;var history=PARTNER.record(data,result.citizen());if(!history.success()){partnerFailures++;lastReason="partner_"+history.failure().name().toLowerCase(java.util.Locale.ROOT);}var orphan=ORPHANS.reconcile(data,FamilyMemberRef.citizen(id),now,PopulationAgingManager.rules(),CivitasConfig.PARENTAGE_PER_DEATH.get());orphansCreated+=orphan.orphaned();orphanFailures+=orphan.failures();if(orphan.truncated())orphanTruncations++;lastReason="invasion_death:"+invasionId;return true;}
 private static boolean reject(String reason){rejected++;lastReason=reason;return false;}
 public static Metrics metrics(){return new Metrics(attempts,deaths,rejected,partnerFailures,orphansCreated,orphanFailures,orphanTruncations,lastReason);}public record Metrics(long attempts,long deaths,long rejected,long partnerFailures,long orphansCreated,long orphanFailures,long orphanTruncations,String lastReason){}private CitizenCombatDeathManager(){}}
