package com.seaquake6324.civitas.infrastructure.population;

import com.seaquake6324.civitas.application.CreateMigrationGroupService;
import com.seaquake6324.civitas.application.TransitionCitizenRuntimeService;
import com.seaquake6324.civitas.domain.City;
import com.seaquake6324.civitas.domain.building.*;
import com.seaquake6324.civitas.domain.civilization.CivilizationLayer;
import com.seaquake6324.civitas.domain.population.*;
import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;
import com.seaquake6324.civitas.infrastructure.entity.CitizenEntity;
import com.seaquake6324.civitas.infrastructure.entity.MaterializationLeaseManager;
import com.seaquake6324.civitas.infrastructure.persistence.*;
import com.seaquake6324.civitas.infrastructure.registry.CivitasEntities;
import com.seaquake6324.civitas.infrastructure.security.SecurityCellManager;
import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.EntitySpawnReason;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.levelgen.Heightmap;

/** Bounded main-thread world migration. Invisible applicants never advance along a route. */
public final class MigrationManager {
    private static final MigrationAttractionRules RULES=new MigrationAttractionRules();
    private static final CreateMigrationGroupService CREATE=new CreateMigrationGroupService();
    private static final TransitionCitizenRuntimeService TRANSITIONS=new TransitionCitizenRuntimeService();
    private static MinecraftServer owner;private static UUID cityCursor;private static long nextAppearance;
    private static long rolls,appeared,reusedFromPool,rollFailures,noLoadedOrigin,attractionEvidenceTruncations,attractionCitizensExamined,attractionHouseholdsExamined,attractionBuildingsExamined,attractionSecurityExamined,originChunksExamined,originScanTruncations,originColumnsExamined,groupsProcessed,spawned,arrived,expired,departed,positionUpdates,stale,totalMicros,maxMicros;private static String lastReason="not_run";private static AttractionEvidence lastAttraction;

    public static void tick(MinecraftServer server){if(owner!=server)reset(server);long started=System.nanoTime(),now=server.overworld().getGameTime();PopulationSavedData population=PopulationSavedData.get(server);CitySavedData cities=CitySavedData.get(server);if(population.readOnly()||cities.readOnly()||BuildingSavedData.get(server).readOnly()||CivilizationSavedData.get(server).readOnly()||ThreatSavedData.get(server).readOnly()){lastReason="dependency_read_only";return;}processGroups(server,population,cities,now);if(now>=nextAppearance){nextAppearance=now+CivitasConfig.MIGRATION_INTERVAL_TICKS.get();appearance(server,population,cities,now);}long micros=Math.max(0,(System.nanoTime()-started)/1_000);totalMicros+=micros;maxMicros=Math.max(maxMicros,micros);}

    private static void appearance(MinecraftServer server,PopulationSavedData population,CitySavedData cities,long now){var batch=cities.cityBatch(cityCursor,1);if(batch.cities().isEmpty()){lastReason="no_cities";return;}City city=batch.cities().getFirst();cityCursor=batch.wrapped()?null:batch.nextCursor();ServerLevel level=level(server,city.dimension());if(level==null){lastReason="dimension_missing";return;}AttractionEvidence evidence=inputs(server,city);lastAttraction=evidence;attractionCitizensExamined+=evidence.citizensExamined();attractionHouseholdsExamined+=evidence.householdsExamined();attractionBuildingsExamined+=evidence.buildingsExamined();attractionSecurityExamined+=evidence.securityExamined();if(evidence.truncated()){attractionEvidenceTruncations++;lastReason="attraction_evidence_truncated";return;}MigrationAttractionRules.Result attraction=RULES.evaluate(evidence.inputs());rolls++;if(roll(city.id(),now)>=attraction.appearanceChance()){rollFailures++;lastReason="attraction_roll_failed";return;}BlockPos origin=findOrigin(level,cities,city,now);if(origin==null){noLoadedOrigin++;lastReason="no_loaded_unclaimed_origin";return;}var pooled=population.regionalPool(city.dimension(),CivitasConfig.MIGRATION_ACTIVE_GROUP_CAP.get()).stream().findFirst().orElse(null);if(pooled!=null){MigrationGroupRecord active=pooled.reactivate(city.id(),origin.asLong(),city.corePosition(),now,attraction.score());if(population.updateMigration(active,pooled.revision())){reusedFromPool++;appeared++;lastReason="regional_pool_reactivated";}else{stale++;lastReason="pool_reactivation_stale";}return;}if(population.activeMigrationCount()>=CivitasConfig.MIGRATION_ACTIVE_GROUP_CAP.get()){lastReason="active_cap";return;}UUID groupId=UUID.nameUUIDFromBytes((city.id()+":migration:"+now).getBytes(java.nio.charset.StandardCharsets.UTF_8));AgeRules ages=PopulationAgingManager.rules();var result=CREATE.create(population,new CreateMigrationGroupService.Request(groupId,city.id(),city.dimension(),origin.asLong(),city.corePosition(),now,attraction.score(),CivitasConfig.MIGRATION_ACTIVE_GROUP_CAP.get(),CivitasConfig.MIGRATION_MAX_MEMBERS.get(),CivitasConfig.MIGRATION_COUPLE_CHANCE.get(),CivitasConfig.MIGRATION_CHILD_CHANCE.get(),CivitasConfig.MIGRATION_SECOND_CHILD_CHANCE.get(),ages.ticksPerYear(),ages.adolescentAt(),ages.youngAdultAt(),ages.elderAt(),PopulationAgingManager.lifespanRules()));if(result.success()){appeared++;lastReason="household_created";}else{stale++;lastReason="create_rejected";}}

    private static void processGroups(MinecraftServer server,PopulationSavedData population,CitySavedData cities,long now){var batch=population.migrationBatch(population.migrationCursor(),CivitasConfig.MIGRATION_GROUPS_PER_TICK.get());for(MigrationGroupRecord original:batch.records()){groupsProcessed++;MigrationGroupRecord group=refreshPositions(server,population,original);City city=cities.byId(group.targetCityId()).orElse(null);if(city==null&&group.state()!=MigrationGroupRecord.State.DEPARTING){MigrationGroupRecord leaving=group.departing();if(population.updateMigration(leaving,group.revision()))group=leaving;else{stale++;continue;}}
            if(group.state()==MigrationGroupRecord.State.APPLIED&&now>=group.decisionDeadline()){MigrationGroupRecord leaving=group.departing();if(population.updateMigration(leaving,group.revision())){group=leaving;expired++;lastReason="application_expired";}else{stale++;continue;}}
            for(UUID member:group.members())ensureVisible(server,population,group,member,now);
            if(group.state()==MigrationGroupRecord.State.APPROACHING&&allAt(server,group,group.targetPos(),CivitasConfig.MIGRATION_ARRIVAL_DISTANCE.get())){MigrationGroupRecord applied=group.applied(now+CivitasConfig.MIGRATION_DECISION_TICKS.get());if(population.updateMigration(applied,group.revision())){arrived++;lastReason="application_arrived";if(city!=null)notifyManagers(server,city,"civitas.migration.arrived");}else stale++;}
            else if(group.state()==MigrationGroupRecord.State.DEPARTING&&allAt(server,group,group.originPos(),3)){discardMembers(server,group);if(population.poolDepartedMigration(group,group.revision())){departed++;lastReason="entered_regional_pool";}else stale++;}
        }population.migrationCursor(batch.wrapped()?null:batch.nextCursor());}

    private static MigrationGroupRecord refreshPositions(MinecraftServer server,PopulationSavedData population,MigrationGroupRecord group){Map<UUID,Long>positions=new LinkedHashMap<>(group.memberPositions());boolean changed=false;for(UUID id:group.members()){var lease=MaterializationLeaseManager.lease(id).orElse(null);if(lease==null)continue;for(ServerLevel level:server.getAllLevels()){var entity=level.getEntity(lease.entityId());if(entity instanceof CitizenEntity citizen){long pos=citizen.blockPosition().asLong();if(positions.getOrDefault(id,Long.MIN_VALUE)!=pos){positions.put(id,pos);changed=true;}break;}}}if(!changed)return group;MigrationGroupRecord updated=group.withPositions(positions);if(population.updateMigration(updated,group.revision())){positionUpdates++;return updated;}stale++;return group;}

    private static void ensureVisible(MinecraftServer server,PopulationSavedData population,MigrationGroupRecord group,UUID member,long now){if(MaterializationLeaseManager.active(member))return;CitizenRecord citizen=population.citizen(member).orElse(null);if(citizen==null)return;ServerLevel level=level(server,group.dimension());BlockPos pos=BlockPos.of(group.memberPositions().get(member));if(level==null||!safe(level,pos)||level.players().stream().noneMatch(p->p.distanceToSqr(pos.getCenter())<=sq(CivitasConfig.MIGRATION_ACTIVATION_DISTANCE.get())))return;if(MaterializationLeaseManager.metrics().active()>=CivitasConfig.NPC_ENTITY_CAP.get()){lastReason="entity_cap";return;}if(citizen.runtimeState()==CitizenRuntimeState.MATERIALIZED||citizen.runtimeState()==CitizenRuntimeState.LOCKED){var reset=TRANSITIONS.transition(population,citizen.id(),citizen.revision(),CitizenRuntimeState.VIRTUAL);if(!reset.success()){stale++;return;}citizen=reset.citizen();}if(citizen.runtimeState()==CitizenRuntimeState.PREWARMING){var reset=TRANSITIONS.transition(population,citizen.id(),citizen.revision(),CitizenRuntimeState.VIRTUAL);if(!reset.success()){stale++;return;}citizen=reset.citizen();}var transition=TRANSITIONS.transition(population,citizen.id(),citizen.revision(),CitizenRuntimeState.MATERIALIZED);if(!transition.success()){stale++;return;}CitizenEntity entity=CivitasEntities.CITIZEN.get().create(level,EntitySpawnReason.EVENT);if(entity==null){TRANSITIONS.transition(population,transition.citizen().id(),transition.citizen().revision(),CitizenRuntimeState.VIRTUAL);return;}entity.snapTo(pos.getX()+.5,pos.getY(),pos.getZ()+.5,0,0);entity.bind(transition.citizen(),UUID.randomUUID(),now);if(entity.isRemoved()||!level.noCollision(entity)||!level.addFreshEntity(entity)){entity.discard();TRANSITIONS.transition(population,transition.citizen().id(),transition.citizen().revision(),CitizenRuntimeState.VIRTUAL);lastReason="spawn_rejected";return;}spawned++;}

    /** Called by the entity travel goal; returns true only for an active migrant. */
    public static boolean drive(CitizenEntity entity,ServerLevel level){UUID id=entity.citizenId().orElse(null);if(id==null)return false;MigrationGroupRecord group=PopulationSavedData.get(level.getServer()).migrationForMember(id).orElse(null);if(group==null||!group.dimension().equals(level.dimension().identifier().toString()))return false;if(group.state()==MigrationGroupRecord.State.APPLIED){entity.getNavigation().stop();return true;}BlockPos target=BlockPos.of(group.state()==MigrationGroupRecord.State.DEPARTING?group.originPos():group.targetPos());entity.getNavigation().moveTo(target.getX()+.5,target.getY(),target.getZ()+.5,1.0);return true;}
    /** Commits the last physical position before a migrant entity becomes virtual. */
    public static void capturePosition(CitizenEntity entity,ServerLevel level){UUID id=entity.citizenId().orElse(null);if(id==null)return;PopulationSavedData data=PopulationSavedData.get(level.getServer());MigrationGroupRecord group=data.migrationForMember(id).orElse(null);if(group==null||!group.dimension().equals(level.dimension().identifier().toString()))return;long position=entity.blockPosition().asLong();if(group.memberPositions().getOrDefault(id,Long.MIN_VALUE)==position)return;Map<UUID,Long>positions=new LinkedHashMap<>(group.memberPositions());positions.put(id,position);if(data.updateMigration(group.withPositions(positions),group.revision()))positionUpdates++;else stale++;}
    public static boolean isMigrant(UUID citizenId,MinecraftServer server){return PopulationSavedData.get(server).migrationForMember(citizenId).isPresent();}

    private static boolean allAt(MinecraftServer server,MigrationGroupRecord group,long target,int distance){BlockPos destination=BlockPos.of(target);double limit=sq(distance);for(UUID id:group.members()){var lease=MaterializationLeaseManager.lease(id).orElse(null);if(lease==null)return false;boolean found=false;for(ServerLevel level:server.getAllLevels()){var entity=level.getEntity(lease.entityId());if(entity instanceof CitizenEntity&&entity.distanceToSqr(destination.getCenter())<=limit){found=true;break;}}if(!found)return false;}return true;}
    private static void discardMembers(MinecraftServer server,MigrationGroupRecord group){for(UUID id:group.members()){var lease=MaterializationLeaseManager.lease(id).orElse(null);if(lease==null)continue;for(ServerLevel level:server.getAllLevels()){var entity=level.getEntity(lease.entityId());if(entity!=null){entity.discard();break;}}MaterializationLeaseManager.revoke(id);}}
    private static AttractionEvidence inputs(MinecraftServer server,City city){int limit=CivitasConfig.POPULATION_DASHBOARD_SCAN_LIMIT.get();PopulationSavedData population=PopulationSavedData.get(server);var citizenPage=population.citizenPage(city.id(),limit);var householdPage=population.householdPage(city.id(),limit);var buildingPage=BuildingSavedData.get(server).cityPage(city.id(),limit);var buildings=buildingPage.records().stream().filter(b->b.status()==BuildingStatus.VALID).toList();int capacity=buildings.stream().filter(b->b.purpose()==BuildingPurpose.RESIDENCE).mapToInt(BuildingRecord::capacity).sum(),residents=(int)citizenPage.records().stream().filter(CitizenRecord::alive).count();double housing=capacity==0?0:Math.max(0,Math.min(100,100.0*(capacity-residents)/capacity));double food=householdPage.records().isEmpty()?50:householdPage.records().stream().mapToInt(Household::foodCoverage).average().orElse(50);var civilization=CivilizationSavedData.get(server).get(city.dimension(),city.coreChunk(),CivilizationLayer.SURFACE);var security=SecurityCellManager.summary(server,city.id());double safety=security.assessedCells()==0?civilization.factors().safety():100-security.averageRisk();boolean truncated=citizenPage.truncated()||householdPage.truncated()||buildingPage.truncated()||security.truncated();return new AttractionEvidence(new MigrationAttractionRules.Inputs(housing,food,safety,civilization.civility(),civilization.activity()),citizenPage.examined(),householdPage.examined(),buildingPage.examined(),security.examined(),truncated);}
    static BlockPos findOrigin(ServerLevel level,CitySavedData cities,City city,long now){
        List<Long>edges=new ArrayList<>();Set<Long>unique=new HashSet<>();int examinedOwned=0,ownedCap=CivitasConfig.MIGRATION_EDGE_CHUNKS_SCAN_LIMIT.get();
        for(long owned:city.territory()){if(examinedOwned>=ownedCap)break;examinedOwned++;for(int[]d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){long adjacent=ChunkPos.pack(ChunkPos.getX(owned)+d[0],ChunkPos.getZ(owned)+d[1]);if(!city.territory().contains(adjacent)&&cities.cityAt(city.dimension(),adjacent).isEmpty()&&unique.add(adjacent))edges.add(adjacent);}}originChunksExamined+=examinedOwned;if(examinedOwned<city.territory().size())originScanTruncations++;
        if(edges.isEmpty())return null;Collections.shuffle(edges,new Random(city.id().getLeastSignificantBits()^now));int checked=0;
        for(long packed:edges){int chunkX=ChunkPos.getX(packed),chunkZ=ChunkPos.getZ(packed),minX=chunkX<<4,minZ=chunkZ<<4;for(int i=0;i<16&&checked<CivitasConfig.MIGRATION_SAFE_COLUMNS.get();i++,checked++){originColumnsExamined++;int x=minX+Math.floorMod(i*7+3,16),z=minZ+Math.floorMod(i*11+5,16);BlockPos probe=new BlockPos(x,64,z);if(!level.hasChunkAt(probe))continue;BlockPos pos=new BlockPos(x,level.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,x,z),z);if(safe(level,pos))return pos;}if(checked>=CivitasConfig.MIGRATION_SAFE_COLUMNS.get())break;}
        return null;
    }
    private static boolean safe(ServerLevel level,BlockPos pos){return level.isInWorldBounds(pos)&&level.hasChunkAt(pos)&&level.getBlockState(pos).getCollisionShape(level,pos).isEmpty()&&level.getBlockState(pos.above()).getCollisionShape(level,pos.above()).isEmpty()&&level.getBlockState(pos.below()).blocksMotion()&&level.getFluidState(pos).isEmpty()&&level.getFluidState(pos.above()).isEmpty();}
    private static ServerLevel level(MinecraftServer server,String dimension){for(ServerLevel level:server.getAllLevels())if(level.dimension().identifier().toString().equals(dimension))return level;return null;}
    private static double roll(UUID id,long now){return new SplittableRandom(id.getMostSignificantBits()^Long.rotateLeft(id.getLeastSignificantBits(),17)^now).nextDouble();}
    private static double sq(double value){return value*value;}
    private static void notifyManagers(MinecraftServer server,City city,String key){for(var player:server.getPlayerList().getPlayers())if(city.mayManage(player.getUUID()))player.sendSystemMessage(net.minecraft.network.chat.Component.translatable(key),true);}
    private static void reset(MinecraftServer server){owner=server;cityCursor=null;nextAppearance=0;lastAttraction=null;rolls=appeared=reusedFromPool=rollFailures=noLoadedOrigin=attractionEvidenceTruncations=attractionCitizensExamined=attractionHouseholdsExamined=attractionBuildingsExamined=attractionSecurityExamined=originChunksExamined=originScanTruncations=originColumnsExamined=groupsProcessed=spawned=arrived=expired=departed=positionUpdates=stale=totalMicros=maxMicros=0;lastReason="server_reset";}
    public static Metrics metrics(){return new Metrics(rolls,appeared,reusedFromPool,rollFailures,noLoadedOrigin,attractionEvidenceTruncations,attractionCitizensExamined,attractionHouseholdsExamined,attractionBuildingsExamined,attractionSecurityExamined,originChunksExamined,originScanTruncations,originColumnsExamined,groupsProcessed,spawned,arrived,expired,departed,positionUpdates,stale,totalMicros/Math.max(1,groupsProcessed),maxMicros,lastAttraction,lastReason);}
    public record AttractionEvidence(MigrationAttractionRules.Inputs inputs,int citizensExamined,int householdsExamined,int buildingsExamined,int securityExamined,boolean truncated){}
    public record Metrics(long rolls,long appeared,long reusedFromPool,long rollFailures,long noLoadedOrigin,long attractionEvidenceTruncations,long attractionCitizensExamined,long attractionHouseholdsExamined,long attractionBuildingsExamined,long attractionSecurityExamined,long originChunksExamined,long originScanTruncations,long originColumnsExamined,long groupsProcessed,long spawned,long arrived,long expired,long departed,long positionUpdates,long stale,long averageMicros,long maxMicros,AttractionEvidence lastAttraction,String lastReason){}
    private MigrationManager(){}
}
