package com.seaquake6324.civitas.infrastructure.population;

import com.seaquake6324.civitas.application.AdoptOrphanService;
import com.seaquake6324.civitas.domain.City;
import com.seaquake6324.civitas.domain.building.*;
import com.seaquake6324.civitas.domain.population.*;
import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;
import com.seaquake6324.civitas.infrastructure.persistence.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;

/** Main-thread player-family adoption orchestration with persisted unanimous player consent. */
public final class PlayerAdoptionManager {
    private static final AdoptionRules RULES=new AdoptionRules();
    private static final AdoptOrphanService ADOPT=new AdoptOrphanService();
    private static long requests,confirmations,completed,declined,expired,rejected,stale,totalMicros,maxMicros;private static String lastReason="not_run";private static AdoptionRules.Result lastEvaluation;

    public static Result request(ServerPlayer player,City city,UUID childId,long expectedOrphanRevision){long started=System.nanoTime();try{
        PopulationSavedData data=PopulationSavedData.get(player.level().getServer());BuildingSavedData buildings=BuildingSavedData.get(player.level().getServer());long now=player.level().getGameTime();
        if(data.readOnly()||buildings.readOnly())return fail("read_only");if(!city.isMember(player.getUUID())||data.profile(player.getUUID()).isEmpty())return fail("not_eligible");
        OrphanRecord orphan=data.orphan(childId).orElse(null);CitizenRecord child=data.citizen(childId).orElse(null);if(orphan==null||child==null||!child.alive()||orphan.revision()!=expectedOrphanRevision||!city.id().equals(orphan.cityId())||PopulationAgingManager.rules().evaluate(child.ageTicks()).stage()!=AgeStage.CHILD)return fail("stale_orphan");
        if(data.adoptionConsentForChild(childId).isPresent())return fail("already_pending");
        FamilyMemberRef actor=FamilyMemberRef.player(player.getUUID());Household source=data.householdForGuardian(actor).or(()->data.householdForPartner(actor)).orElse(null);Set<FamilyMemberRef>guardians;
        if(source==null)guardians=Set.of(actor);else{if(!city.id().equals(source.cityId())||source.id().equals(child.householdId()))return fail("not_eligible");guardians=source.guardians().isEmpty()?source.partners():source.guardians();if(!guardians.contains(actor))return fail("not_guardian");}
        Set<UUID>required=playerGuardians(guardians);if(required.isEmpty())return fail("not_eligible");for(UUID id:required)if(data.profile(id).isEmpty()||!city.isMember(id))return fail("guardian_unavailable");
        UUID consentId=UUID.nameUUIDFromBytes((city.id()+":adoption:"+childId+":"+now+":"+player.getUUID()).getBytes(StandardCharsets.UTF_8));UUID householdId=source==null?UUID.nameUUIDFromBytes((consentId+":household").getBytes(StandardCharsets.UTF_8)):source.id();Anchor anchor=familyAnchor(player,source,buildings);Anchor childAnchor=childAnchor(orphan,child,data,buildings);if(anchor==null||childAnchor==null||!anchor.dimension.equals(childAnchor.dimension))return fail("missing_local_evidence");
        lastEvaluation=evaluate(source,guardians,anchor,childAnchor,data,buildings,true);if(!lastEvaluation.eligible())return fail(lastEvaluation.reason());
        AdoptionConsent consent=new AdoptionConsent(consentId,city.id(),childId,householdId,guardians,required,Set.of(player.getUUID()),source==null?null:source.residenceId(),anchor.dimension,anchor.position,now,now+CivitasConfig.ADOPTION_CONSENT_TICKS.get(),1);
        if(!data.createAdoptionConsent(consent,CivitasConfig.ADOPTION_CONSENT_CAP.get()))return fail("capacity_or_stale");requests++;if(consent.complete())return finish(data,buildings,consent,now);lastReason="awaiting_guardians";return new Result(true,"awaiting_guardians",consent);
    }finally{recordTime(started);}}

    public static Result act(ServerPlayer player,City city,UUID consentId,long expectedRevision,boolean approve){long started=System.nanoTime();try{PopulationSavedData data=PopulationSavedData.get(player.level().getServer());AdoptionConsent consent=data.adoptionConsent(consentId).orElse(null);long now=player.level().getGameTime();if(consent==null||consent.revision()!=expectedRevision||!consent.cityId().equals(city.id())||!consent.requiredPlayers().contains(player.getUUID()))return fail("stale_consent");if(now>=consent.expiresAt()){data.removeAdoptionConsent(consent.id(),consent.revision());expired++;return fail("expired");}if(!approve){if(data.removeAdoptionConsent(consent.id(),consent.revision())){declined++;lastReason="declined";return new Result(true,"declined",null);}return fail("stale_consent");}if(consent.confirmedPlayers().contains(player.getUUID()))return fail("already_confirmed");AdoptionConsent confirmed=consent.confirm(player.getUUID());if(!data.updateAdoptionConsent(confirmed,consent.revision()))return fail("stale_consent");confirmations++;if(!confirmed.complete()){lastReason="awaiting_guardians";return new Result(true,"awaiting_guardians",confirmed);}return finish(data,BuildingSavedData.get(player.level().getServer()),confirmed,now);}finally{recordTime(started);}}

    private static Result finish(PopulationSavedData data,BuildingSavedData buildings,AdoptionConsent consent,long now){OrphanRecord orphan=data.orphan(consent.childId()).orElse(null);CitizenRecord child=data.citizen(consent.childId()).orElse(null);if(orphan==null||child==null||!child.alive()){remove(data,consent);return fail("stale_orphan");}Household source=data.household(consent.householdId()).orElse(null);if(source!=null){Set<FamilyMemberRef>current=source.guardians().isEmpty()?source.partners():source.guardians();if(!current.equals(consent.guardians())){remove(data,consent);return fail("family_changed");}}
        for(FamilyMemberRef guardian:consent.guardians()){if(guardian.kind()==FamilyMemberRef.Kind.PLAYER){if(data.profile(guardian.id()).isEmpty()||!consent.confirmedPlayers().contains(guardian.id()))return fail("missing_confirmation");}else{CitizenRecord npc=data.citizen(guardian.id()).orElse(null);if(npc==null||!npc.alive()){remove(data,consent);return fail("guardian_unavailable");}}}
        Anchor family=source==null?new Anchor(consent.anchorDimension(),consent.anchorPosition()):familyAnchor(source,buildings);Anchor childPos=childAnchor(orphan,child,data,buildings);if(family==null||childPos==null||!family.dimension.equals(childPos.dimension)){remove(data,consent);return fail("missing_local_evidence");}lastEvaluation=evaluate(source,consent.guardians(),family,childPos,data,buildings,true);if(!lastEvaluation.eligible()){remove(data,consent);return fail(lastEvaluation.reason());}if(stableRoll(child.id(),consent.householdId())>=lastEvaluation.score()/100.0){remove(data,consent);return fail("willingness_roll_failed");}
        int food=source==null?50:source.foodCoverage(),housing=source==null?0:source.housingCoverage();Household adoptive=source==null?new Household(consent.householdId(),consent.cityId(),Set.of(),Set.of(),consent.guardians(),Set.of(child.id()),consent.residenceId(),food,housing,1):source.addChild(child.id(),consent.guardians());Household origin=child.householdId()==null?null:data.household(child.householdId()).orElse(null);Map<UUID,Long>revisions=new HashMap<>();for(FamilyMemberRef guardian:consent.guardians())if(guardian.kind()==FamilyMemberRef.Kind.CITIZEN)data.citizen(guardian.id()).ifPresent(c->revisions.put(c.id(),c.revision()));var result=ADOPT.adopt(data,new AdoptOrphanService.Request(child.id(),orphan.revision(),child.revision(),adoptive,source==null?0:source.revision(),origin==null?0:origin.revision(),revisions,consent.confirmedPlayers(),CivitasConfig.HOUSEHOLD_CHILD_CAPACITY.get()));if(!result.success()){stale++;return fail("commit_stale");}data.removeAdoptionConsent(consent.id(),consent.revision());completed++;lastReason="adopted";return new Result(true,"adopted",null);}

    public static void maintain(net.minecraft.server.MinecraftServer server){PopulationSavedData data=PopulationSavedData.get(server);long now=server.overworld().getGameTime();var batch=data.adoptionConsentBatch(data.adoptionConsentCursor(),CivitasConfig.ADOPTION_CONSENT_MAINTENANCE_BATCH.get());for(AdoptionConsent consent:batch.records())if(now>=consent.expiresAt()&&data.removeAdoptionConsent(consent.id(),consent.revision()))expired++;data.adoptionConsentCursor(batch.wrapped()?null:batch.nextCursor());}
    private static AdoptionRules.Result evaluate(Household source,Set<FamilyMemberRef>guardians,Anchor family,Anchor child,PopulationSavedData data,BuildingSavedData buildings,boolean consent){int maximum=CivitasConfig.HOUSEHOLD_CHILD_CAPACITY.get(),children=source==null?0:source.children().size();BuildingRecord residence=source==null||source.residenceId()==null?null:buildings.byId(source.residenceId()).filter(b->b.status()==BuildingStatus.VALID&&b.purpose()==BuildingPurpose.RESIDENCE).orElse(null);int remaining=Math.max(0,maximum-children);if(residence!=null)remaining=Math.min(remaining,Math.max(0,residence.capacity()-guardians.size()-children));double food=source==null?50:source.foodCoverage(),housing=source==null?0:source.housingCoverage(),safety=50,willingness=50;int npcs=0;for(FamilyMemberRef guardian:guardians)if(guardian.kind()==FamilyMemberRef.Kind.CITIZEN){CitizenRecord npc=data.citizen(guardian.id()).orElse(null);if(npc!=null){safety+=npc.needs().safety();willingness+=npc.settlementWillingness();npcs++;}}if(npcs>0){safety=(safety-50)/npcs;willingness=(willingness-50)/npcs;}double distance=Math.sqrt(BlockPos.of(family.position).distSqr(BlockPos.of(child.position)));return RULES.evaluate(new AdoptionRules.Candidate(guardians.size(),true,remaining,Math.max(1,maximum),housing,food,safety,willingness),distance,CivitasConfig.ADOPTION_MAX_DISTANCE_BLOCKS.get(),consent);}
    private static Anchor familyAnchor(ServerPlayer player,Household source,BuildingSavedData buildings){Anchor fixed=familyAnchor(source,buildings);return fixed!=null?fixed:new Anchor(player.level().dimension().identifier().toString(),player.blockPosition().asLong());}
    private static Anchor familyAnchor(Household source,BuildingSavedData buildings){if(source==null||source.residenceId()==null)return null;return buildings.byId(source.residenceId()).filter(b->b.status()==BuildingStatus.VALID&&b.purpose()==BuildingPurpose.RESIDENCE).map(b->new Anchor(b.dimension(),b.interior())).orElse(null);}
    private static Anchor childAnchor(OrphanRecord orphan,CitizenRecord child,PopulationSavedData data,BuildingSavedData buildings){UUID residence=orphan.lastResidenceId()!=null?orphan.lastResidenceId():child.residenceId();if(residence!=null){BuildingRecord b=buildings.byId(residence).filter(x->x.status()==BuildingStatus.VALID).orElse(null);if(b!=null)return new Anchor(b.dimension(),b.interior());}return data.location(child.id()).map(l->new Anchor(l.dimension(),l.position())).orElse(null);}
    private static Set<UUID>playerGuardians(Set<FamilyMemberRef>guardians){Set<UUID>out=new HashSet<>();for(FamilyMemberRef guardian:guardians)if(guardian.kind()==FamilyMemberRef.Kind.PLAYER)out.add(guardian.id());return Set.copyOf(out);}
    private static double stableRoll(UUID child,UUID household){return new SplittableRandom(child.getMostSignificantBits()^Long.rotateLeft(child.getLeastSignificantBits(),7)^household.getMostSignificantBits()^Long.rotateLeft(household.getLeastSignificantBits(),29)).nextDouble();}
    private static void remove(PopulationSavedData data,AdoptionConsent consent){data.removeAdoptionConsent(consent.id(),consent.revision());}
    private static Result fail(String reason){rejected++;lastReason=reason;return new Result(false,reason,null);}private static void recordTime(long started){long micros=Math.max(0,(System.nanoTime()-started)/1_000);totalMicros+=micros;maxMicros=Math.max(maxMicros,micros);}
    public static Metrics metrics(){return new Metrics(requests,confirmations,completed,declined,expired,rejected,stale,totalMicros/Math.max(1,requests+confirmations),maxMicros,lastReason,lastEvaluation);}public record Metrics(long requests,long confirmations,long completed,long declined,long expired,long rejected,long stale,long averageMicros,long maxMicros,String lastReason,AdoptionRules.Result lastEvaluation){}public record Result(boolean success,String reason,AdoptionConsent consent){}private record Anchor(String dimension,long position){}private PlayerAdoptionManager(){}
}
