package com.seaquake6324.civitas.infrastructure.security;

import com.seaquake6324.civitas.application.AssignGuardService;import com.seaquake6324.civitas.domain.City;import com.seaquake6324.civitas.domain.population.*;import com.seaquake6324.civitas.domain.security.*;import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;import com.seaquake6324.civitas.infrastructure.entity.CitizenEntity;import com.seaquake6324.civitas.infrastructure.network.OpenCitizenInfoPayload;import com.seaquake6324.civitas.infrastructure.persistence.*;import com.seaquake6324.civitas.infrastructure.population.PopulationAgingManager;import java.util.*;import net.minecraft.server.level.*;import net.minecraft.tags.ItemTags;import net.minecraft.world.entity.EquipmentSlot;import net.minecraft.world.item.*;import net.minecraft.world.phys.AABB;

/** Main-thread adapter for close-range guard appointment and real equipment evidence. */
public final class GuardAssignmentManager {
    private static final AssignGuardService SERVICE=new AssignGuardService();private static final GuardAssignmentRules RULES=new GuardAssignmentRules();
    private static long views,attempts,assigned,rejected,forced,entityChecks;private static String lastReason="not_run";

    public static View view(ServerPlayer player,CitizenEntity entity,CitizenRecord citizen){views++;City city=citizen.cityId()==null?null:CitySavedData.get(player.level().getServer()).byId(citizen.cityId()).orElse(null);ThreatSavedData threat=ThreatSavedData.get(player.level().getServer());GuardEquipment equipment=equipment(entity);AgeStage age=PopulationAgingManager.rules().evaluate(citizen.ageTicks()).stage();String action;if(city==null||!city.mayManage(player.getUUID()))action="not_authorized";else if(!citizen.alive()||age==AgeStage.CHILD)action="underage";else if(threat.patrolAssignmentForCitizen(citizen.id()).isPresent())action="already_assigned";else action="available";List<OpenCitizenInfoPayload.GuardRouteOption>routes="available".equals(action)?threat.patrolRoutes(city.id(),CivitasConfig.PATROL_ROUTE_CITY_CAP.get()).stream().filter(r->r.status()==PatrolRoute.Status.VALID).map(r->new OpenCitizenInfoPayload.GuardRouteOption(r.id(),r.revision(),r.nodes().size())).toList():List.of();if("available".equals(action)&&routes.isEmpty())action="no_routes";double day=score(citizen,equipment,GuardShift.DAY),night=score(citizen,equipment,GuardShift.NIGHT);return new View(action,equipment,(float)day,(float)night,routes);}

    public static Result assign(ServerPlayer player,UUID citizenId,long expectedCitizenRevision,UUID routeId,long expectedRouteRevision,GuardShift shift,boolean force){attempts++;if(!(player.level() instanceof ServerLevel level)){return reject("invalid_level");}PopulationSavedData population=PopulationSavedData.get(level.getServer());ThreatSavedData threat=ThreatSavedData.get(level.getServer());if(population.readOnly()||threat.readOnly())return reject("read_only");CitizenRecord citizen=population.citizen(citizenId).orElse(null);City city=citizen==null||citizen.cityId()==null?null:CitySavedData.get(level.getServer()).byId(citizen.cityId()).orElse(null);PatrolRoute route=threat.patrolRoute(routeId).orElse(null);if(route==null||route.revision()!=expectedRouteRevision)return reject("stale_route");var post=BuildingSavedData.get(level.getServer()).byId(route.guardPostId()).orElse(null);CitizenEntity entity=find(level,player,citizenId);if(entity==null)return reject("not_nearby");GuardEquipment equipment=equipment(entity);AgeStage age=citizen==null?AgeStage.CHILD:PopulationAgingManager.rules().evaluate(citizen.ageTicks()).stage();var result=SERVICE.assign(threat,new AssignGuardService.Request(UUID.randomUUID(),city,player.getUUID(),citizen,city==null?0:city.revision(),expectedCitizenRevision,age,route,post,shift,equipment,force,50,CivitasConfig.GUARD_MINIMUM_WILLINGNESS.get(),weights(),level.getGameTime(),CivitasConfig.PATROL_ASSIGNMENT_CITY_CAP.get()));if(!result.success())return reject(result.failure().name().toLowerCase(Locale.ROOT));assigned++;if(result.assignment().forced())forced++;lastReason=result.assignment().status().name().toLowerCase(Locale.ROOT);return new Result(true,lastReason,result.assignment());}

    public static GuardEquipment equipment(CitizenEntity entity){ItemStack hand=entity.getMainHandItem();boolean weapon=hand.is(ItemTags.SWORDS)||hand.is(ItemTags.AXES)||hand.is(ItemTags.BOW_ENCHANTABLE)||hand.is(ItemTags.CROSSBOW_ENCHANTABLE)||hand.is(ItemTags.TRIDENT_ENCHANTABLE);int armor=0;for(EquipmentSlot slot:List.of(EquipmentSlot.HEAD,EquipmentSlot.CHEST,EquipmentSlot.LEGS,EquipmentSlot.FEET))if(!entity.getItemBySlot(slot).isEmpty())armor++;boolean shield=entity.getOffhandItem().is(Items.SHIELD);return new GuardEquipment(weapon,armor,shield);}
    public static GuardAssignmentRules.Weights weights(){double[]raw={CivitasConfig.GUARD_SETTLEMENT_WEIGHT.get(),CivitasConfig.GUARD_SAFETY_WEIGHT.get(),CivitasConfig.GUARD_WEAPON_WEIGHT.get(),CivitasConfig.GUARD_ARMOR_WEIGHT.get(),CivitasConfig.GUARD_SHIELD_WEIGHT.get(),CivitasConfig.GUARD_SHIFT_WEIGHT.get(),CivitasConfig.GUARD_RELIABILITY_WEIGHT.get()};double total=Arrays.stream(raw).sum();if(total<=0){raw=new double[]{.35,.15,.20,.10,.05,.05,.10};total=1;}return new GuardAssignmentRules.Weights(raw[0]/total,raw[1]/total,raw[2]/total,raw[3]/total,raw[4]/total,raw[5]/total,raw[6]/total);}
    private static double score(CitizenRecord citizen,GuardEquipment equipment,GuardShift shift){return RULES.evaluate(new GuardAssignmentRules.Inputs(citizen.settlementWillingness(),citizen.needs().safety(),equipment,shift,50),weights()).score();}
    private static CitizenEntity find(ServerLevel level,ServerPlayer player,UUID citizenId){List<CitizenEntity>entities=level.getEntitiesOfClass(CitizenEntity.class,new AABB(player.blockPosition()).inflate(8),e->e.citizenId().filter(citizenId::equals).isPresent());entityChecks+=entities.size();return entities.stream().min(Comparator.comparing(CitizenEntity::getUUID)).orElse(null);}
    private static Result reject(String reason){rejected++;lastReason=reason;return new Result(false,reason,null);}public static Metrics metrics(){return new Metrics(views,attempts,assigned,rejected,forced,entityChecks,lastReason);}public record View(String action,GuardEquipment equipment,float dayWillingness,float nightWillingness,List<OpenCitizenInfoPayload.GuardRouteOption>routes){}public record Result(boolean success,String reason,PatrolAssignment assignment){}public record Metrics(long views,long attempts,long assigned,long rejected,long forced,long entityChecks,String lastReason){}private GuardAssignmentManager(){}
}
