package com.seaquake6324.civitas.infrastructure.security;

import com.seaquake6324.civitas.domain.building.*;import com.seaquake6324.civitas.domain.population.*;import com.seaquake6324.civitas.domain.security.*;import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;import com.seaquake6324.civitas.infrastructure.entity.*;import com.seaquake6324.civitas.infrastructure.persistence.*;import java.util.*;import net.minecraft.core.BlockPos;import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerLevel;import net.minecraft.world.level.ChunkPos;

/** Bounded main-thread guard execution. Virtual guards only advance validated node indices. */
public final class PatrolExecutionManager {
    private static MinecraftServer owner;private static UUID cursor;private static long lastDriveTick=-1;private static int drivesThisTick;
    private static long ticks,examined,active,offShift,unequipped,virtualAdvances,visibleDrives,nodesReached,staleRoutes,missingGuards,totalMicros,maxMicros;private static String lastReason="not_run";
    public static void tick(MinecraftServer server){if(owner!=server)reset(server);long began=System.nanoTime();ThreatSavedData threat=ThreatSavedData.get(server);PopulationSavedData population=PopulationSavedData.get(server);CitizenEquipmentSavedData equipment=CitizenEquipmentSavedData.get(server);if(threat.readOnly()||population.readOnly()||equipment.readOnly()){lastReason="read_only";return;}var batch=threat.patrolAssignmentBatch(cursor,CivitasConfig.PATROL_ASSIGNMENTS_PER_TICK.get());for(PatrolAssignment assignment:batch.assignments()){process(server,threat,population,equipment,assignment);examined++;}if(!batch.assignments().isEmpty())cursor=batch.nextCursor();ticks++;long micros=(System.nanoTime()-began)/1000;totalMicros+=micros;maxMicros=Math.max(maxMicros,micros);}
    private static void process(MinecraftServer server,ThreatSavedData threat,PopulationSavedData population,CitizenEquipmentSavedData equipmentData,PatrolAssignment assignment){PatrolRoute route=threat.patrolRoute(assignment.routeId()).orElse(null);CitizenRecord citizen=population.citizen(assignment.citizenId()).orElse(null);BuildingRecord post=BuildingSavedData.get(server).byId(assignment.guardPostId()).orElse(null);long now=server.overworld().getGameTime();if(route==null||route.status()!=PatrolRoute.Status.VALID||post==null||post.status()!=BuildingStatus.VALID){replace(threat,assignment,PatrolAssignment.Status.ROUTE_STALE,"route_or_post_stale",assignment.nodeIndex(),assignment.forward(),assignment.lastProgressAt(),assignment.lastCoverageAt());staleRoutes++;lastReason="route_or_post_stale";return;}if(citizen==null||!citizen.alive()||!assignment.cityId().equals(citizen.cityId())){replace(threat,assignment,PatrolAssignment.Status.GUARD_MISSING,"citizen_missing",assignment.nodeIndex(),assignment.forward(),assignment.lastProgressAt(),assignment.lastCoverageAt());missingGuards++;lastReason="citizen_missing";return;}if(!assignment.shift().onDuty(server.overworld().getOverworldClockTime())){replace(threat,assignment,PatrolAssignment.Status.OFF_SHIFT,"off_shift",assignment.nodeIndex(),assignment.forward(),assignment.lastProgressAt(),assignment.lastCoverageAt());offShift++;lastReason="off_shift";return;}CitizenEntity entity=entity(server,assignment.citizenId());GuardEquipment equipment=entity==null?equipmentData.guardEquipment(citizen.id(),server.registryAccess()):GuardAssignmentManager.equipment(entity);if(!equipment.basicWeapon()){replace(threat,assignment,PatrolAssignment.Status.UNEQUIPPED,"missing_basic_weapon",assignment.nodeIndex(),assignment.forward(),assignment.lastProgressAt(),assignment.lastCoverageAt());unequipped++;lastReason="missing_basic_weapon";return;}if(entity!=null){replace(threat,assignment,PatrolAssignment.Status.ACTIVE,"",assignment.nodeIndex(),assignment.forward(),assignment.lastProgressAt(),assignment.lastCoverageAt());active++;lastReason="visible_active";return;}if(now-assignment.lastProgressAt()>=CivitasConfig.PATROL_VIRTUAL_NODE_TICKS.get()){Progress progress=advance(assignment,route);long chunk=ChunkPos.pack(BlockPos.of(route.nodes().get(progress.nodeIndex)));threat.recordPatrolCoverage(assignment.cityId(),chunk,assignment.id(),now,false);replace(threat,assignment,PatrolAssignment.Status.ACTIVE,"",progress.nodeIndex,progress.forward,now,now);virtualAdvances++;lastReason="virtual_advance";}else{replace(threat,assignment,PatrolAssignment.Status.ACTIVE,"",assignment.nodeIndex(),assignment.forward(),assignment.lastProgressAt(),assignment.lastCoverageAt());active++;lastReason="virtual_wait";}}
    public static boolean drive(CitizenEntity entity,ServerLevel level){long now=level.getGameTime();if(lastDriveTick!=now){lastDriveTick=now;drivesThisTick=0;}if(drivesThisTick>=CivitasConfig.PATROL_VISIBLE_DRIVES_PER_TICK.get())return false;UUID citizen=entity.citizenId().orElse(null);if(citizen==null)return false;ThreatSavedData threat=ThreatSavedData.get(level.getServer());PatrolAssignment assignment=threat.patrolAssignmentForCitizen(citizen).orElse(null);if(assignment==null||assignment.status()!=PatrolAssignment.Status.ACTIVE||!assignment.shift().onDuty(level.getOverworldClockTime())||!GuardAssignmentManager.equipment(entity).basicWeapon())return false;PatrolRoute route=threat.patrolRoute(assignment.routeId()).orElse(null);if(route==null||route.status()!=PatrolRoute.Status.VALID||assignment.nodeIndex()>=route.nodes().size())return false;BlockPos target=BlockPos.of(route.nodes().get(assignment.nodeIndex()));if(!level.hasChunkAt(target))return false;if(!standable(level,target)){if(threat.markPatrolRouteStale(route.id(),"path_blocked")){staleRoutes++;lastReason="path_blocked";}return false;}drivesThisTick++;visibleDrives++;double reach=CivitasConfig.PATROL_NODE_REACH_DISTANCE.get();if(entity.distanceToSqr(target.getX()+.5,target.getY(),target.getZ()+.5)<=reach*reach){threat.recordPatrolCoverage(assignment.cityId(),ChunkPos.pack(target),assignment.id(),now,true);Progress progress=advance(assignment,route);replace(threat,assignment,PatrolAssignment.Status.ACTIVE,"",progress.nodeIndex,progress.forward,now,now);nodesReached++;lastReason="visible_node_reached";return true;}entity.getNavigation().moveTo(target.getX()+.5,target.getY(),target.getZ()+.5,1.0);lastReason="visible_pathing";return true;}
    private static Progress advance(PatrolAssignment assignment,PatrolRoute route){int last=route.nodes().size()-1,index=assignment.nodeIndex();boolean forward=assignment.forward();if(forward&&index>=last){forward=false;index=Math.max(0,last-1);}else if(!forward&&index<=0){forward=true;index=Math.min(last,1);}else index+=forward?1:-1;return new Progress(index,forward);}
    private static CitizenEntity entity(MinecraftServer server,UUID citizenId){var lease=MaterializationLeaseManager.lease(citizenId).orElse(null);if(lease==null)return null;for(ServerLevel level:server.getAllLevels()){var entity=level.getEntity(lease.entityId());if(entity instanceof CitizenEntity citizen)return citizen;}return null;}
    private static boolean standable(ServerLevel level,BlockPos p){return level.isInWorldBounds(p)&&level.getBlockState(p).getCollisionShape(level,p).isEmpty()&&level.getBlockState(p.above()).getCollisionShape(level,p.above()).isEmpty()&&level.getBlockState(p.below()).blocksMotion()&&level.getFluidState(p).isEmpty();}
    private static void replace(ThreatSavedData threat,PatrolAssignment assignment,PatrolAssignment.Status status,String reason,int node,boolean forward,long progress,long coverage){PatrolAssignment next=assignment.withState(status,reason,node,forward,progress,coverage);if(next!=assignment&&!threat.replacePatrolAssignment(next,assignment.revision()))lastReason="stale_assignment";}
    private static void reset(MinecraftServer server){owner=server;cursor=null;lastDriveTick=-1;drivesThisTick=0;ticks=examined=active=offShift=unequipped=virtualAdvances=visibleDrives=nodesReached=staleRoutes=missingGuards=totalMicros=maxMicros=0;lastReason="server_reset";}public static Metrics metrics(){return new Metrics(ticks,examined,active,offShift,unequipped,virtualAdvances,visibleDrives,nodesReached,staleRoutes,missingGuards,ticks==0?0:totalMicros/ticks,maxMicros,lastReason);}public record Metrics(long ticks,long examined,long active,long offShift,long unequipped,long virtualAdvances,long visibleDrives,long nodesReached,long staleRoutes,long missingGuards,long averageMicros,long maxMicros,String lastReason){}private record Progress(int nodeIndex,boolean forward){}private PatrolExecutionManager(){}
}
