package com.seaquake6324.civitas.infrastructure.security;

import com.seaquake6324.civitas.application.EvaluateSecurityCellService;
import com.seaquake6324.civitas.domain.City;
import com.seaquake6324.civitas.domain.civilization.CivilizationLayer;
import com.seaquake6324.civitas.domain.security.*;
import com.seaquake6324.civitas.domain.territory.*;
import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;
import com.seaquake6324.civitas.infrastructure.persistence.*;
import java.util.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;

/** Fair, bounded main-thread refresh of whole-city security and legal infiltration evidence. */
public final class SecurityCellManager {
    private static final EvaluateSecurityCellService SERVICE=new EvaluateSecurityCellService();
    private static final InfiltrationCellScanner INFILTRATION=new InfiltrationCellScanner();
    private static final ArrayDeque<Work>QUEUE=new ArrayDeque<>();
    private static final Set<ThreatSavedData.CellKey>QUEUED=new HashSet<>();
    private static MinecraftServer owner;private static UUID discoveryCityCursor;private static City discoveryCity;private static Iterator<Long>discoveryChunks;private static long nextDiscovery;
    private static ThreatSavedData.CellKey cleanupCursor;
    private static long assessed,deferred,missing,truncatedDiscoveries,discoveryCycles,cleanupExamined,cleanupRemoved,buildingEvidenceTruncations,infiltrationSamples,infiltrationTruncations,infiltrationUnloaded,totalMicros,maxMicros;private static boolean discoveryTruncated;

    public static void tick(MinecraftServer server){if(owner!=server)reset(server);long now=server.overworld().getGameTime();fill(server,now);int count=Math.min(QUEUE.size(),CivitasConfig.SECURITY_CELLS_PER_TICK.get());for(int i=0;i<count;i++){Work work=QUEUE.removeFirst();QUEUED.remove(new ThreatSavedData.CellKey(work.cityId(),work.chunk()));process(server,work,now);}cleanup(server);fill(server,now);}

    private static void fill(MinecraftServer server,long now){if(now<nextDiscovery)return;int cap=CivitasConfig.SECURITY_QUEUE_LIMIT.get();while(QUEUE.size()<cap){if(discoveryChunks!=null&&discoveryChunks.hasNext()){offer(new Work(discoveryCity.id(),discoveryChunks.next()));continue;}discoveryCity=null;discoveryChunks=null;var batch=CitySavedData.get(server).cityBatchAfter(discoveryCityCursor,1);if(batch.cities().isEmpty()){discoveryCityCursor=null;nextDiscovery=now+CivitasConfig.SECURITY_REFRESH_TICKS.get();discoveryCycles++;discoveryTruncated=false;return;}discoveryCity=batch.cities().getFirst();discoveryCityCursor=discoveryCity.id();discoveryChunks=discoveryCity.territory().iterator();}
        if(!discoveryTruncated){discoveryTruncated=true;truncatedDiscoveries++;}}

    private static void cleanup(MinecraftServer server){ThreatSavedData threat=ThreatSavedData.get(server);var batch=threat.securityCellMaintenanceBatch(cleanupCursor,CivitasConfig.SECURITY_CELLS_PER_TICK.get());for(var entry:batch.entries()){cleanupExamined++;City city=CitySavedData.get(server).byId(entry.getKey().cityId()).orElse(null);if(city==null||!city.territory().contains(entry.getKey().chunk()))if(threat.removeSecurityCell(entry.getKey()))cleanupRemoved++;}cleanupCursor=batch.exhausted()?null:batch.nextCursor();}

    private static void process(MinecraftServer server,Work work,long now){long started=System.nanoTime();City city=CitySavedData.get(server).byId(work.cityId()).orElse(null);if(city==null||!city.territory().contains(work.chunk())){missing++;finish(started);return;}TerritoryChunkState territory=city.territoryStates().get(work.chunk());if(territory==null){missing++;finish(started);return;}ThreatSavedData threat=ThreatSavedData.get(server);SecurityCell previous=threat.securityCell(city.id(),work.chunk()).orElse(null);if(previous!=null&&now-previous.evidence().assessedAt()<CivitasConfig.SECURITY_REFRESH_TICKS.get()){deferred++;finish(started);return;}var civilization=CivilizationSavedData.get(server).get(city.dimension(),work.chunk(),CivilizationLayer.SURFACE);SecurityTopology.Result topology=SecurityTopology.borderDistance(city.territory(),work.chunk(),CivitasConfig.SECURITY_TOPOLOGY_VISIT_LIMIT.get());var buildingPage=BuildingSavedData.get(server).recordsInChunk(city.id(),city.dimension(),work.chunk(),CivitasConfig.SECURITY_BUILDING_RECORD_LIMIT_PER_CELL.get());if(buildingPage.truncated())buildingEvidenceTruncations++;int validBuildings=(int)buildingPage.records().stream().filter(record->record.status()==com.seaquake6324.civitas.domain.building.BuildingStatus.VALID).count();int validatedEntrances=(int)buildingPage.records().stream().filter(record->record.status()==com.seaquake6324.civitas.domain.building.BuildingStatus.VALID&&record.features().entranceConnected()).count();var coverage=threat.coverageEvidence(city.id(),work.chunk(),now,CivitasConfig.PATROL_COVERAGE_MEMORY_TICKS.get());var level=level(server,city.dimension());var infiltration=level==null?new InfiltrationCellScanner.Result(List.of(),0,0,false,false,0,false):INFILTRATION.scan(level,city,work.chunk(),buildingPage.records(),!buildingPage.truncated(),CivitasConfig.INFILTRATION_WORLD_SAMPLES_PER_CELL.get(),CivitasConfig.INFILTRATION_CANDIDATES_PER_CELL.get(),CivitasConfig.INFILTRATION_GUARDED_THRESHOLD.get(),coverage.patrol(),coverage.visibleGuard());infiltrationSamples+=infiltration.worldSamples();if(infiltration.truncated())infiltrationTruncations++;if(!infiltration.infiltrationEvidenceLinked()&&!infiltration.truncated())infiltrationUnloaded++;SecurityCellEvidence evidence=new SecurityCellEvidence(civilization.civility(),civilization.activity(),civilization.factors().safety(),topology.distance(),topology.limited(),territory.neglectStage(),territory.lastDefenseResult(),territory.lastDefenseAt(),city.territory().size(),validBuildings,validatedEntrances,!buildingPage.truncated(),coverage.patrol(),coverage.visibleGuard(),coverage.patrolLinked(),coverage.guardLinked(),infiltration.infiltrationAccess(),infiltration.undergroundDarkness(),infiltration.infiltrationEvidenceLinked(),infiltration.undergroundEvidenceLinked(),now);SecurityCell cell=SERVICE.evaluate(city.id(),work.chunk(),evidence,weights(),previous==null?0:previous.revision());threat.putSecurityCell(cell);assessed++;finish(started);}
    private static void finish(long started){long micros=Math.max(0,(System.nanoTime()-started)/1_000);totalMicros+=micros;maxMicros=Math.max(maxMicros,micros);}
    private static void offer(Work work){ThreatSavedData.CellKey key=new ThreatSavedData.CellKey(work.cityId(),work.chunk());if(QUEUED.add(key))QUEUE.addLast(work);}
    private static SecurityRiskRules.Weights weights(){return new SecurityRiskRules.Weights(CivitasConfig.SECURITY_CIVILITY_WEIGHT.get(),CivitasConfig.SECURITY_ACTIVITY_WEIGHT.get(),CivitasConfig.SECURITY_BUILT_SAFETY_WEIGHT.get(),CivitasConfig.SECURITY_PATROL_WEIGHT.get(),CivitasConfig.SECURITY_GUARD_WEIGHT.get(),CivitasConfig.SECURITY_INFILTRATION_WEIGHT.get(),CivitasConfig.SECURITY_UNDERGROUND_WEIGHT.get(),CivitasConfig.SECURITY_BORDER_WEIGHT.get(),CivitasConfig.SECURITY_NEGLECT_WEIGHT.get(),CivitasConfig.SECURITY_FAILURE_WEIGHT.get(),CivitasConfig.SECURITY_CITY_SCALE_WEIGHT.get(),CivitasConfig.SECURITY_FAILURE_MEMORY_TICKS.get(),CivitasConfig.SECURITY_FULL_SCALE_CHUNKS.get());}
    private static ServerLevel level(MinecraftServer server,String dimension){for(ServerLevel level:server.getAllLevels())if(level.dimension().identifier().toString().equals(dimension))return level;return null;}
    private static void reset(MinecraftServer server){owner=server;QUEUE.clear();QUEUED.clear();discoveryCityCursor=null;discoveryCity=null;discoveryChunks=null;cleanupCursor=null;nextDiscovery=0;assessed=deferred=missing=truncatedDiscoveries=discoveryCycles=cleanupExamined=cleanupRemoved=buildingEvidenceTruncations=infiltrationSamples=infiltrationTruncations=infiltrationUnloaded=totalMicros=maxMicros=0;discoveryTruncated=false;}
    public static Metrics metrics(){long processed=Math.max(1,assessed+deferred+missing);return new Metrics(QUEUE.size(),assessed,deferred,missing,truncatedDiscoveries,discoveryCycles,cleanupExamined,cleanupRemoved,buildingEvidenceTruncations,infiltrationSamples,infiltrationTruncations,infiltrationUnloaded,discoveryTruncated,totalMicros/processed,maxMicros);}
    public static Summary summary(MinecraftServer server,UUID cityId){var page=ThreatSavedData.get(server).securityCellPage(cityId,CivitasConfig.SECURITY_QUEUE_LIMIT.get());List<SecurityCell>cells=page.cells();if(cells.isEmpty())return new Summary(0,0,0,0,"NONE",0,0,0,0,page.truncated(),page.examined());double average=cells.stream().mapToDouble(SecurityCell::diagnosticRisk).average().orElse(0);SecurityCell weakest=cells.stream().max(Comparator.comparingDouble(SecurityCell::diagnosticRisk)).orElseThrow();int missing=(int)cells.stream().filter(c->!c.missingEvidence().isEmpty()).count();long updated=cells.stream().mapToLong(c->c.evidence().assessedAt()).max().orElse(0);int covered=(int)cells.stream().filter(c->c.evidence().patrolCoverage()>0).count(),visible=(int)cells.stream().filter(c->c.evidence().guardResponse()>0).count();return new Summary(cells.size(),average,weakest.diagnosticRisk(),weakest.chunk(),weakest.primaryFactor().name(),missing,updated,covered,visible,page.truncated(),page.examined());}
    public record Metrics(int queued,long assessed,long deferred,long missing,long truncatedDiscoveries,long discoveryCycles,long cleanupExamined,long cleanupRemoved,long buildingEvidenceTruncations,long infiltrationSamples,long infiltrationTruncations,long infiltrationUnloaded,boolean discoveryTruncated,long averageMicros,long maxMicros){}
    public record Summary(int assessedCells,double averageRisk,double maxRisk,long weakestChunk,String primaryFactor,int cellsWithMissingEvidence,long updatedAt,int recentlyPatrolledCells,int visibleGuardCells,boolean truncated,int examined){}
    private record Work(UUID cityId,long chunk){}
    private SecurityCellManager(){}
}
