package com.seaquake6324.civitas.domain.security;
import static org.junit.jupiter.api.Assertions.*;import com.seaquake6324.civitas.domain.territory.*;import java.util.UUID;import org.junit.jupiter.api.Test;
class SecurityRiskRulesTest{
 private static final SecurityRiskRules.Weights W=new SecurityRiskRules.Weights(1,1,1,1,1,1,.5,24000,64);
 @Test void exposesEveryRawContributionAndMissingFutureEvidence(){var e=new SecurityCellEvidence(80,60,70,0,false,NeglectStage.WARNING,TerritoryChunkState.DefenseResult.FAILURE,900,16,2,2,1000);SecurityCell cell=new SecurityRiskRules().evaluate(UUID.randomUUID(),1,e,W,3);assertEquals(11,cell.contributions().size());assertEquals(100,cell.contributions().get(SecurityFactor.BORDER_EXPOSURE).risk());assertEquals(5,cell.missingEvidence().size());assertTrue(cell.diagnosticRisk()>0);assertEquals(3,cell.revision());}
 @Test void higherCivilityActivitySafetyAndDepthReduceDiagnosticRisk(){var weak=new SecurityCellEvidence(10,10,10,0,false,NeglectStage.RETRACTABLE,TerritoryChunkState.DefenseResult.FAILURE,0,64,0,0,100);var strong=new SecurityCellEvidence(90,90,90,3,false,NeglectStage.HEALTHY,TerritoryChunkState.DefenseResult.SUCCESS,0,9,4,4,100);var rules=new SecurityRiskRules();assertTrue(rules.evaluate(UUID.randomUUID(),1,weak,W,1).diagnosticRisk()>rules.evaluate(UUID.randomUUID(),1,strong,W,1).diagnosticRisk());}
 @Test void completeBuildingSnapshotRemovesOnlyBuildingLinkGap(){var evidence=new SecurityCellEvidence(80,80,80,2,false,NeglectStage.HEALTHY,TerritoryChunkState.DefenseResult.NONE,0,9,0,0,true,100);var cell=new SecurityRiskRules().evaluate(UUID.randomUUID(),1,evidence,W,1);assertFalse(cell.missingEvidence().contains(SecurityCell.MissingEvidence.BUILDING_RECORD_LINK));assertEquals(4,cell.missingEvidence().size());}
 @Test void recentPatrolAndVisibleGuardEvidenceRemoveTheirGapsAndReduceRisk(){var weights=new SecurityRiskRules.Weights(1,1,1,1,1,1,1,1,.5,24000,64);var none=new SecurityCellEvidence(50,50,50,1,false,NeglectStage.HEALTHY,TerritoryChunkState.DefenseResult.NONE,0,9,1,1,true,0,0,false,false,100);var covered=new SecurityCellEvidence(50,50,50,1,false,NeglectStage.HEALTHY,TerritoryChunkState.DefenseResult.NONE,0,9,1,1,true,100,100,true,true,100);var rules=new SecurityRiskRules();SecurityCell result=rules.evaluate(UUID.randomUUID(),1,covered,weights,1);assertFalse(result.missingEvidence().contains(SecurityCell.MissingEvidence.PATROL_COVERAGE));assertFalse(result.missingEvidence().contains(SecurityCell.MissingEvidence.GUARD_RESPONSE));assertTrue(result.diagnosticRisk()<rules.evaluate(UUID.randomUUID(),1,none,weights,1).diagnosticRisk());}
 @Test void completeInfiltrationEvidenceRemovesBothSourceGaps(){var weights=new SecurityRiskRules.Weights(1,1,1,1,1,1,1,1,1,1,.5,24000,64);var evidence=new SecurityCellEvidence(50,50,50,1,false,NeglectStage.HEALTHY,TerritoryChunkState.DefenseResult.NONE,0,9,1,1,true,0,0,false,false,80,60,true,true,100);var result=new SecurityRiskRules().evaluate(UUID.randomUUID(),1,evidence,weights,1);assertFalse(result.missingEvidence().contains(SecurityCell.MissingEvidence.INFILTRATION_SOURCE));assertFalse(result.missingEvidence().contains(SecurityCell.MissingEvidence.UNDERGROUND_DARKNESS));assertEquals(80,result.contributions().get(SecurityFactor.INFILTRATION_ACCESS).risk());}
 @Test void rejectsInvalidBalanceHypotheses(){assertThrows(IllegalArgumentException.class,()->new SecurityRiskRules.Weights(-1,1,1,1,1,1,1,1,1));}
}
