license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="\u9091"
logoFile="civitas.png"
authors="Seaquake6324"
description=''''''

[[mixins]]
config="civitas.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[mixins]]
config="civitas.core.mixins.json"
