package com.seaquake6324.civitas.infrastructure.border;
import com.seaquake6324.civitas.domain.territory.TerritoryChunkState;
import com.seaquake6324.civitas.domain.border.InvasionWaveRules;
import com.seaquake6324.civitas.domain.security.InfiltrationDefenseRules;
import com.seaquake6324.civitas.domain.security.InfiltrationPlan;
import com.seaquake6324.civitas.infrastructure.security.InfiltrationPlanner;
import com.seaquake6324.civitas.infrastructure.security.InvasionCommitmentManager;
import com.seaquake6324.civitas.infrastructure.persistence.BuildingSavedData;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;

import com.seaquake6324.civitas.domain.ChunkCoordinate;import com.seaquake6324.civitas.domain.City;import com.seaquake6324.civitas.domain.border.BorderReadiness;import com.seaquake6324.civitas.domain.border.ThreatPressure;import com.seaquake6324.civitas.domain.civilization.CivilizationLayer;import com.seaquake6324.civitas.domain.territory.TerritoryTopology;import com.seaquake6324.civitas.infrastructure.config.CivitasConfig;import com.seaquake6324.civitas.infrastructure.persistence.CitySavedData;import com.seaquake6324.civitas.infrastructure.persistence.CivilizationSavedData;import com.seaquake6324.civitas.infrastructure.persistence.ThreatSavedData;import java.util.*;import net.minecraft.core.BlockPos;import net.minecraft.core.particles.DustParticleOptions;import net.minecraft.network.chat.Component;import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerLevel;import net.minecraft.server.level.ServerPlayer;import net.minecraft.world.entity.*;import net.minecraft.world.entity.monster.Enemy;import net.minecraft.world.level.levelgen.Heightmap;

/** Bounded pressure and three-wave invasion orchestration. */
public final class BorderThreatManager{
 private static final InvasionWaveRules WAVE_RULES=new InvasionWaveRules();
 private static final InfiltrationDefenseRules INFILTRATION_DEFENSE=new InfiltrationDefenseRules();
 private static final Map<UUID,Long>INFILTRATION_RETRY_UNTIL=new HashMap<>();
 private static MinecraftServer owner;private static UUID cityCursor;private static City currentCity;private static Iterator<Long>chunkCursor;private static ThreatSavedData.EdgeKey cleanupCursor;private static long ticks,chunksExamined,edgesProcessed,cityCycles,cleanupExamined,cleanupRemoved,infiltrationIntercepted,infiltrationSpawnSamples,infiltrationSpawnRejected,totalMicros,maxMicros;
 public static void tick(MinecraftServer server){long now=server.overworld().getGameTime();if(now%20!=0)return;if(owner!=server)reset(server);long started=System.nanoTime();int budget=CivitasConfig.THREAT_BORDER_CHUNKS_PER_TICK.get();for(int i=0;i<budget;i++){ChunkWork chunk=nextChunk(server);if(chunk==null)break;chunksExamined++;for(var direction:TerritoryTopology.borderEdges(chunk.city.territory(),chunk.chunk)){process(server,new EdgeWork(chunk.city,chunk.chunk,direction),now);edgesProcessed++;}}cleanup(server);long micros=Math.max(0,(System.nanoTime()-started)/1_000);totalMicros+=micros;maxMicros=Math.max(maxMicros,micros);ticks++;}
 private static ChunkWork nextChunk(MinecraftServer server){int cityAdvances=0,limit=Math.max(1,CivitasConfig.THREAT_BORDER_CHUNKS_PER_TICK.get());while(cityAdvances<=limit){if(chunkCursor!=null&&chunkCursor.hasNext())return new ChunkWork(currentCity,chunkCursor.next());var batch=CitySavedData.get(server).cityBatch(cityCursor,1);if(batch.cities().isEmpty()){currentCity=null;chunkCursor=null;return null;}currentCity=batch.cities().getFirst();cityCursor=batch.nextCursor();if(batch.wrapped())cityCycles++;chunkCursor=currentCity.territory().iterator();cityAdvances++;}return null;}
 private static void cleanup(MinecraftServer server){ThreatSavedData data=ThreatSavedData.get(server);var batch=data.edgeBatch(cleanupCursor,CivitasConfig.THREAT_STALE_EDGES_PER_TICK.get());if(batch.entries().isEmpty()){cleanupCursor=null;return;}for(var entry:batch.entries()){cleanupExamined++;var key=entry.getKey();City city=CitySavedData.get(server).byId(key.cityId()).orElse(null);boolean valid=city!=null&&city.territory().contains(key.chunk())&&!city.territory().contains(TerritoryTopology.adjacent(key.chunk(),key.direction()));if(!valid){if(entry.getValue().invasionId()!=null)for(ServerLevel level:server.getAllLevels())release(level,entry.getValue().invasionId());data.remove(key);cleanupRemoved++;}}cleanupCursor=batch.wrapped()?null:batch.nextCursor();}
 private static void process(MinecraftServer server,EdgeWork work,long now){ServerLevel level=level(server,work.city.dimension());if(level==null)return;ThreatSavedData data=ThreatSavedData.get(server);var key=new ThreatSavedData.EdgeKey(work.city.id(),work.chunk,work.direction);var state=data.get(key,now);
  if(state.phase()==ThreatSavedData.Phase.COOLDOWN){if(now<state.cooldownUntil())return;state=ThreatSavedData.State.calm(now);}
  if(state.phase()==ThreatSavedData.Phase.WAVE){processWave(level,work,key,state,data,now);return;}
  if(state.phase()==ThreatSavedData.Phase.WARNING){var plan=data.infiltrationPlan(key).orElse(null);if(plan==null||!InfiltrationPlanner.revalidate(server,work.city,plan)){data.clearInfiltrationPlan(key);data.put(key,new ThreatSavedData.State(state.pressure(),ThreatSavedData.Phase.OMEN,now,0,0,null,state.failedDefenses(),now));INFILTRATION_RETRY_UNTIL.put(work.city.id(),now+CivitasConfig.INFILTRATION_RETRY_TICKS.get());return;}omen(level,BlockPos.of(plan.selected().position()),0xE8A65A);int warning=CivitasConfig.INVASION_WARNING_TICKS.get()+defense(plan,0).warningBonusTicks();if(now-state.phaseStartedAt()>=warning&&hasOnlineDefender(level,work.city)&&!hasOtherWave(data,key)){UUID id=UUID.randomUUID();var wave=new ThreatSavedData.State(state.pressure(),ThreatSavedData.Phase.WAVE,now,0,1,id,0,state.failedDefenses(),now);data.put(key,wave);SpawnResult spawned=spawnWave(level,work,wave,plan);if(!spawned.mobs().isEmpty()){data.put(key,wave.withRemainingMobs(spawned.mobs().size(),now));if(!InvasionCommitmentManager.create(server,work.city,plan,id,1,spawned.ids(),now)){discard(spawned);data.put(key,new ThreatSavedData.State(CivitasConfig.THREAT_INVASION_THRESHOLD.get(),ThreatSavedData.Phase.OMEN,now,0,0,null,state.failedDefenses(),now));}}else{data.clearInfiltrationPlan(key);data.put(key,new ThreatSavedData.State(CivitasConfig.THREAT_INVASION_THRESHOLD.get(),ThreatSavedData.Phase.OMEN,now,0,0,null,state.failedDefenses(),now));INFILTRATION_RETRY_UNTIL.put(work.city.id(),now+CivitasConfig.INFILTRATION_RETRY_TICKS.get());}}return;}
  BorderReadiness readiness=readiness(level,work);ThreatPressure pressure=new ThreatPressure(state.pressure(),state.lastUpdatedAt(),0,state.failedDefenses());double base=CivitasConfig.THREAT_BASE_PER_TICK.get()*Math.max(1,now-state.lastUpdatedAt());double next=pressure.accumulate(readiness,work.city.territory().size(),now,base,CivitasConfig.THREAT_CITY_SIZE_FACTOR.get()).pressure().value();
  boolean eligible=next>=CivitasConfig.THREAT_INVASION_THRESHOLD.get()&&hasOnlineDefender(level,work.city)&&mayStartWarning(data,key,next)&&now>=INFILTRATION_RETRY_UNTIL.getOrDefault(work.city.id(),0L);if(eligible){var planned=InfiltrationPlanner.plan(server,work.city,now);if(planned.plan().isPresent()){InfiltrationPlan plan=planned.plan().orElseThrow();var defense=defense(plan,level.getRandom().nextDouble());if(defense.intercepted()){infiltrationIntercepted++;data.put(key,new ThreatSavedData.State(0,ThreatSavedData.Phase.COOLDOWN,now,now+CivitasConfig.DEFENSE_BUFFER_TICKS.get(),0,null,state.failedDefenses(),now));recordDefense(level,work,plan.selected().chunk(),TerritoryChunkState.DefenseResult.SUCCESS,now);notifyMembers(level,work.city,"civitas.invasion.intercepted",source(plan));return;}data.put(key,new ThreatSavedData.State(next,ThreatSavedData.Phase.WARNING,now,0,0,null,state.failedDefenses(),now));data.putInfiltrationPlan(key,plan);notifyMembers(level,work.city,"civitas.invasion.warning.source",source(plan));return;}INFILTRATION_RETRY_UNTIL.put(work.city.id(),now+CivitasConfig.INFILTRATION_RETRY_TICKS.get());}
  ThreatSavedData.Phase phase=next>=CivitasConfig.THREAT_OMEN_THRESHOLD.get()?ThreatSavedData.Phase.OMEN:ThreatSavedData.Phase.CALM;long started=phase==state.phase()?state.phaseStartedAt():now;data.put(key,new ThreatSavedData.State(next,phase,started,0,0,null,state.failedDefenses(),now));if(phase==ThreatSavedData.Phase.OMEN)omen(level,work,0xB85C52);
 }
 private static BorderReadiness readiness(ServerLevel level,EdgeWork work){var state=CivilizationSavedData.get(level.getServer()).get(work.city.dimension(),work.chunk,CivilizationLayer.SURFACE);var fort=BoundedBorderScanner.scan(level,work.chunk,work.direction);return BorderReadiness.calculate(state.civility(),state.activity(),state.factors().safety(),fort.score(),readinessWeights());}
 private static int developedChunks(MinecraftServer server,City city){CivilizationSavedData data=CivilizationSavedData.get(server);int count=0;for(long c:city.territory()){var s=data.get(city.dimension(),c,CivilizationLayer.SURFACE);var u=data.get(city.dimension(),c,CivilizationLayer.UNDERGROUND);boolean surface=s.civility()>=CivitasConfig.EXPANSION_CIVILITY_MINIMUM.get()&&s.activity()>=CivitasConfig.EXPANSION_ACTIVITY_MINIMUM.get();boolean underground=u.civility()>=CivitasConfig.EXPANSION_CIVILITY_MINIMUM.get()&&u.activity()>=CivitasConfig.EXPANSION_ACTIVITY_MINIMUM.get();if(surface||underground)count++;}return count;}
 private static void processWave(ServerLevel level,EdgeWork work,ThreatSavedData.EdgeKey key,ThreatSavedData.State state,ThreatSavedData data,long now){InfiltrationPlan plan=data.infiltrationPlan(key).orElse(null);long localChunk=plan==null?work.chunk:plan.selected().chunk();if(plan!=null&&level.hasChunkAt(BlockPos.of(plan.selected().position())))materializeVirtualEnemies(level,work,state,plan,data);switch(WAVE_RULES.evaluate(state.remainingMobs(),state.wave(),Math.max(0,now-state.phaseStartedAt()),CivitasConfig.INVASION_WAVE_TIME_LIMIT_TICKS.get())){case WAIT->{}case SUCCESS->{data.put(key,new ThreatSavedData.State(0,ThreatSavedData.Phase.COOLDOWN,now,now+CivitasConfig.DEFENSE_BUFFER_TICKS.get(),0,null,0,state.failedDefenses(),now));patrolGain(level,localChunk);recordDefense(level,work,localChunk,TerritoryChunkState.DefenseResult.SUCCESS,now);notifyMembers(level,work.city,"civitas.invasion.success");}case ADVANCE->{var next=new ThreatSavedData.State(state.pressure(),ThreatSavedData.Phase.WAVE,now,0,state.wave()+1,state.invasionId(),0,state.failedDefenses(),now);var commitment=data.invasionCommitment(state.invasionId()).orElse(null);if(commitment!=null&&plan!=null&&!level.hasChunkAt(BlockPos.of(plan.selected().position()))){List<UUID>virtual=virtualEnemyIds(state.invasionId(),next.wave(),waveAmount(level,work,next,plan));data.put(key,next.withRemainingMobs(virtual.size(),now));if(!InvasionCommitmentManager.beginWave(data,state.invasionId(),next.wave(),virtual,now))data.put(key,new ThreatSavedData.State(CivitasConfig.THREAT_INVASION_THRESHOLD.get(),ThreatSavedData.Phase.OMEN,now,0,0,null,state.failedDefenses(),now));break;}SpawnResult spawned=spawnWave(level,work,next,plan);if(!spawned.mobs().isEmpty()){data.put(key,next.withRemainingMobs(spawned.mobs().size(),now));if(!InvasionCommitmentManager.beginWave(data,state.invasionId(),next.wave(),spawned.ids(),now)){discard(spawned);data.put(key,new ThreatSavedData.State(CivitasConfig.THREAT_INVASION_THRESHOLD.get(),ThreatSavedData.Phase.OMEN,now,0,0,null,state.failedDefenses(),now));}}else{data.clearInfiltrationPlan(key);data.put(key,new ThreatSavedData.State(CivitasConfig.THREAT_INVASION_THRESHOLD.get(),ThreatSavedData.Phase.OMEN,now,0,0,null,state.failedDefenses(),now));INFILTRATION_RETRY_UNTIL.put(work.city.id(),now+CivitasConfig.INFILTRATION_RETRY_TICKS.get());}}case FAILURE->{release(level,state.invasionId());data.put(key,new ThreatSavedData.State(CivitasConfig.THREAT_OMEN_THRESHOLD.get(),ThreatSavedData.Phase.COOLDOWN,now,now+CivitasConfig.FAILED_DEFENSE_COOLDOWN_TICKS.get(),0,null,0,state.failedDefenses()+1,now));recordDefense(level,work,localChunk,TerritoryChunkState.DefenseResult.FAILURE,now);notifyMembers(level,work.city,"civitas.invasion.failed");}}}
 private static SpawnResult spawnWave(ServerLevel level,EdgeWork work,ThreatSavedData.State state,InfiltrationPlan plan){int amount=waveAmount(level,work,state,plan);ArrayList<Mob>spawned=new ArrayList<>();for(int i=0;i<amount;i++){Mob mob=createEnemy(level,i);if(mob==null)continue;BlockPos pos=plan==null?spawnPos(level,work,i):infiltrationSpawn(level,work,plan,i);if(pos==null)continue;if(addEnemy(level,mob,pos,state.invasionId()))spawned.add(mob);}if(!spawned.isEmpty())notifyMembers(level,work.city,"civitas.invasion.wave",state.wave());return new SpawnResult(List.copyOf(spawned));}
 private static int waveAmount(ServerLevel level,EdgeWork work,ThreatSavedData.State state,InfiltrationPlan plan){int defenders=(int)level.players().stream().filter(p->work.city.isMember(p.getUUID())).count();int base=Math.max(1,CivitasConfig.INVASION_BASE_WAVE_SIZE.get()+developedChunks(level.getServer(),work.city)/CivitasConfig.INVASION_PER_DEVELOPED_DIVISOR.get()+state.wave()*CivitasConfig.INVASION_PER_WAVE.get()-defenders*CivitasConfig.INVASION_PER_DEFENDER_REDUCTION.get());double scale=plan==null?1:defense(plan,0).waveScale();return Math.min(CivitasConfig.INVASION_WAVE_CAP.get(),Math.max(1,(int)Math.round(base*scale)));}
 private static Mob createEnemy(ServerLevel level,int index){return (index%3==0?EntityType.SKELETON:EntityType.ZOMBIE).create(level,EntitySpawnReason.EVENT);}
 private static boolean addEnemy(ServerLevel level,Mob mob,BlockPos pos,UUID invasion){mob.snapTo(pos.getX()+.5,pos.getY(),pos.getZ()+.5,level.getRandom().nextFloat()*360,0);if(!level.noCollision(mob,mob.getBoundingBox()))return false;mob.setPersistenceRequired();InvasionMobMarker.mark(mob,invasion);if(level.addFreshEntity(mob))return true;InvasionMobIndex.unregister(mob);InvasionMobMarker.release(mob);return false;}
 private static List<UUID>virtualEnemyIds(UUID invasion,int wave,int amount){ArrayList<UUID>ids=new ArrayList<>(amount);for(int i=0;i<amount;i++)ids.add(virtualEnemyId(invasion,wave,i));return List.copyOf(ids);}
 private static UUID virtualEnemyId(UUID invasion,int wave,int index){return UUID.nameUUIDFromBytes(("civitas:virtual_invasion:"+invasion+":"+wave+":"+index).getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 private static void materializeVirtualEnemies(ServerLevel level,EdgeWork work,ThreatSavedData.State state,InfiltrationPlan plan,ThreatSavedData data){var commitment=data.invasionCommitment(state.invasionId()).orElse(null);if(commitment==null)return;int cap=CivitasConfig.VIRTUAL_INVASION_MATERIALIZATIONS_PER_TICK.get(),examined=0;Set<UUID>virtual=new HashSet<>(virtualEnemyIds(state.invasionId(),state.wave(),CivitasConfig.INVASION_WAVE_CAP.get()));for(UUID id:commitment.survivingEnemyIds()){if(examined>=cap)break;if(!virtual.contains(id)||level.getEntity(id)!=null)continue;examined++;Mob mob=createEnemy(level,examined-1);if(mob==null)continue;mob.setUUID(id);BlockPos pos=infiltrationSpawn(level,work,plan,examined-1);if(pos!=null)addEnemy(level,mob,pos,state.invasionId());}}
 private static void discard(SpawnResult result){for(Mob mob:result.mobs()){InvasionMobIndex.unregister(mob);mob.discard();}}
 private static BlockPos spawnPos(ServerLevel level,EdgeWork work,int index){ChunkCoordinate c=ChunkCoordinate.unpack(work.chunk);int baseX=(c.x()<<4)+8,baseZ=(c.z()<<4)+8;int offset=10+index%6;int x=baseX+(work.direction==TerritoryTopology.Direction.EAST?offset:work.direction==TerritoryTopology.Direction.WEST?-offset:index%7-3);int z=baseZ+(work.direction==TerritoryTopology.Direction.SOUTH?offset:work.direction==TerritoryTopology.Direction.NORTH?-offset:index%7-3);return new BlockPos(x,level.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,x,z),z);}
 private static BlockPos infiltrationSpawn(ServerLevel level,EdgeWork work,InfiltrationPlan plan,int index){BlockPos base=BlockPos.of(plan.selected().position());int attempts=CivitasConfig.INFILTRATION_LOCAL_SPAWN_ATTEMPTS.get();for(int attempt=0;attempt<attempts;attempt++){infiltrationSpawnSamples++;int n=index+attempt;int radius=n==0?0:1+n/8;int slot=n%8;int dx=switch(slot){case 0,1,7->radius;case 3,4,5->-radius;default->0;};int dz=switch(slot){case 1,2,3->radius;case 5,6,7->-radius;default->0;};BlockPos pos=base.offset(dx,0,dz);if(legalInfiltrationSpawn(level,work.city,pos))return pos;}infiltrationSpawnRejected++;return null;}
 private static boolean legalInfiltrationSpawn(ServerLevel level,City city,BlockPos pos){if(!level.isInWorldBounds(pos)||!level.hasChunkAt(pos)||!level.getBlockState(pos).getCollisionShape(level,pos).isEmpty()||!level.getBlockState(pos.above()).getCollisionShape(level,pos.above()).isEmpty()||!level.getBlockState(pos.below()).blocksMotion()||!level.getFluidState(pos).isEmpty()||!level.getFluidState(pos.above()).isEmpty())return false;long chunk=net.minecraft.world.level.ChunkPos.pack(pos);var page=BuildingSavedData.get(level.getServer()).recordsInChunk(city.id(),city.dimension(),chunk,CivitasConfig.SECURITY_BUILDING_RECORD_LIMIT_PER_CELL.get());if(page.truncated())return false;long packed=pos.asLong();return page.records().stream().noneMatch(r->r.status()==com.seaquake6324.civitas.domain.building.BuildingStatus.VALID&&r.cells().contains(packed));}
 private static InfiltrationDefenseRules.Result defense(InfiltrationPlan plan,double draw){return INFILTRATION_DEFENSE.evaluate(plan.selected().securityRisk(),draw,CivitasConfig.INFILTRATION_MAX_WARNING_BONUS_TICKS.get(),CivitasConfig.INFILTRATION_MINIMUM_WAVE_SCALE.get());}
 private static Component source(InfiltrationPlan plan){return Component.translatable("civitas.infiltration.source."+plan.selected().source().name().toLowerCase(Locale.ROOT));}
 public static BlockPos previewSpawn(ServerLevel level,City city,long chunk,TerritoryTopology.Direction direction){return spawnPos(level,new EdgeWork(city,chunk,direction),0);}
 private static int countMobs(ServerLevel level,UUID id){var count=InvasionMobIndex.count(level,id);return count.incomplete()?Math.max(1,count.loadedAlive()):count.loadedAlive();}
 private static void release(ServerLevel level,UUID id){InvasionMobIndex.release(level,id);}
 private static void patrolGain(ServerLevel level,long chunk){CivilizationSavedData data=CivilizationSavedData.get(level.getServer());String dim=level.dimension().identifier().toString();var state=data.get(dim,chunk,CivilizationLayer.SURFACE);data.put(dim,chunk,CivilizationLayer.SURFACE,state.withActivity(state.activity()+CivitasConfig.PATROL_ACTIVITY_GAIN.get(),level.getGameTime()));}
 private static void recordDefense(ServerLevel level,EdgeWork work,long localChunk,TerritoryChunkState.DefenseResult result,long now){CitySavedData repo=CitySavedData.get(level.getServer());City current=repo.byId(work.city.id()).orElse(null);if(current==null)return;long target=current.territory().contains(localChunk)?localChunk:work.chunk;TerritoryChunkState state=current.territoryStates().get(target);if(state!=null)repo.add(current.withTerritoryState(target,state.withDefense(result,now)));}
 private static boolean hasOnlineDefender(ServerLevel level,City city){return level.players().stream().anyMatch(p->city.isMember(p.getUUID()));}
 private static boolean hasOtherWave(ThreatSavedData data,ThreatSavedData.EdgeKey key){var page=data.edgePage(key.cityId(),CivitasConfig.THREAT_EDGE_QUERY_LIMIT.get());if(page.entries().stream().anyMatch(e->!e.getKey().equals(key)&&e.getValue().phase()==ThreatSavedData.Phase.WAVE))return true;return page.truncated();}
 private static boolean mayStartWarning(ThreatSavedData data,ThreatSavedData.EdgeKey key,double pressure){var page=data.edgePage(key.cityId(),CivitasConfig.THREAT_EDGE_QUERY_LIMIT.get());if(page.truncated())return false;for(var entry:page.entries()){if(entry.getKey().equals(key))continue;if(entry.getValue().phase()==ThreatSavedData.Phase.WARNING||entry.getValue().phase()==ThreatSavedData.Phase.WAVE)return false;if(entry.getValue().pressure()>pressure)return false;if(entry.getValue().pressure()==pressure&&edgeOrder(entry.getKey(),key)<0)return false;}return true;}
 private static int edgeOrder(ThreatSavedData.EdgeKey a,ThreatSavedData.EdgeKey b){int chunk=Long.compare(a.chunk(),b.chunk());return chunk!=0?chunk:Integer.compare(a.direction().ordinal(),b.direction().ordinal());}
 private static void notifyMembers(ServerLevel level,City city,String key,Object...args){for(ServerPlayer player:level.players())if(city.isMember(player.getUUID()))player.sendSystemMessage(Component.translatable(key,args),true);}
 private static void omen(ServerLevel level,EdgeWork work,int color){ChunkCoordinate c=ChunkCoordinate.unpack(work.chunk);double x=(c.x()<<4)+8,z=(c.z()<<4)+8;int y=level.getHeight(Heightmap.Types.MOTION_BLOCKING,(int)x,(int)z);level.sendParticles(new DustParticleOptions(color,1F),x,y+1,z,4,2,.5,2,.01);if(level.getGameTime()%200==0)level.playSound(null,new BlockPos((int)x,y,(int)z),SoundEvents.AMBIENT_CAVE.value(),SoundSource.HOSTILE,.45F,.72F);}
 private static void omen(ServerLevel level,BlockPos pos,int color){level.sendParticles(new DustParticleOptions(color,1F),pos.getX()+.5,pos.getY()+1,pos.getZ()+.5,4,2,.5,2,.01);if(level.getGameTime()%200==0)level.playSound(null,pos,SoundEvents.AMBIENT_CAVE.value(),SoundSource.HOSTILE,.45F,.72F);}
 private static ServerLevel level(MinecraftServer server,String dimension){for(ServerLevel level:server.getAllLevels())if(level.dimension().identifier().toString().equals(dimension))return level;return null;}
 private static BorderReadiness.Weights readinessWeights(){return new BorderReadiness.Weights(CivitasConfig.READINESS_CIVILITY_WEIGHT.get(),CivitasConfig.READINESS_ACTIVITY_WEIGHT.get(),CivitasConfig.READINESS_SAFETY_WEIGHT.get(),CivitasConfig.READINESS_FORTIFICATION_WEIGHT.get());}
 public static Snapshot snapshot(MinecraftServer server,UUID cityId){return ThreatSavedData.get(server).edgePage(cityId,CivitasConfig.THREAT_EDGE_QUERY_LIMIT.get()).entries().stream().max(Comparator.comparingDouble(e->e.getValue().pressure())).map(e->new Snapshot(e.getKey().chunk(),e.getKey().direction(),e.getValue())).orElse(null);}
 public static void removeCity(MinecraftServer server,UUID cityId){ThreatSavedData data=ThreatSavedData.get(server);var page=data.edgePage(cityId,CivitasConfig.THREAT_EDGE_QUERY_LIMIT.get());for(var entry:page.entries())if(entry.getValue().invasionId()!=null)for(ServerLevel level:server.getAllLevels())release(level,entry.getValue().invasionId());data.removeCity(cityId);}
 public record Snapshot(long chunk,TerritoryTopology.Direction direction,ThreatSavedData.State state){}
 public static Metrics metrics(){var mobs=InvasionMobIndex.metrics();return new Metrics(ticks,chunksExamined,edgesProcessed,cityCycles,cleanupExamined,cleanupRemoved,infiltrationIntercepted,infiltrationSpawnSamples,infiltrationSpawnRejected,ticks==0?0:totalMicros/ticks,maxMicros,mobs.retained(),mobs.invasions(),mobs.overflow(),mobs.rejections(),mobs.staleRemoved());}
 public record Metrics(long ticks,long chunksExamined,long edgesProcessed,long cityCycles,long cleanupExamined,long cleanupRemoved,long infiltrationIntercepted,long infiltrationSpawnSamples,long infiltrationSpawnRejected,long averageMicros,long maxMicros,int indexedMobs,int indexedInvasions,boolean mobIndexOverflow,long mobIndexRejections,long staleMobsRemoved){}
 private static void reset(MinecraftServer server){owner=server;cityCursor=null;currentCity=null;chunkCursor=null;cleanupCursor=null;INFILTRATION_RETRY_UNTIL.clear();ticks=chunksExamined=edgesProcessed=cityCycles=cleanupExamined=cleanupRemoved=infiltrationIntercepted=infiltrationSpawnSamples=infiltrationSpawnRejected=totalMicros=maxMicros=0;InvasionMobIndex.clear();}
 private record ChunkWork(City city,long chunk){}
 private record EdgeWork(City city,long chunk,TerritoryTopology.Direction direction){}
 private record SpawnResult(List<Mob>mobs){List<UUID>ids(){return mobs.stream().map(Entity::getUUID).toList();}}
 private BorderThreatManager(){}
}
