package com.seaquake6324.civitas.infrastructure.config;

import java.util.List;
import com.seaquake6324.civitas.domain.security.PatrolRoute;
import com.seaquake6324.civitas.domain.security.InfiltrationPlan;
import com.seaquake6324.civitas.domain.security.InvasionCommitment;
import net.neoforged.neoforge.common.ModConfigSpec;

public final class CivitasConfig {
    public static final ModConfigSpec SPEC;
    public static final ModConfigSpec.IntValue MINIMUM_CORE_DISTANCE_CHUNKS;
    public static final ModConfigSpec.IntValue BORDER_BUFFER_CHUNKS;
    public static final ModConfigSpec.ConfigValue<List<? extends String>> ALLOWED_DIMENSIONS;
    public static final ModConfigSpec.BooleanValue SERVER_WIDE_ANNOUNCEMENTS;
    public static final ModConfigSpec.DoubleValue NATURAL_SPAWN_MULTIPLIER;
    public static final ModConfigSpec.ConfigValue<List<? extends String>> CIVILITY_SUPPRESSION_CURVE;
    public static final ModConfigSpec.DoubleValue CIVILITY_GROWTH_PER_CYCLE;
    public static final ModConfigSpec.DoubleValue CIVILITY_DECLINE_PER_CYCLE;
    public static final ModConfigSpec.IntValue CIVILITY_STABILITY_TICKS;
    public static final ModConfigSpec.IntValue CIVILITY_SCAN_BUDGET_MICROS;
    public static final ModConfigSpec.IntValue ACTIVITY_WINDOW_TICKS;
    public static final ModConfigSpec.IntValue ACTIVITY_MOVEMENT_SAMPLE_TICKS;
    public static final ModConfigSpec.IntValue ACTIVITY_MOVEMENT_CELL_SIZE;
    public static final ModConfigSpec.IntValue ACTIVITY_GRACE_TICKS;
    public static final ModConfigSpec.DoubleValue ACTIVITY_DECAY_PER_WINDOW;
    public static final ModConfigSpec.DoubleValue ACTIVITY_GAIN_PER_CATEGORY;
    public static final ModConfigSpec.DoubleValue ACTIVITY_PROPAGATION_RATIO;
    public static final ModConfigSpec.DoubleValue ACTIVITY_PROPAGATION_CAP;
    public static final ModConfigSpec.DoubleValue ACTIVITY_LOCAL_GAIN_CAP;
    public static final ModConfigSpec.IntValue REGION_SURFACE_PATH;
    public static final ModConfigSpec.IntValue REGION_INTERIOR_PATH;
    public static final ModConfigSpec.IntValue REGION_SHALLOW_DEPTH;
    public static final ModConfigSpec.IntValue REGION_UNDERGROUND_DEPTH;
    public static final ModConfigSpec.IntValue REGION_THIN_COVERAGE;
    public static final ModConfigSpec.IntValue REGION_UNDERGROUND_COVERAGE;
    public static final ModConfigSpec.IntValue REGION_HORIZONTAL_RADIUS;
    public static final ModConfigSpec.IntValue REGION_VERTICAL_RADIUS;
    public static final ModConfigSpec.IntValue REGION_NODE_LIMIT;
    public static final ModConfigSpec.DoubleValue REGION_ENCLOSURE_THRESHOLD;
    public static final ModConfigSpec.DoubleValue REGION_UNDERGROUND_SCORE;
    public static final ModConfigSpec.DoubleValue EXPANSION_CIVILITY_MINIMUM;
    public static final ModConfigSpec.DoubleValue EXPANSION_ACTIVITY_MINIMUM;
    public static final ModConfigSpec.DoubleValue EXPANSION_DEVELOPED_COVERAGE;
    public static final ModConfigSpec.DoubleValue EXPANSION_ACTIVE_COVERAGE;
    public static final ModConfigSpec.IntValue EXPANSION_COOLDOWN_TICKS;
    public static final ModConfigSpec.IntValue NEGLECT_WARNING_TICKS;
    public static final ModConfigSpec.IntValue NEGLECT_ABANDONED_TICKS;
    public static final ModConfigSpec.IntValue NEGLECT_RETRACTABLE_TICKS;
    public static final ModConfigSpec.IntValue NEGLECT_RECOVERY_TICKS;
    public static final ModConfigSpec.DoubleValue NEGLECT_CIVILITY_MINIMUM;
    public static final ModConfigSpec.DoubleValue NEGLECT_ACTIVITY_MINIMUM;
    public static final ModConfigSpec.IntValue OFFLINE_GRACE_SECONDS;
    public static final ModConfigSpec.DoubleValue THREAT_BASE_PER_TICK;
    public static final ModConfigSpec.DoubleValue THREAT_CITY_SIZE_FACTOR;
    public static final ModConfigSpec.IntValue DEFENSE_BUFFER_TICKS;
    public static final ModConfigSpec.IntValue INVASION_WARNING_TICKS;
    public static final ModConfigSpec.IntValue INVASION_WAVE_CAP;
    public static final ModConfigSpec.DoubleValue CIVILITY_BUILDING_WEIGHT,CIVILITY_FACILITIES_WEIGHT,CIVILITY_SAFETY_WEIGHT,CIVILITY_CONNECTIVITY_WEIGHT;
    public static final ModConfigSpec.DoubleValue READINESS_CIVILITY_WEIGHT,READINESS_ACTIVITY_WEIGHT,READINESS_SAFETY_WEIGHT,READINESS_FORTIFICATION_WEIGHT;
    public static final ModConfigSpec.IntValue INVASION_BASE_WAVE_SIZE,INVASION_PER_DEVELOPED_DIVISOR,INVASION_PER_WAVE,INVASION_PER_DEFENDER_REDUCTION;
    public static final ModConfigSpec.DoubleValue THREAT_OMEN_THRESHOLD,THREAT_INVASION_THRESHOLD,PATROL_ACTIVITY_GAIN,FAILED_DEFENSE_NEGLECT_MULTIPLIER;
    public static final ModConfigSpec.IntValue INVASION_WAVE_TIME_LIMIT_TICKS,FAILED_DEFENSE_COOLDOWN_TICKS,THREAT_EDGE_QUERY_LIMIT,THREAT_BORDER_CHUNKS_PER_TICK,THREAT_STALE_EDGES_PER_TICK,THREAT_MOB_INDEX_CAP;
    public static final ModConfigSpec.DoubleValue FORT_WALL_WEIGHT,FORT_ENTRANCE_WEIGHT,FORT_GATE_WEIGHT,FORT_PATH_WEIGHT,FORT_GAP_PENALTY;
    public static final ModConfigSpec.IntValue BUILDING_SCAN_CELL_LIMIT,BUILDING_SCAN_HORIZONTAL_RADIUS,BUILDING_SCAN_VERTICAL_RADIUS;
    public static final ModConfigSpec.IntValue BUILDING_REVALIDATION_QUEUE_LIMIT,BUILDING_REVALIDATION_PER_TICK,BUILDING_DASHBOARD_SCAN_LIMIT,BUILDING_DASHBOARD_RECORD_LIMIT,BUILDING_STORAGE_AUTHORIZATION_TICKS,BUILDING_STORAGE_AUTHORIZATION_SESSIONS;
    public static final ModConfigSpec.IntValue POPULATION_TICKS_PER_YEAR,POPULATION_ADOLESCENT_AT,POPULATION_YOUNG_ADULT_AT,POPULATION_MATURE_ADULT_AT,POPULATION_ELDER_AT;
    public static final ModConfigSpec.IntValue POPULATION_AGING_INTERVAL_TICKS,POPULATION_AGING_BATCH_SIZE,POPULATION_MIN_LIFESPAN_YEARS,POPULATION_MAX_LIFESPAN_YEARS;
    public static final ModConfigSpec.IntValue POPULATION_WORKER_THREADS,POPULATION_WORK_QUEUE_CAP,POPULATION_INTENT_QUEUE_CAP,POPULATION_INTENTS_APPLY_PER_TICK,POPULATION_INTENT_MAX_AGE_TICKS;
    public static final ModConfigSpec.IntValue POPULATION_DASHBOARD_SCAN_LIMIT;
    public static final ModConfigSpec.IntValue MARRIAGE_PROPOSAL_DURATION_TICKS,MARRIAGE_PROPOSAL_COOLDOWN_TICKS,MARRIAGE_MAX_STORED_PROPOSALS,MARRIAGE_MAINTENANCE_INTERVAL_TICKS,MARRIAGE_MAINTENANCE_BATCH_SIZE,MARRIAGE_TERMINAL_RETENTION_TICKS,HOUSEHOLD_CHILD_CAPACITY,NPC_MARRIAGE_INTERVAL_TICKS,NPC_MARRIAGE_SCAN_BATCH,NPC_MARRIAGE_PAIRS_PER_RUN;
    public static final ModConfigSpec.DoubleValue MARRIAGE_NPC_WILLINGNESS_MINIMUM;
    public static final ModConfigSpec.IntValue REPRODUCTION_INTERVAL_TICKS,REPRODUCTION_HOUSEHOLDS_PER_RUN,REPRODUCTION_CITIZEN_SCAN_BATCH,REPRODUCTION_PAIRS_PER_RUN,REPRODUCTION_CONDITION_SCAN_LIMIT,REPRODUCTION_CASUALTY_RECOVERY_TICKS,PREGNANCY_DURATION_TICKS,BIRTH_COOLDOWN_TICKS,PREGNANCY_RECORD_CAP,PREGNANCIES_PER_TICK,HOUSEHOLD_CHILD_SAFETY_CAP,PARENTAGE_PER_DEATH,REPRODUCTION_CONSENT_DURATION_TICKS,REPRODUCTION_CONSENT_CAP;
    public static final ModConfigSpec.DoubleValue REPRODUCTION_HOUSING_WEIGHT,REPRODUCTION_FOOD_WEIGHT,REPRODUCTION_SAFETY_WEIGHT,REPRODUCTION_CIVILITY_WEIGHT,REPRODUCTION_ACTIVITY_WEIGHT,REPRODUCTION_FAMILY_WEIGHT,REPRODUCTION_CASUALTY_WEIGHT,REPRODUCTION_UNCROWDED_WEIGHT;
    public static final ModConfigSpec.IntValue ADOPTION_INTERVAL_TICKS,ADOPTION_ORPHANS_PER_RUN,ADOPTION_CANDIDATES_PER_ORPHAN,ADOPTION_MAX_DISTANCE_BLOCKS,ADOPTION_CONSENT_TICKS,ADOPTION_CONSENT_CAP,ADOPTION_CONSENT_MAINTENANCE_BATCH;
    public static final ModConfigSpec.IntValue MIGRATION_INTERVAL_TICKS,MIGRATION_ACTIVE_GROUP_CAP,MIGRATION_GROUPS_PER_TICK,MIGRATION_DECISION_TICKS,MIGRATION_ACTIVATION_DISTANCE,MIGRATION_ARRIVAL_DISTANCE,MIGRATION_MAX_MEMBERS,MIGRATION_EDGE_CHUNKS_SCAN_LIMIT,MIGRATION_SAFE_COLUMNS;
    public static final ModConfigSpec.DoubleValue MIGRATION_COUPLE_CHANCE,MIGRATION_CHILD_CHANCE,MIGRATION_SECOND_CHILD_CHANCE;
    public static final ModConfigSpec.IntValue OUT_MIGRATION_INTERVAL_TICKS,OUT_MIGRATION_HOUSEHOLDS_PER_RUN,OUT_MIGRATION_CITIZENS_PER_RUN,OUT_MIGRATION_STARTS_PER_RUN;
    public static final ModConfigSpec.DoubleValue OUT_MIGRATION_MAX_CHANCE;
    public static final ModConfigSpec.IntValue NPC_MATERIALIZE_DISTANCE,NPC_PREWARM_DISTANCE,NPC_EXIT_DISTANCE,NPC_PREWARM_TICKS,NPC_PREWARM_TIMEOUT_TICKS,NPC_PREWARM_CAP,NPC_MATERIALIZATION_BATCH_SIZE,NPC_ENTITY_CAP,NPC_EQUIPMENT_DEATH_DROPS_PER_TICK;
    public static final ModConfigSpec.IntValue SECURITY_CELLS_PER_TICK,SECURITY_QUEUE_LIMIT,SECURITY_REFRESH_TICKS,SECURITY_TOPOLOGY_VISIT_LIMIT,SECURITY_FAILURE_MEMORY_TICKS,SECURITY_FULL_SCALE_CHUNKS;
    public static final ModConfigSpec.IntValue SECURITY_BUILDING_RECORD_LIMIT_PER_CELL,INFILTRATION_WORLD_SAMPLES_PER_CELL,INFILTRATION_CANDIDATES_PER_CELL,INFILTRATION_EVENT_CELL_CAP,INFILTRATION_EVENT_CANDIDATE_CAP,INFILTRATION_RETRY_TICKS,INFILTRATION_MAX_WARNING_BONUS_TICKS,INFILTRATION_LOCAL_SPAWN_ATTEMPTS,INFILTRATION_BORDER_SAMPLES_PER_EDGE,INFILTRATION_UNDERGROUND_COLUMNS_PER_CELL,INFILTRATION_VERTICAL_DEPTH,INFILTRATION_CAVE_MOUTH_DISTANCE;
    public static final ModConfigSpec.IntValue PATROL_ROUTE_CITY_CAP,PATROL_ROUTE_NODE_CAP,PATROL_ROUTE_SEGMENT_BLOCKS,PATROL_ROUTE_PATH_SAMPLE_CAP,PATROL_ROUTE_SESSION_TICKS;
    public static final ModConfigSpec.IntValue PATROL_ASSIGNMENT_CITY_CAP,PATROL_ASSIGNMENTS_PER_TICK,PATROL_VISIBLE_DRIVES_PER_TICK,PATROL_COVERAGE_MEMORY_TICKS,PATROL_VIRTUAL_NODE_TICKS;
    public static final ModConfigSpec.IntValue BACKGROUND_BATTLES_PER_TICK,BACKGROUND_BATTLE_ROUND_TICKS,BACKGROUND_BATTLE_PARTICIPANT_CAP,BACKGROUND_BATTLE_CITIZEN_SCAN_CAP,BACKGROUND_BATTLE_CIVILIAN_RADIUS,BACKGROUND_BATTLE_CIVILIAN_CAP,BACKGROUND_BATTLE_TARGETS_PER_ROUND,BACKGROUND_BATTLE_MAX_DAMAGE_PER_ROUND,BACKGROUND_BATTLE_CIVILIAN_EXPOSURE_ROUND,VISIBLE_INVASION_MOBS_PER_TICK,VISIBLE_INVASION_TARGET_RADIUS,VIRTUAL_INVASION_MATERIALIZATIONS_PER_TICK;
    public static final ModConfigSpec.DoubleValue GUARD_MINIMUM_WILLINGNESS,PATROL_NODE_REACH_DISTANCE,GUARD_SETTLEMENT_WEIGHT,GUARD_SAFETY_WEIGHT,GUARD_WEAPON_WEIGHT,GUARD_ARMOR_WEIGHT,GUARD_SHIELD_WEIGHT,GUARD_SHIFT_WEIGHT,GUARD_RELIABILITY_WEIGHT;
    public static final ModConfigSpec.DoubleValue SECURITY_CIVILITY_WEIGHT,SECURITY_ACTIVITY_WEIGHT,SECURITY_BUILT_SAFETY_WEIGHT,SECURITY_PATROL_WEIGHT,SECURITY_GUARD_WEIGHT,SECURITY_INFILTRATION_WEIGHT,SECURITY_UNDERGROUND_WEIGHT,SECURITY_BORDER_WEIGHT,SECURITY_NEGLECT_WEIGHT,SECURITY_FAILURE_WEIGHT,SECURITY_CITY_SCALE_WEIGHT;
    public static final ModConfigSpec.DoubleValue INFILTRATION_GUARDED_THRESHOLD,INFILTRATION_UNCONTROLLED_ENTRANCE_WEIGHT,INFILTRATION_WALL_GAP_WEIGHT,INFILTRATION_CAVE_WEIGHT,INFILTRATION_UNDERGROUND_DARKNESS_WEIGHT,INFILTRATION_DISGUISED_ENTRY_WEIGHT,INFILTRATION_SECURITY_COMPONENT_WEIGHT,INFILTRATION_DARKNESS_COMPONENT_WEIGHT,INFILTRATION_UNGUARDED_COMPONENT_WEIGHT,INFILTRATION_MINIMUM_WAVE_SCALE;
    public static final ModConfigSpec.DoubleValue BACKGROUND_BATTLE_WEAPON_POWER,BACKGROUND_BATTLE_ENEMY_DURABILITY,BACKGROUND_BATTLE_ENEMY_DAMAGE,BACKGROUND_BATTLE_ARMOR_REDUCTION_PER_PIECE,BACKGROUND_BATTLE_SHIELD_REDUCTION,BACKGROUND_BATTLE_MAXIMUM_REDUCTION;

    static {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();
        builder.push("founding");
        MINIMUM_CORE_DISTANCE_CHUNKS = builder.comment("Minimum Chebyshev distance between city core chunks.")
                .defineInRange("minimumCoreDistanceChunks", 16, 1, 1024);
        BORDER_BUFFER_CHUNKS = builder.comment("Unclaimed chunk buffer required around every city's territory.")
                .defineInRange("borderBufferChunks", 4, 0, 64);
        ALLOWED_DIMENSIONS = builder.comment("Dimension ids in which cities may be founded.")
                .defineListAllowEmpty("allowedDimensions", List.of("minecraft:overworld"), value -> value instanceof String text && text.contains(":"));
        SERVER_WIDE_ANNOUNCEMENTS = builder.comment("Show a HUD announcement to all players when a city is founded. Disabled by default; never uses chat.")
                .define("serverWideAnnouncements", false);
        builder.pop();
        builder.push("territoryLifecycle");
        builder.push("expansion");
        EXPANSION_CIVILITY_MINIMUM=builder.defineInRange("civilityMinimum",40.0,0.0,100.0);
        EXPANSION_ACTIVITY_MINIMUM=builder.defineInRange("activityMinimum",20.0,0.0,100.0);
        EXPANSION_DEVELOPED_COVERAGE=builder.defineInRange("developedCoverage",0.5,0.0,1.0);
        EXPANSION_ACTIVE_COVERAGE=builder.defineInRange("activeCoverage",1.0/3.0,0.0,1.0);
        EXPANSION_COOLDOWN_TICKS=builder.defineInRange("cooldownTicks",12000,0,720000);
        builder.pop();
        builder.push("neglect");
        NEGLECT_CIVILITY_MINIMUM=builder.defineInRange("civilityMinimum",20.0,0.0,100.0);
        NEGLECT_ACTIVITY_MINIMUM=builder.defineInRange("activityMinimum",20.0,0.0,100.0);
        NEGLECT_WARNING_TICKS=builder.defineInRange("warningTicks",72000,20,Integer.MAX_VALUE);
        NEGLECT_ABANDONED_TICKS=builder.defineInRange("abandonedTicks",432000,20,Integer.MAX_VALUE);
        NEGLECT_RETRACTABLE_TICKS=builder.defineInRange("retractableTicks",1728000,20,Integer.MAX_VALUE);
        NEGLECT_RECOVERY_TICKS=builder.defineInRange("recoveryTicks",12000,20,720000);
        FAILED_DEFENSE_NEGLECT_MULTIPLIER=builder.defineInRange("failedDefenseTimeMultiplier",.75,.1,1.0);
        OFFLINE_GRACE_SECONDS=builder.comment("Real-time offline grace; server downtime only advances this clock.").defineInRange("offlineGraceSeconds",604800,0,Integer.MAX_VALUE);
        builder.pop();
        builder.push("threat");
        THREAT_BASE_PER_TICK=builder.defineInRange("basePressurePerTick",0.00025,0.0,10.0);
        THREAT_CITY_SIZE_FACTOR=builder.defineInRange("citySizeFactor",0.08,0.0,10.0);
        THREAT_OMEN_THRESHOLD=builder.defineInRange("omenThreshold",65.0,0.0,100.0);THREAT_INVASION_THRESHOLD=builder.defineInRange("invasionThreshold",100.0,0.0,100.0);
        THREAT_EDGE_QUERY_LIMIT=builder.comment("Hard cap on persisted threat edges examined by one city query; truncated safety checks fail closed.").defineInRange("edgeQueryLimit",16384,64,262144);
        THREAT_BORDER_CHUNKS_PER_TICK=builder.comment("Maximum territory chunks examined by the rotating border scheduler each threat tick.").defineInRange("borderChunksPerTick",32,1,4096);
        THREAT_STALE_EDGES_PER_TICK=builder.comment("Maximum persisted threat edges topology-checked for cleanup each threat tick.").defineInRange("staleEdgesPerTick",16,1,1024);
        THREAT_MOB_INDEX_CAP=builder.comment("Hard cap on loaded invasion mobs retained in the event-maintained index; overflow fails closed.").defineInRange("mobIndexCap",4096,32,65536);
        DEFENSE_BUFFER_TICKS=builder.defineInRange("successfulDefenseBufferTicks",24000,0,Integer.MAX_VALUE);
        INVASION_WARNING_TICKS=builder.defineInRange("warningTicks",2400,20,72000);
        INVASION_WAVE_CAP=builder.defineInRange("waveEntityCap",32,1,256);
        INVASION_BASE_WAVE_SIZE=builder.defineInRange("baseWaveSize",4,1,128);
        INVASION_PER_DEVELOPED_DIVISOR=builder.defineInRange("oneMobPerDevelopedChunks",3,1,128);
        INVASION_PER_WAVE=builder.defineInRange("additionalMobsPerWave",2,0,64);
        INVASION_PER_DEFENDER_REDUCTION=builder.defineInRange("reductionPerOnlineDefender",1,0,32);
        INVASION_WAVE_TIME_LIMIT_TICKS=builder.defineInRange("waveTimeLimitTicks",3600,20,72000);FAILED_DEFENSE_COOLDOWN_TICKS=builder.defineInRange("failedDefenseCooldownTicks",6000,0,720000);PATROL_ACTIVITY_GAIN=builder.defineInRange("successfulPatrolActivityGain",2.0,0.0,100.0);
        builder.push("readinessWeights");
        READINESS_CIVILITY_WEIGHT=builder.defineInRange("civility",.30,0.0,1.0);READINESS_ACTIVITY_WEIGHT=builder.defineInRange("activity",.30,0.0,1.0);READINESS_SAFETY_WEIGHT=builder.defineInRange("safeConstruction",.20,0.0,1.0);READINESS_FORTIFICATION_WEIGHT=builder.defineInRange("fortification",.20,0.0,1.0);
        builder.pop();
        builder.push("fortificationScore");FORT_WALL_WEIGHT=builder.defineInRange("continuousWall",45.0,0.0,100.0);FORT_ENTRANCE_WEIGHT=builder.defineInRange("controlledEntrance",15.0,0.0,100.0);FORT_GATE_WEIGHT=builder.defineInRange("passableGate",15.0,0.0,100.0);FORT_PATH_WEIGHT=builder.defineInRange("insideSafePath",25.0,0.0,100.0);FORT_GAP_PENALTY=builder.defineInRange("unprotectedGapPenalty",50.0,0.0,100.0);builder.pop();
        builder.pop();
        builder.pop();
        builder.push("buildings");
        BUILDING_SCAN_CELL_LIMIT=builder.comment("Hard cap on standable cells visited by one registration scan.").defineInRange("scanCellLimit",512,32,4096);
        BUILDING_SCAN_HORIZONTAL_RADIUS=builder.comment("Maximum horizontal distance from the selected interior cell.").defineInRange("scanHorizontalRadius",16,4,64);
        BUILDING_SCAN_VERTICAL_RADIUS=builder.comment("Maximum vertical distance from the selected interior cell.").defineInRange("scanVerticalRadius",8,2,32);
        BUILDING_REVALIDATION_QUEUE_LIMIT=builder.comment("Hard cap on queued local building revalidations.").defineInRange("revalidationQueueLimit",1024,16,16384);
        BUILDING_REVALIDATION_PER_TICK=builder.comment("Maximum stale buildings revalidated on one server tick.").defineInRange("revalidationPerTick",2,1,64);
        BUILDING_DASHBOARD_SCAN_LIMIT=builder.comment("Hard cap on building records read for one city dashboard or diagnostic.").defineInRange("dashboardScanLimit",4096,64,65536);
        BUILDING_DASHBOARD_RECORD_LIMIT=builder.comment("Maximum individual building rows sent to one city dashboard.").defineInRange("dashboardRecordLimit",16,1,64);
        BUILDING_STORAGE_AUTHORIZATION_TICKS=builder.comment("Game-time expiry for one real-container selection session.").defineInRange("storageAuthorizationTicks",1200,100,72000);
        BUILDING_STORAGE_AUTHORIZATION_SESSIONS=builder.comment("Hard server-wide cap on simultaneous storage authorization sessions.").defineInRange("storageAuthorizationSessions",64,1,1024);
        builder.pop();
        builder.push("population");
        POPULATION_TICKS_PER_YEAR=builder.comment("First-pass hypothesis: one citizen year in server ticks.").defineInRange("ticksPerYear",24000,1200,Integer.MAX_VALUE);
        POPULATION_ADOLESCENT_AT=builder.defineInRange("adolescentAtYears",12,1,100);
        POPULATION_YOUNG_ADULT_AT=builder.defineInRange("youngAdultAtYears",18,2,120);
        POPULATION_MATURE_ADULT_AT=builder.defineInRange("matureAdultAtYears",35,3,140);
        POPULATION_ELDER_AT=builder.defineInRange("elderAtYears",60,4,200);
        POPULATION_AGING_INTERVAL_TICKS=builder.comment("Ticks between bounded citizen aging batches.").defineInRange("agingIntervalTicks",1200,20,72000);
        POPULATION_AGING_BATCH_SIZE=builder.comment("Maximum citizens advanced in one aging batch.").defineInRange("agingBatchSize",32,1,1024);
        POPULATION_MIN_LIFESPAN_YEARS=builder.comment("First-pass lower bound for deterministic NPC lifespan.").defineInRange("minimumLifespanYears",60,1,300);
        POPULATION_MAX_LIFESPAN_YEARS=builder.comment("First-pass upper bound; effective value is never below the minimum.").defineInRange("maximumLifespanYears",90,1,300);
        POPULATION_WORKER_THREADS=builder.comment("Fixed pure-computation worker count; never scales with population.").defineInRange("workerThreads",2,1,8);
        POPULATION_WORK_QUEUE_CAP=builder.comment("Hard cap on immutable population snapshots awaiting worker execution.").defineInRange("workerQueueCapacity",256,1,8192);
        POPULATION_INTENT_QUEUE_CAP=builder.comment("Hard cap on calculated citizen intents awaiting server-thread revalidation.").defineInRange("intentQueueCapacity",256,1,8192);
        POPULATION_INTENTS_APPLY_PER_TICK=builder.comment("Maximum calculated citizen intents revalidated on one server tick.").defineInRange("intentsAppliedPerTick",32,1,1024);
        POPULATION_INTENT_MAX_AGE_TICKS=builder.comment("First-pass maximum age of a background result before it is discarded and recalculated.").defineInRange("intentMaximumAgeTicks",2400,20,72000);
        POPULATION_DASHBOARD_SCAN_LIMIT=builder.comment("Hard per-root record cap for one on-demand population dashboard snapshot.").defineInRange("dashboardScanLimit",4096,64,65536);
        builder.push("marriage");
        MARRIAGE_NPC_WILLINGNESS_MINIMUM=builder.comment("First-pass NPC consent threshold; player gender is never part of eligibility.").defineInRange("npcWillingnessMinimum",60.0,0.0,100.0);
        MARRIAGE_PROPOSAL_DURATION_TICKS=builder.comment("Game-time duration of a pending player proposal.").defineInRange("proposalDurationTicks",24000,200,720000);
        MARRIAGE_PROPOSAL_COOLDOWN_TICKS=builder.comment("Anti-spam game-time cooldown after creating a proposal; does not define divorce or widowhood rules.").defineInRange("proposalCooldownTicks",1200,0,720000);
        MARRIAGE_MAX_STORED_PROPOSALS=builder.comment("Hard cap across pending and retained terminal proposals.").defineInRange("maximumStoredProposals",4096,16,65536);
        MARRIAGE_MAINTENANCE_INTERVAL_TICKS=builder.comment("Ticks between bounded proposal expiry and pruning batches.").defineInRange("maintenanceIntervalTicks",200,20,72000);
        MARRIAGE_MAINTENANCE_BATCH_SIZE=builder.comment("Maximum proposal records examined by one maintenance batch.").defineInRange("maintenanceBatchSize",32,1,1024);
        MARRIAGE_TERMINAL_RETENTION_TICKS=builder.comment("Game-time retention for explainable recent terminal proposal results.").defineInRange("terminalRetentionTicks",72000,200,Integer.MAX_VALUE);
        HOUSEHOLD_CHILD_CAPACITY=builder.comment("First-pass gameplay capacity reserved for later birth/adoption; hard NBT safety cap remains 256.").defineInRange("householdChildCapacity",8,0,64);
        NPC_MARRIAGE_INTERVAL_TICKS=builder.comment("First-pass interval for bounded autonomous NPC matching.").defineInRange("npcMatchingIntervalTicks",1200,20,72000);
        NPC_MARRIAGE_SCAN_BATCH=builder.comment("Maximum citizens examined by one autonomous matching run.").defineInRange("npcMatchingScanBatch",64,2,1024);
        NPC_MARRIAGE_PAIRS_PER_RUN=builder.comment("Maximum NPC households created by one autonomous matching run.").defineInRange("npcMatchingPairsPerRun",2,1,64);
        builder.pop();
        builder.push("reproduction");
        REPRODUCTION_INTERVAL_TICKS=builder.comment("First-pass interval between bounded autonomous household conception passes.").defineInRange("evaluationIntervalTicks",1200,20,72000);
        REPRODUCTION_HOUSEHOLDS_PER_RUN=builder.comment("Maximum households examined in one conception pass.").defineInRange("householdsPerRun",32,1,1024);
        REPRODUCTION_CITIZEN_SCAN_BATCH=builder.comment("Maximum citizens examined for non-marital autonomous NPC reproduction in one pass.").defineInRange("citizenScanBatch",64,2,1024);
        REPRODUCTION_PAIRS_PER_RUN=builder.comment("Maximum non-spouse NPC pairs attempted in one autonomous pass.").defineInRange("nonSpousePairsPerRun",2,1,64);
        REPRODUCTION_CONDITION_SCAN_LIMIT=builder.comment("Maximum citizens and buildings examined to explain one reproduction condition snapshot.").defineInRange("conditionScanLimit",4096,64,65536);
        REPRODUCTION_CASUALTY_RECOVERY_TICKS=builder.comment("Recent permanent deaths within this game-time window reduce, but never block, conception willingness.").defineInRange("casualtyRecoveryTicks",168000,1200,1440000);
        builder.push("conditionWeights");
        REPRODUCTION_HOUSING_WEIGHT=builder.defineInRange("housing",.20,0.0,1.0);REPRODUCTION_FOOD_WEIGHT=builder.defineInRange("food",.20,0.0,1.0);REPRODUCTION_SAFETY_WEIGHT=builder.defineInRange("safety",.15,0.0,1.0);REPRODUCTION_CIVILITY_WEIGHT=builder.defineInRange("civility",.10,0.0,1.0);REPRODUCTION_ACTIVITY_WEIGHT=builder.defineInRange("activity",.10,0.0,1.0);REPRODUCTION_FAMILY_WEIGHT=builder.defineInRange("familyStability",.10,0.0,1.0);REPRODUCTION_CASUALTY_WEIGHT=builder.defineInRange("casualtyRecovery",.05,0.0,1.0);REPRODUCTION_UNCROWDED_WEIGHT=builder.defineInRange("uncrowded",.10,0.0,1.0);
        builder.pop();
        PREGNANCY_DURATION_TICKS=builder.comment("First-pass pregnancy duration: three Minecraft days; server downtime is not backfilled.").defineInRange("pregnancyDurationTicks",72000,1200,720000);
        BIRTH_COOLDOWN_TICKS=builder.comment("First-pass post-birth cooldown: seven Minecraft days.").defineInRange("birthCooldownTicks",168000,1200,1440000);
        PREGNANCY_RECORD_CAP=builder.comment("Hard cap on simultaneously persisted pregnancies.").defineInRange("pregnancyRecordCap",4096,16,65536);
        REPRODUCTION_CONSENT_DURATION_TICKS=builder.comment("Lifetime of a persisted player-to-player reproduction request.").defineInRange("consentDurationTicks",24000,200,72000);
        REPRODUCTION_CONSENT_CAP=builder.comment("Hard cap on pending player reproduction requests.").defineInRange("consentCap",4096,16,65536);
        PREGNANCIES_PER_TICK=builder.comment("Maximum due pregnancies revalidated and committed on one server tick.").defineInRange("pregnanciesPerTick",4,1,128);
        HOUSEHOLD_CHILD_SAFETY_CAP=builder.comment("NBT safety cap; housing and family capacity affect willingness rather than blocking an already due birth.").defineInRange("householdChildSafetyCap",256,16,256);
        PARENTAGE_PER_DEATH=builder.comment("Maximum source-backed children reconciled immediately for one permanent parent death.").defineInRange("parentagePerDeath",256,1,256);
        builder.pop();
        builder.push("adoption");
        ADOPTION_INTERVAL_TICKS=builder.comment("First-pass interval between bounded autonomous NPC adoption passes.").defineInRange("evaluationIntervalTicks",1200,20,72000);
        ADOPTION_ORPHANS_PER_RUN=builder.comment("Maximum real orphan records examined in one pass.").defineInRange("orphansPerRun",8,1,256);
        ADOPTION_CANDIDATES_PER_ORPHAN=builder.comment("Maximum local NPC families or single adults scored for one orphan.").defineInRange("candidatesPerOrphan",64,1,1024);
        ADOPTION_MAX_DISTANCE_BLOCKS=builder.comment("Hard local-distance limit for adoption; missing spatial evidence is never treated as nearby.").defineInRange("maximumDistanceBlocks",128,16,1024);
        ADOPTION_CONSENT_TICKS=builder.comment("First-pass lifetime of a player-family adoption request in server game ticks.").defineInRange("playerConsentTicks",24000,200,720000);
        ADOPTION_CONSENT_CAP=builder.comment("Hard server-wide cap on pending player-family adoption requests.").defineInRange("playerConsentCap",64,1,1024);
        ADOPTION_CONSENT_MAINTENANCE_BATCH=builder.comment("Maximum player-family adoption requests checked for expiry per pass.").defineInRange("consentMaintenanceBatch",16,1,256);
        builder.pop();
        builder.push("migration");
        MIGRATION_INTERVAL_TICKS=builder.comment("First-pass interval between bounded city attraction rolls.").defineInRange("appearanceIntervalTicks",24000,200,720000);
        MIGRATION_ACTIVE_GROUP_CAP=builder.comment("Hard server-wide cap on approaching, waiting, or departing migrant households.").defineInRange("activeGroupCap",16,1,256);
        MIGRATION_GROUPS_PER_TICK=builder.comment("Maximum active migrant groups whose entities and route state are processed per tick.").defineInRange("groupsPerTick",2,1,64);
        MIGRATION_DECISION_TICKS=builder.comment("Game-time allowed for a manager to decide an arrived household application.").defineInRange("decisionTicks",24000,200,720000);
        MIGRATION_ACTIVATION_DISTANCE=builder.comment("A player must be this close before a persisted migrant can become visible; invisible migrants never move.").defineInRange("activationDistance",96,16,512);
        MIGRATION_ARRIVAL_DISTANCE=builder.comment("Distance from the city core at which the whole household has physically arrived.").defineInRange("arrivalDistance",6,2,32);
        MIGRATION_MAX_MEMBERS=builder.comment("First-pass maximum members generated in one household; domain safety cap is eight.").defineInRange("maximumMembers",4,1,8);
        MIGRATION_EDGE_CHUNKS_SCAN_LIMIT=builder.comment("Maximum owned chunks examined while finding a loaded unclaimed migration origin; truncation is diagnosed and fails safely if no edge is found.").defineInRange("edgeChunksScanLimit",4096,16,65536);
        MIGRATION_SAFE_COLUMNS=builder.comment("Hard number of candidate surface columns checked when finding one unclaimed edge origin.").defineInRange("safeColumns",32,4,256);
        MIGRATION_COUPLE_CHANCE=builder.comment("First-pass household composition hypothesis.").defineInRange("coupleChance",.70,0.0,1.0);
        MIGRATION_CHILD_CHANCE=builder.comment("First-pass chance that a generated couple migrates with one source-backed child.").defineInRange("childChance",.35,0.0,1.0);
        MIGRATION_SECOND_CHILD_CHANCE=builder.comment("Conditional first-pass chance for a second source-backed child.").defineInRange("secondChildChance",.25,0.0,1.0);
        OUT_MIGRATION_INTERVAL_TICKS=builder.comment("First-pass interval between bounded autonomous settled-resident out-migration passes.").defineInRange("outMigrationIntervalTicks",24000,200,720000);
        OUT_MIGRATION_HOUSEHOLDS_PER_RUN=builder.comment("Maximum persisted households evaluated per out-migration pass.").defineInRange("outMigrationHouseholdsPerRun",16,1,256);
        OUT_MIGRATION_CITIZENS_PER_RUN=builder.comment("Maximum household-free citizens evaluated per out-migration pass.").defineInRange("outMigrationCitizensPerRun",16,1,256);
        OUT_MIGRATION_STARTS_PER_RUN=builder.comment("Maximum real departing groups started in one pass.").defineInRange("outMigrationStartsPerRun",2,1,32);
        OUT_MIGRATION_MAX_CHANCE=builder.comment("First-pass maximum per-pass departure probability after the explainable pressure score.").defineInRange("outMigrationMaximumChance",.20,0.0,1.0);
        builder.pop();
        NPC_MATERIALIZE_DISTANCE=builder.comment("First-pass visible entity radius in blocks.").defineInRange("materializeDistance",48,8,256);
        NPC_PREWARM_DISTANCE=builder.comment("Outer interest radius; effective value is never below materializeDistance.").defineInRange("prewarmDistance",64,8,384);
        NPC_EXIT_DISTANCE=builder.comment("Hysteresis exit radius; effective value is never below prewarmDistance.").defineInRange("exitDistance",72,8,512);
        NPC_PREWARM_TICKS=builder.comment("Minimum preparation time before creating an entity.").defineInRange("prewarmTicks",20,1,1200);
        NPC_PREWARM_TIMEOUT_TICKS=builder.comment("Maximum continuous cache residency before a failed prewarm yields its slot.").defineInRange("prewarmTimeoutTicks",200,20,72000);
        NPC_PREWARM_CAP=builder.comment("Hard cap on citizens retained in the in-memory prewarming cache.").defineInRange("prewarmCap",256,1,8192);
        NPC_MATERIALIZATION_BATCH_SIZE=builder.comment("Maximum citizen state decisions on one server tick.").defineInRange("materializationBatchSize",32,1,1024);
        NPC_ENTITY_CAP=builder.comment("Hard cap on materialized Civitas citizens per server.").defineInRange("entityCap",128,1,4096);
        NPC_EQUIPMENT_DEATH_DROPS_PER_TICK=builder.comment("Maximum dead-citizen equipment snapshots checked for real world drops per server tick; chunks are never force-loaded.").defineInRange("equipmentDeathDropsPerTick",4,1,64);
        builder.pop();
        builder.push("securityBaseline");
        SECURITY_CELLS_PER_TICK=builder.comment("Maximum diagnostic SecurityCells refreshed on one server tick.").defineInRange("cellsPerTick",4,1,128);
        SECURITY_QUEUE_LIMIT=builder.comment("Hard cap on the rotating SecurityCell work queue.").defineInRange("queueLimit",2048,16,65536);
        SECURITY_REFRESH_TICKS=builder.comment("Minimum interval before a persisted SecurityCell is recomputed.").defineInRange("refreshTicks",200,20,72000);
        SECURITY_TOPOLOGY_VISIT_LIMIT=builder.comment("Hard cap on territory nodes visited for one border-distance calculation.").defineInRange("topologyVisitLimit",1024,16,65536);
        SECURITY_BUILDING_RECORD_LIMIT_PER_CELL=builder.comment("Hard cap on building records linked into one diagnostic SecurityCell.").defineInRange("buildingRecordsPerCell",128,1,4096);
        INFILTRATION_WORLD_SAMPLES_PER_CELL=builder.comment("Hard block-read budget for one infiltration evidence refresh; unloaded chunks are never forced.").defineInRange("infiltrationWorldSamplesPerCell",256,16,8192);
        INFILTRATION_CANDIDATES_PER_CELL=builder.comment("Hard candidate cap retained from one SecurityCell scan.").defineInRange("infiltrationCandidatesPerCell",16,1,128);
        INFILTRATION_EVENT_CELL_CAP=builder.comment("Maximum persisted SecurityCells considered when choosing one event location.").defineInRange("infiltrationEventCellCap",256,1,4096);
        INFILTRATION_EVENT_CANDIDATE_CAP=builder.comment("Maximum fully explained candidates persisted for one invasion event.").defineInRange("infiltrationEventCandidateCap",128,1,InfiltrationPlan.HARD_CANDIDATE_CAP);
        INFILTRATION_RETRY_TICKS=builder.comment("Minimum delay before retrying a city whose loaded area has no currently legal infiltration source.").defineInRange("infiltrationRetryTicks",1200,20,72000);
        INFILTRATION_MAX_WARNING_BONUS_TICKS=builder.comment("Maximum extra warning time produced by very low local risk after an event is not intercepted.").defineInRange("infiltrationMaxWarningBonusTicks",1200,0,72000);
        INFILTRATION_LOCAL_SPAWN_ATTEMPTS=builder.comment("Hard standability checks used to place each mob near the selected legal source.").defineInRange("infiltrationLocalSpawnAttempts",24,1,128);
        INFILTRATION_BORDER_SAMPLES_PER_EDGE=builder.comment("Evenly spaced breach samples along each exposed city-cell edge.").defineInRange("infiltrationBorderSamplesPerEdge",3,1,14);
        INFILTRATION_UNDERGROUND_COLUMNS_PER_CELL=builder.comment("Maximum deterministic underground columns inspected in one cell refresh.").defineInRange("infiltrationUndergroundColumnsPerCell",16,1,64);
        INFILTRATION_VERTICAL_DEPTH=builder.comment("Maximum blocks below the local surface inspected for caves and dark underground space.").defineInRange("infiltrationVerticalDepth",48,4,256);
        INFILTRATION_CAVE_MOUTH_DISTANCE=builder.comment("Horizontal sky-access distance used to distinguish a cave mouth from enclosed underground darkness.").defineInRange("infiltrationCaveMouthDistance",2,1,8);
        SECURITY_FAILURE_MEMORY_TICKS=builder.comment("Diagnostic decay window for a recent local defense failure.").defineInRange("failureMemoryTicks",24000,20,720000);
        SECURITY_FULL_SCALE_CHUNKS=builder.comment("Diagnostic city size that reaches full scale exposure.").defineInRange("fullScaleChunks",64,9,4096);
        SECURITY_CIVILITY_WEIGHT=builder.defineInRange("civilityWeight",1.0,0.0,10.0);SECURITY_ACTIVITY_WEIGHT=builder.defineInRange("activityWeight",1.0,0.0,10.0);SECURITY_BUILT_SAFETY_WEIGHT=builder.defineInRange("builtSafetyWeight",1.0,0.0,10.0);SECURITY_PATROL_WEIGHT=builder.defineInRange("patrolCoverageWeight",1.0,0.0,10.0);SECURITY_GUARD_WEIGHT=builder.defineInRange("guardResponseWeight",1.0,0.0,10.0);SECURITY_INFILTRATION_WEIGHT=builder.defineInRange("infiltrationAccessWeight",1.0,0.0,10.0);SECURITY_UNDERGROUND_WEIGHT=builder.defineInRange("undergroundDarknessWeight",.75,0.0,10.0);SECURITY_BORDER_WEIGHT=builder.defineInRange("borderExposureWeight",1.0,0.0,10.0);SECURITY_NEGLECT_WEIGHT=builder.defineInRange("neglectWeight",1.0,0.0,10.0);SECURITY_FAILURE_WEIGHT=builder.defineInRange("recentFailureWeight",1.0,0.0,10.0);SECURITY_CITY_SCALE_WEIGHT=builder.defineInRange("cityScaleWeight",.5,0.0,10.0);
        INFILTRATION_GUARDED_THRESHOLD=builder.comment("Coverage at or above this first-pass value turns a valid entrance candidate into disguised entry rather than uncontrolled entry.").defineInRange("infiltrationGuardedThreshold",50.0,0.0,100.0);
        INFILTRATION_UNCONTROLLED_ENTRANCE_WEIGHT=builder.defineInRange("uncontrolledEntranceWeight",1.0,0.0,10.0);INFILTRATION_WALL_GAP_WEIGHT=builder.defineInRange("wallGapWeight",1.0,0.0,10.0);INFILTRATION_CAVE_WEIGHT=builder.defineInRange("caveWeight",.8,0.0,10.0);INFILTRATION_UNDERGROUND_DARKNESS_WEIGHT=builder.defineInRange("undergroundDarknessSourceWeight",.75,0.0,10.0);INFILTRATION_DISGUISED_ENTRY_WEIGHT=builder.defineInRange("disguisedEntryWeight",.35,0.0,10.0);
        INFILTRATION_SECURITY_COMPONENT_WEIGHT=builder.defineInRange("infiltrationSecurityComponentWeight",.5,0.0,1.0);INFILTRATION_DARKNESS_COMPONENT_WEIGHT=builder.defineInRange("infiltrationDarknessComponentWeight",.2,0.0,1.0);INFILTRATION_UNGUARDED_COMPONENT_WEIGHT=builder.defineInRange("infiltrationUnguardedComponentWeight",.3,0.0,1.0);
        INFILTRATION_MINIMUM_WAVE_SCALE=builder.comment("Lowest wave-size multiplier obtainable from excellent local security after an event evades interception.").defineInRange("infiltrationMinimumWaveScale",.5,.1,1.0);
        PATROL_ROUTE_CITY_CAP=builder.comment("Hard cap on persisted patrol routes per city.").defineInRange("patrolRouteCityCap",16,1,256);
        PATROL_ROUTE_NODE_CAP=builder.comment("Hard cap on player-drawn nodes per patrol route.").defineInRange("patrolRouteNodeCap",24,2,PatrolRoute.HARD_NODE_CAP);
        PATROL_ROUTE_SEGMENT_BLOCKS=builder.comment("First-pass maximum straight traversable distance between adjacent patrol nodes.").defineInRange("patrolRouteSegmentBlocks",24,2,128);
        PATROL_ROUTE_PATH_SAMPLE_CAP=builder.comment("Hard world-sample cap for one route confirmation.").defineInRange("patrolRoutePathSampleCap",512,8,8192);
        PATROL_ROUTE_SESSION_TICKS=builder.comment("Server-tick timeout for one world route drawing session.").defineInRange("patrolRouteSessionTicks",1200,100,72000);
        PATROL_ASSIGNMENT_CITY_CAP=builder.comment("Hard cap on persisted guard assignments per city; one route may have one guard per fixed shift.").defineInRange("patrolAssignmentCityCap",32,1,512);
        PATROL_ASSIGNMENTS_PER_TICK=builder.comment("Maximum guard assignments revalidated or advanced on one server tick.").defineInRange("patrolAssignmentsPerTick",8,1,128);
        PATROL_VISIBLE_DRIVES_PER_TICK=builder.comment("Hard cap on visible guard navigation drives issued on one server tick.").defineInRange("patrolVisibleDrivesPerTick",32,1,256);
        PATROL_COVERAGE_MEMORY_TICKS=builder.comment("First-pass time that a completed patrol sample contributes recent coverage.").defineInRange("patrolCoverageMemoryTicks",1200,20,72000);
        PATROL_VIRTUAL_NODE_TICKS=builder.comment("First-pass on-duty server ticks required for an invisible guard to advance one validated route node.").defineInRange("patrolVirtualNodeTicks",200,20,72000);
        PATROL_NODE_REACH_DISTANCE=builder.comment("Visible guard distance in blocks for reaching a patrol node.").defineInRange("patrolNodeReachDistance",2.0,.5,8.0);
        GUARD_MINIMUM_WILLINGNESS=builder.comment("Voluntary appointment threshold; a lord may force a lower score and the negative result remains recorded.").defineInRange("guardMinimumWillingness",60.0,0.0,100.0);
        GUARD_SETTLEMENT_WEIGHT=builder.defineInRange("guardSettlementWeight",.35,0.0,1.0);GUARD_SAFETY_WEIGHT=builder.defineInRange("guardSafetyWeight",.15,0.0,1.0);GUARD_WEAPON_WEIGHT=builder.defineInRange("guardWeaponWeight",.20,0.0,1.0);GUARD_ARMOR_WEIGHT=builder.defineInRange("guardArmorWeight",.10,0.0,1.0);GUARD_SHIELD_WEIGHT=builder.defineInRange("guardShieldWeight",.05,0.0,1.0);GUARD_SHIFT_WEIGHT=builder.defineInRange("guardShiftWeight",.05,0.0,1.0);GUARD_RELIABILITY_WEIGHT=builder.defineInRange("guardReliabilityWeight",.10,0.0,1.0);
        BACKGROUND_BATTLES_PER_TICK=builder.comment("Maximum committed invasions considered for off-screen combat on one server tick.").defineInRange("backgroundBattlesPerTick",2,1,32);
        BACKGROUND_BATTLE_ROUND_TICKS=builder.comment("Server ticks between off-screen combat rounds; shutdown time never advances it.").defineInRange("backgroundBattleRoundTicks",200,20,72000);
        BACKGROUND_BATTLE_PARTICIPANT_CAP=builder.comment("Hard total participant roster cap locked when the first invasion mob spawns.").defineInRange("backgroundBattleParticipantCap",32,1,InvasionCommitment.HARD_PARTICIPANT_CAP);
        BACKGROUND_BATTLE_CITIZEN_SCAN_CAP=builder.comment("Maximum city citizens inspected when locking a local invasion roster.").defineInRange("backgroundBattleCitizenScanCap",256,1,4096);
        BACKGROUND_BATTLE_CIVILIAN_RADIUS=builder.comment("Maximum last-known distance for civilians exposed to an invasion site.").defineInRange("backgroundBattleCivilianRadius",64,8,256);
        BACKGROUND_BATTLE_CIVILIAN_CAP=builder.comment("Maximum nearby civilians locked into one invasion commitment.").defineInRange("backgroundBattleCivilianCap",16,0,64);
        BACKGROUND_BATTLE_TARGETS_PER_ROUND=builder.defineInRange("backgroundBattleTargetsPerRound",2,1,32);
        BACKGROUND_BATTLE_MAX_DAMAGE_PER_ROUND=builder.defineInRange("backgroundBattleMaximumDamagePerRound",35,1,100);
        BACKGROUND_BATTLE_CIVILIAN_EXPOSURE_ROUND=builder.comment("First off-screen round where surviving enemies may reach civilians even while guards remain.").defineInRange("backgroundBattleCivilianExposureRound",3,0,100);
        VISIBLE_INVASION_MOBS_PER_TICK=builder.comment("Maximum loaded invasion mobs whose citizen target is revalidated on one tick.").defineInRange("visibleInvasionMobsPerTick",16,1,256);
        VISIBLE_INVASION_TARGET_RADIUS=builder.comment("Maximum blocks between a loaded invasion mob and a locked citizen participant target.").defineInRange("visibleInvasionTargetRadius",48,8,128);
        VIRTUAL_INVASION_MATERIALIZATIONS_PER_TICK=builder.comment("Maximum abstract surviving enemies restored into one loaded invasion source per threat update.").defineInRange("virtualInvasionMaterializationsPerTick",8,1,64);
        BACKGROUND_BATTLE_WEAPON_POWER=builder.defineInRange("backgroundBattleWeaponPower",2.0,0.0,100.0);BACKGROUND_BATTLE_ENEMY_DURABILITY=builder.defineInRange("backgroundBattleEnemyDurability",4.0,.1,100.0);BACKGROUND_BATTLE_ENEMY_DAMAGE=builder.defineInRange("backgroundBattleEnemyDamage",6.0,0.0,100.0);BACKGROUND_BATTLE_ARMOR_REDUCTION_PER_PIECE=builder.defineInRange("backgroundBattleArmorReductionPerPiece",.08,0.0,.25);BACKGROUND_BATTLE_SHIELD_REDUCTION=builder.defineInRange("backgroundBattleShieldReduction",.15,0.0,1.0);BACKGROUND_BATTLE_MAXIMUM_REDUCTION=builder.defineInRange("backgroundBattleMaximumReduction",.65,0.0,.95);
        builder.pop();
        builder.push("naturalSpawning");
        NATURAL_SPAWN_MULTIPLIER = builder.comment("Multiplier for the shared vanilla natural hostile-mob cap. Other mob categories are unchanged.")
                .defineInRange("multiplier", 1.0, 0.0, 16.0);
        CIVILITY_SUPPRESSION_CURVE = builder.comment("Piecewise-linear civility:spawn-suppression points. Suppression is a 0..1 fraction.")
                .defineList("civilitySuppressionCurve", List.of("0:0", "20:0.10", "40:0.30", "60:0.55", "80:0.75", "100:0.90"),
                        value -> value instanceof String text && text.matches("\\d+(?:\\.\\d+)?:0(?:\\.\\d+)?|\\d+(?:\\.\\d+)?:1(?:\\.0+)?"));
        builder.pop();
        builder.push("civilization");
        CIVILITY_GROWTH_PER_CYCLE = builder.defineInRange("growthPerCycle", 0.25, 0.0, 100.0);
        CIVILITY_DECLINE_PER_CYCLE = builder.defineInRange("declinePerCycle", 0.5, 0.0, 100.0);
        CIVILITY_STABILITY_TICKS = builder.comment("Minimum unchanged time before scanner results may contribute fully.")
                .defineInRange("stabilityTicks", 1200, 20, 72000);
        CIVILITY_SCAN_BUDGET_MICROS = builder.comment("Soft per-tick civility scan scheduling budget in microseconds.")
                .defineInRange("scanBudgetMicros", 2000, 100, 50000);
        builder.push("factorWeights");
        CIVILITY_BUILDING_WEIGHT=builder.defineInRange("building",.35,0.0,1.0);CIVILITY_FACILITIES_WEIGHT=builder.defineInRange("facilities",.25,0.0,1.0);CIVILITY_SAFETY_WEIGHT=builder.defineInRange("safety",.25,0.0,1.0);CIVILITY_CONNECTIVITY_WEIGHT=builder.defineInRange("connectivity",.15,0.0,1.0);
        builder.pop();
        builder.push("activity");
        ACTIVITY_WINDOW_TICKS = builder.defineInRange("windowTicks", 1200, 20, 72000);
        ACTIVITY_MOVEMENT_SAMPLE_TICKS = builder.defineInRange("movementSampleTicks", 100, 1, 1200);
        ACTIVITY_MOVEMENT_CELL_SIZE = builder.defineInRange("movementCellSize", 8, 1, 64);
        ACTIVITY_GRACE_TICKS = builder.defineInRange("graceTicks", 6000, 0, 720000);
        ACTIVITY_DECAY_PER_WINDOW = builder.defineInRange("decayPerWindow", 0.25, 0.0, 100.0);
        ACTIVITY_GAIN_PER_CATEGORY = builder.defineInRange("gainPerCategory", 0.5, 0.0, 100.0);
        ACTIVITY_PROPAGATION_RATIO = builder.defineInRange("propagationRatio", 0.35, 0.0, 1.0);
        ACTIVITY_PROPAGATION_CAP = builder.defineInRange("propagationCapPerWindow", 1.0, 0.0, 100.0);
        ACTIVITY_LOCAL_GAIN_CAP = builder.defineInRange("localGainCapPerWindow", 3.5, 0.0, 100.0);
        builder.pop();
        builder.pop();
        builder.push("naturalSpawning");
        builder.push("regionClassifier");
        REGION_SURFACE_PATH = builder.defineInRange("surfacePathDistance", 8, 1, 32);
        REGION_INTERIOR_PATH = builder.defineInRange("interiorPathDistance", 20, 2, 64);
        REGION_SHALLOW_DEPTH = builder.defineInRange("shallowDepth", 8, 1, 64);
        REGION_UNDERGROUND_DEPTH = builder.defineInRange("undergroundDepth", 12, 1, 128);
        REGION_THIN_COVERAGE = builder.defineInRange("thinCoverage", 5, 0, 32);
        REGION_UNDERGROUND_COVERAGE = builder.defineInRange("undergroundCoverage", 8, 1, 128);
        REGION_HORIZONTAL_RADIUS = builder.defineInRange("horizontalSearchRadius", 24, 8, 64);
        REGION_VERTICAL_RADIUS = builder.defineInRange("verticalSearchRadius", 16, 4, 64);
        REGION_NODE_LIMIT = builder.defineInRange("bfsNodeLimit", 4096, 128, 32768);
        REGION_ENCLOSURE_THRESHOLD = builder.defineInRange("enclosureThreshold", 0.34, 0.0, 1.0);
        REGION_UNDERGROUND_SCORE = builder.defineInRange("undergroundScoreThreshold", 0.62, 0.0, 1.0);
        builder.pop();
        builder.pop();
        SPEC = builder.build();
    }

    private CivitasConfig() {}
}
